### PR TITLE
BACKLOG-5863 Cannot rename files in folders

### PR DESCRIPTION
**Pull request by AliaksandrDrebenchuk**
fixed:
 - submit by another event
 - dialog render only after the name init
 - 'rename' servlet without the extension check

### CODE REVIEW

**Comment by AliaksandrDrebenchuk** [comment]
@pedrofvteixeira @dkincade @rmansoor please review

**Comment by pedrofvteixeira** [comment]
Unit tests failure:

FileResourceTest.testDoRenameWithoutExtension
FileResourceTest.testDoRenameIncorrectExtension

Please look into those and re-issue PR.
In addition, would it be possible to add some unit tests, that focus on this change ?

Thanks Aliaksandr

**Comment by AliaksandrDrebenchuk** [comment]
@pedrofvteixeira @dkincade @rmansoor 
tests were fixed, please review

**Comment by AliaksandrDrebenchuk** [comment]
@pedrofvteixeira @dkincade @rmansoor please review

**Comment by dkincade** [comment]
@pentaho-nbaker - due to the short staff today, can you please review this case and the pull request.

**Comment by pentaho-nbaker** [comment]
What a mess. Looks like the code fits the logic. Accepting to see how it works in QA.

**Pull request merged**
