### PR TITLE
[BISERVER-13625] - When the server is started for the first time, it uses a resource string for the name of the "Home" folder.

### PR DESCRIPTION
**Pull request by andreramos89**

### CODE REVIEW

**Comment by andreramos89** [comment]
@smmribeiro 
@renato-s 
@bcostahitachivantara

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 23m 33s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 21m 51s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 23m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 23m 45s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
