### PR TITLE
BACKLOG-9185 - Downloaded zip doesn't contain corresponding *.eml file

### PR DESCRIPTION
**Pull request by EgorZhuk**
@tmorgner probably we should consider having another 5 places to apply your changes to in case you want to add new file extension :)

### CODE REVIEW

**Comment by tmorgner** [comment]
@wingman-pentaho I have a null-pointer. Can I spend my air miles to upgrade to one-pointer instead?

**Comment by lucboudreau** [comment]
@tmorgner I'll take a look at this one. It's weird. There is no build command..

**Comment by lucboudreau** [comment]
Figured it out. There is nothing to build. This is a change in the assembly. Should be fixed as soon as I deploy this.

```
https://github.com/pentaho/pentaho-wingman/commit/18211c1cf04e850d52abb493d8e28ed29c84d6e2
```

**Comment by tmorgner** [comment]
Sweet.

**Comment by EgorZhuk** [comment]
@tmorgner then why not to merge it? :)

**Comment by EgorZhuk** [comment]
@tmorgner one more place :+1:

**Comment by tmorgner** [comment]
Not waiting for wingman, as this is an assembly change. Wingman does not pick those up.

**Pull request merged**
