### PR TITLE
[BISERVER-13112] Favourites and recents not being listed since SP SP2…

### PR DESCRIPTION
**Pull request by ivanpogodin**
…01602-6.0.1.2 applied

### CODE REVIEW

**Comment by ivanpogodin** [comment]
Checking now...

**Comment by ivanpogodin** [comment]
@pamval , @tmorgner , @rmansoor , could you review it, please?
PR is updated. Wingman hasn't started again yet.

**Comment by tmorgner** [comment]
Code looks good and sane.

**Comment by tmorgner** [comment]
Merging; ignoring the wingman failure, as it seems unrelated to the actual build. The first one went through nicely and the build script executed correctly on the second one.

**Pull request merged**
