### PR TITLE
[BACKLOG-5217] - Adding a fallback to the datasource lookup logic to using the datsource as it is

### PR DESCRIPTION
**Pull request by rmansoor**
Master pull request https://github.com/pentaho/pentaho-platform/pull/2580

### CODE REVIEW

**Comment by rmansoor** [comment]
@dkincade please review

**Comment by dkincade** [comment]
https://github.com/pentaho/pentaho-platform/pull/2580

**Comment by pentaho-nbaker** [comment]
sorry merged the wrong one.

**Comment by dkincade** [comment]
oh boy ... it had better work then :-D

**Pull request merged**
