### PR TITLE
SP-3014 "Allow scheduling" and "Hidden" checkboxes are not imported properly

### PR DESCRIPTION
**Pull request by AliaksandrDrebenchuk**
checkboxes were fixed

### CODE REVIEW

**Comment by AliaksandrDrebenchuk** [comment]
@rfellows @pamval @rmansoor @pentaho-nbaker please take a look

**Comment by AliaksandrDrebenchuk** [comment]
@mbatchelor 
https://github.com/pentaho/pentaho-platform/pull/3197 - 39 files
over here - 39 files

**Comment by pamval** [comment]
Are the changes in https://github.com/pentaho/pentaho-platform/pull/3241 also here?

**Comment by AliaksandrDrebenchuk** [comment]
@pamval yes

**Comment by AliaksandrDrebenchuk** [comment]
@rfellows @pamval @rmansoor @pentaho-nbaker please take a look

**Pull request merged**
