### PR TITLE
[BISERVER-13603] - IE - PDF pane remains active when glass pane was a…

### PR DESCRIPTION
**Pull request by YuryBY**
…ctivated, which blocks user from accepting/declining action in appeared dialog box.

 - additional fix covers the regression

@pamval, could you please take a look?

### CODE REVIEW

**Comment by YuryBY** [comment]
@pamval, the PR should be merged together with https://github.com/pentaho/pentaho-commons-gwt-modules/pull/595. Thanks

**Comment by YuryBY** [comment]
@pamval, @mbatchelor the PR is blocker for SP cases. Thanks.

**Comment by mchen-len-son** [comment]
@YuryBY shouldn't we remove the old changes at https://github.com/pentaho/pentaho-platform/pull/3775/files#diff-11e3f51c8dd386edc6276299ade02d5eR295 ?

**Comment by YuryBY** [comment]
@mchen-len-son, nope. This changes is separate fix for the dropdown menu.

**Comment by mchen-len-son** [comment]
@Yury got it, thanks.
for those who is also wondering how it works.
MantleDialogBox is a more accurate change than in pentaho/pentaho-commons-gwt-modules#595. 
It lets us use the new code when a report is requested for UI, and bypass it when it is being generated in background, therefore fixing the regression found.

**Pull request merged**
