### PR TITLE
[TEST] ChartHelper is refactored

### PR DESCRIPTION
**Pull request by AliaksandrDrebenchuk**
test dependency on jmockit added
ChartHelper refactored
ChartHelperTest is created

### CODE REVIEW

**Comment by AliaksandrDrebenchuk** [comment]
@rmansoor please verify

**Comment by brosander** [comment]
Changed files:
==============
  core/ivy.xml
  core/src/org/pentaho/platform/uifoundation/chart/ChartHelper.java
  core/test-src/org/pentaho/platform/uifoundation/chart/ChartHelperTest.java

Checkstyle violations:
----------------------
Errors:File core/src/org/pentaho/platform/uifoundation/chart/ChartHelper.java
1. Message: 'static' modifier out of order with the JLS suggestions. at Line: 106 Column: 16
2. Message: 'static' modifier out of order with the JLS suggestions. at Line: 107 Column: 16
3. Message: 'static' modifier out of order with the JLS suggestions. at Line: 108 Column: 16
4. Message: 'static' modifier out of order with the JLS suggestions. at Line: 109 Column: 16
5. Message: 'static' modifier out of order with the JLS suggestions. at Line: 110 Column: 16
6. Message: 'static' modifier out of order with the JLS suggestions. at Line: 111 Column: 16
7. Message: 'static' modifier out of order with the JLS suggestions. at Line: 112 Column: 16
8. Message: 'static' modifier out of order with the JLS suggestions. at Line: 113 Column: 16
9. Message: 'static' modifier out of order with the JLS suggestions. at Line: 114 Column: 16
10. Message: 'static' modifier out of order with the JLS suggestions. at Line: 116 Column: 16
11. Message: 'static' modifier out of order with the JLS suggestions. at Line: 117 Column: 16
12. Message: 'static' modifier out of order with the JLS suggestions. at Line: 118 Column: 16
13. Message: 'static' modifier out of order with the JLS suggestions. at Line: 120 Column: 16
14. Message: 'static' modifier out of order with the JLS suggestions. at Line: 122 Column: 16
15. Message: Line has trailing spaces. at Line: 55 Column: None
16. Message: Line has trailing spaces. at Line: 56 Column: None
17. Message: Line has trailing spaces. at Line: 57 Column: None
18. Message: 'static' modifier out of order with the JLS suggestions. at Line: 66 Column: 21File core/test-src/org/pentaho/platform/uifoundation/chart/ChartHelperTest.java
1. Message: '}' is not followed by whitespace. at Line: 101 Column: 10
2. Message: 'static' modifier out of order with the JLS suggestions. at Line: 74 Column: 17
3. Message: 'static' modifier out of order with the JLS suggestions. at Line: 79 Column: 17

Newly Broken Tests:
=================
Test Case Errors:
-----------------
  
org.pentaho.platform.uifoundation.chart.ChartHelperTest.testInitChartType: java.lang.NullPointerException
```
java.lang.NullPointerException
	at org.dom4j.io.SAXReader.read(SAXReader.java:284)
	at org.pentaho.platform.uifoundation.chart.ChartHelperTest$5.getSolutionDocument(ChartHelperTest.java:138)
	at org.pentaho.platform.engine.services.ActionSequenceJCRHelper.getSolutionDocument(ActionSequenceJCRHelper.java)
	at org.pentaho.platform.uifoundation.chart.ChartHelper$Builder.initChartType(ChartHelper.java:204)
	at org.pentaho.platform.uifoundation.chart.ChartHelperTest.testInitChartType(ChartHelperTest.java:208)

```
junit.framework.TestSuite$1.warning: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: No tests found in org.pentaho.platform.util.JSONComparitorTest

```


Unit test coverage change:
============
org.pentaho.platform.uifoundation.messages.Messages:
 * instructionPercentCoverageChange : +100.00%
 * linePercentCoverageChange : +100.00%
 * complexityPercentCoverageChange : +100.00%
 * methodPercentCoverageChange : +100.00%
    
org.pentaho.platform.engine.services.ActionSequenceJCRHelper:
 * instructionPercentCoverageChange : +1.36%
 * branchPercentCoverageChange : +1.09%
 * linePercentCoverageChange : +1.39%
 * complexityPercentCoverageChange : +1.72%
 * methodPercentCoverageChange : +8.33%
    
org.pentaho.platform.engine.core.system.objfac.AggregateObjectFactory.ReferencePriorityComparitor:
 * instructionPercentCoverageChange :**-4.44%**
 * branchPercentCoverageChange :**-10.00%**
 * linePercentCoverageChange :**-7.69%**
 * complexityPercentCoverageChange :**-12.50%**
    
org.pentaho.platform.uifoundation.chart.AbstractChartComponent:
 * instructionPercentCoverageChange : +1.13%
 * linePercentCoverageChange : +1.48%
 * complexityPercentCoverageChange : +1.92%
 * methodPercentCoverageChange : +2.78%
    
org.pentaho.platform.uifoundation.component.xml.XmlComponent:
 * instructionPercentCoverageChange : +4.49%
 * linePercentCoverageChange : +4.17%
 * complexityPercentCoverageChange : +14.29%
 * methodPercentCoverageChange : +33.33%
    
org.pentaho.platform.uifoundation.chart.ChartHelper.LogWriter:
 * branchPercentCoverage :75.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :87.50%
 * instructionPercentCoverage :97.78%
    
org.pentaho.platform.uifoundation.chart.ChartHelper.Error:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :50.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :84.48%
    
org.pentaho.platform.util.logging.SimpleLogger:
 * instructionPercentCoverageChange : +6.06%
 * linePercentCoverageChange : +8.33%
 * complexityPercentCoverageChange : +5.00%
 * methodPercentCoverageChange : +5.26%
    
org.pentaho.platform.engine.security.event.OrderedApplicationEventMulticaster.new Comparator() {...}:
 * instructionPercentCoverageChange :**-6.25%**
 * branchPercentCoverageChange :**-12.50%**
 * linePercentCoverageChange :**-12.50%**
 * complexityPercentCoverageChange :**-16.67%**
    
org.pentaho.platform.engine.services.runtime.TemplateUtil:
 * instructionPercentCoverageChange : +1.26%
 * branchPercentCoverageChange : +0.85%
 * linePercentCoverageChange : +1.97%
 * complexityPercentCoverageChange : +1.35%
 * methodPercentCoverageChange : +7.14%
    
org.pentaho.platform.uifoundation.chart.ChartHelper.Builder:
 * branchPercentCoverage :13.33%
 * linePercentCoverage :27.37%
 * methodPercentCoverage :42.86%
 * complexityPercentCoverage :12.90%
 * instructionPercentCoverage :21.95%

**Comment by brosander** [comment]
Changed files:
==============
  core/ivy.xml
  core/src/org/pentaho/platform/uifoundation/chart/ChartHelper.java
  core/test-src/org/pentaho/platform/uifoundation/chart/ChartHelperTest.java

Checkstyle violations:
----------------------
No errors found

**Comment by AliaksandrDrebenchuk** [comment]
@brosander NullPointerException was fixed

**Comment by lucboudreau** [comment]
Changed files:
==============
  core/ivy.xml
  core/src/org/pentaho/platform/uifoundation/chart/ChartHelper.java
  core/test-res/solution/test/xml/flash_dotchart.xml
  core/test-src/org/pentaho/platform/uifoundation/chart/ChartHelperTest.java

Checkstyle violations:
----------------------
Errors:File core/src/org/pentaho/platform/uifoundation/chart/ChartHelper.java
1. Message: 'static' modifier out of order with the JLS suggestions. at Line: 106 Column: 16
2. Message: 'static' modifier out of order with the JLS suggestions. at Line: 107 Column: 16
3. Message: 'static' modifier out of order with the JLS suggestions. at Line: 108 Column: 16
4. Message: 'static' modifier out of order with the JLS suggestions. at Line: 109 Column: 16
5. Message: 'static' modifier out of order with the JLS suggestions. at Line: 110 Column: 16
6. Message: 'static' modifier out of order with the JLS suggestions. at Line: 111 Column: 16
7. Message: 'static' modifier out of order with the JLS suggestions. at Line: 112 Column: 16
8. Message: 'static' modifier out of order with the JLS suggestions. at Line: 113 Column: 16
9. Message: 'static' modifier out of order with the JLS suggestions. at Line: 114 Column: 16
10. Message: 'static' modifier out of order with the JLS suggestions. at Line: 116 Column: 16
11. Message: 'static' modifier out of order with the JLS suggestions. at Line: 117 Column: 16
12. Message: 'static' modifier out of order with the JLS suggestions. at Line: 118 Column: 16
13. Message: 'static' modifier out of order with the JLS suggestions. at Line: 120 Column: 16
14. Message: 'static' modifier out of order with the JLS suggestions. at Line: 122 Column: 16
15. Message: Line has trailing spaces. at Line: 55 Column: None
16. Message: Line has trailing spaces. at Line: 56 Column: None
17. Message: Line has trailing spaces. at Line: 57 Column: None
18. Message: 'static' modifier out of order with the JLS suggestions. at Line: 66 Column: 21File core/test-src/org/pentaho/platform/uifoundation/chart/ChartHelperTest.java
1. Message: '}' is not followed by whitespace. at Line: 121 Column: 10
2. Message: 'static' modifier out of order with the JLS suggestions. at Line: 94 Column: 17
3. Message: 'static' modifier out of order with the JLS suggestions. at Line: 99 Column: 17

Newly Broken Tests:
-----------------
junit.framework.TestSuite$1.warning: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: No tests found in org.pentaho.platform.util.JSONComparitorTest

```





Unit test coverage change:
============
org.pentaho.platform.uifoundation.messages.Messages:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.platform.engine.services.ActionSequenceJCRHelper:
 * branchPercentCoverage :1.09%
 * linePercentCoverage :1.39%
 * methodPercentCoverage :8.33%
 * complexityPercentCoverage :1.72%
 * instructionPercentCoverage :1.36%
    
org.pentaho.platform.engine.core.system.objfac.AggregateObjectFactory.ReferencePriorityComparitor:
 * instructionPercentCoverageChange :**-4.44%**
 * branchPercentCoverageChange :**-10.00%**
 * linePercentCoverageChange :**-7.69%**
 * complexityPercentCoverageChange :**-12.50%**
    
org.pentaho.platform.uifoundation.chart.AbstractChartComponent:
 * linePercentCoverage :1.48%
 * methodPercentCoverage :2.78%
 * complexityPercentCoverage :1.92%
 * instructionPercentCoverage :1.13%
    
org.pentaho.platform.uifoundation.component.xml.XmlComponent:
 * linePercentCoverage :4.17%
 * methodPercentCoverage :33.33%
 * complexityPercentCoverage :14.29%
 * instructionPercentCoverage :4.49%
    
org.pentaho.platform.uifoundation.chart.ChartHelper.LogWriter:
 * branchPercentCoverage :75.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :87.50%
 * instructionPercentCoverage :97.78%
    
org.pentaho.platform.uifoundation.chart.ChartHelper.Error:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :50.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :84.48%
    
org.pentaho.platform.util.logging.SimpleLogger:
 * instructionPercentCoverageChange : +6.06%
 * linePercentCoverageChange : +8.33%
 * complexityPercentCoverageChange : +5.00%
 * methodPercentCoverageChange : +5.26%
    
org.pentaho.platform.engine.security.event.OrderedApplicationEventMulticaster.new Comparator() {...}:
 * instructionPercentCoverageChange : +6.25%
 * branchPercentCoverageChange : +12.50%
 * linePercentCoverageChange : +12.50%
 * complexityPercentCoverageChange : +16.67%
    
org.pentaho.platform.engine.services.runtime.TemplateUtil:
 * instructionPercentCoverageChange : +1.26%
 * branchPercentCoverageChange : +0.85%
 * linePercentCoverageChange : +1.97%
 * complexityPercentCoverageChange : +1.35%
 * methodPercentCoverageChange : +7.14%
    
org.pentaho.platform.uifoundation.chart.ChartHelper.Builder:
 * branchPercentCoverage :20.00%
 * linePercentCoverage :40.00%
 * methodPercentCoverage :57.14%
 * complexityPercentCoverage :19.35%
 * instructionPercentCoverage :31.88%

**Comment by lucboudreau** [comment]
Changed files:
==============
  core/ivy.xml
  core/src/org/pentaho/platform/uifoundation/chart/ChartHelper.java
  core/test-res/solution/test/xml/flash_dotchart.xml
  core/test-src/org/pentaho/platform/uifoundation/chart/ChartHelperTest.java

Checkstyle violations:
----------------------
Errors:File core/src/org/pentaho/platform/uifoundation/chart/ChartHelper.java
1. Message: 'static' modifier out of order with the JLS suggestions. at Line: 106 Column: 16
2. Message: 'static' modifier out of order with the JLS suggestions. at Line: 107 Column: 16
3. Message: 'static' modifier out of order with the JLS suggestions. at Line: 108 Column: 16
4. Message: 'static' modifier out of order with the JLS suggestions. at Line: 109 Column: 16
5. Message: 'static' modifier out of order with the JLS suggestions. at Line: 110 Column: 16
6. Message: 'static' modifier out of order with the JLS suggestions. at Line: 111 Column: 16
7. Message: 'static' modifier out of order with the JLS suggestions. at Line: 112 Column: 16
8. Message: 'static' modifier out of order with the JLS suggestions. at Line: 113 Column: 16
9. Message: 'static' modifier out of order with the JLS suggestions. at Line: 114 Column: 16
10. Message: 'static' modifier out of order with the JLS suggestions. at Line: 116 Column: 16
11. Message: 'static' modifier out of order with the JLS suggestions. at Line: 117 Column: 16
12. Message: 'static' modifier out of order with the JLS suggestions. at Line: 118 Column: 16
13. Message: 'static' modifier out of order with the JLS suggestions. at Line: 120 Column: 16
14. Message: 'static' modifier out of order with the JLS suggestions. at Line: 122 Column: 16
15. Message: Line has trailing spaces. at Line: 55 Column: None
16. Message: Line has trailing spaces. at Line: 56 Column: None
17. Message: Line has trailing spaces. at Line: 57 Column: None
18. Message: 'static' modifier out of order with the JLS suggestions. at Line: 66 Column: 21File core/test-src/org/pentaho/platform/uifoundation/chart/ChartHelperTest.java
1. Message: '}' is not followed by whitespace. at Line: 121 Column: 10
2. Message: 'static' modifier out of order with the JLS suggestions. at Line: 94 Column: 17
3. Message: 'static' modifier out of order with the JLS suggestions. at Line: 99 Column: 17

Newly Broken Tests:
-----------------
junit.framework.TestSuite$1.warning: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: No tests found in org.pentaho.platform.util.JSONComparitorTest

```





Unit test coverage change:
============
org.pentaho.platform.uifoundation.messages.Messages:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.platform.engine.services.ActionSequenceJCRHelper:
 * branchPercentCoverage :1.09%
 * linePercentCoverage :1.39%
 * methodPercentCoverage :8.33%
 * complexityPercentCoverage :1.72%
 * instructionPercentCoverage :1.36%
    
org.pentaho.platform.engine.core.system.objfac.AggregateObjectFactory.ReferencePriorityComparitor:
 * instructionPercentCoverageChange :**-4.44%**
 * branchPercentCoverageChange :**-10.00%**
 * linePercentCoverageChange :**-7.69%**
 * complexityPercentCoverageChange :**-12.50%**
    
org.pentaho.platform.uifoundation.chart.AbstractChartComponent:
 * linePercentCoverage :1.48%
 * methodPercentCoverage :2.78%
 * complexityPercentCoverage :1.92%
 * instructionPercentCoverage :1.13%
    
org.pentaho.platform.uifoundation.component.xml.XmlComponent:
 * linePercentCoverage :4.17%
 * methodPercentCoverage :33.33%
 * complexityPercentCoverage :14.29%
 * instructionPercentCoverage :4.49%
    
org.pentaho.platform.uifoundation.chart.ChartHelper.LogWriter:
 * branchPercentCoverage :75.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :87.50%
 * instructionPercentCoverage :97.78%
    
org.pentaho.platform.uifoundation.chart.ChartHelper.Error:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :50.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :84.48%
    
org.pentaho.platform.util.logging.SimpleLogger:
 * instructionPercentCoverageChange : +6.06%
 * linePercentCoverageChange : +8.33%
 * complexityPercentCoverageChange : +5.00%
 * methodPercentCoverageChange : +5.26%
    
org.pentaho.platform.engine.services.runtime.TemplateUtil:
 * instructionPercentCoverageChange : +1.26%
 * branchPercentCoverageChange : +0.85%
 * linePercentCoverageChange : +1.97%
 * complexityPercentCoverageChange : +1.35%
 * methodPercentCoverageChange : +7.14%
    
org.pentaho.platform.uifoundation.chart.ChartHelper.Builder:
 * branchPercentCoverage :20.00%
 * linePercentCoverage :40.00%
 * methodPercentCoverage :57.14%
 * complexityPercentCoverage :19.35%
 * instructionPercentCoverage :31.88%

**Comment by AliaksandrDrebenchuk** [comment]
@brosander Checkstyle was fixed

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  core/ivy.xml
  core/src/org/pentaho/platform/uifoundation/chart/ChartHelper.java
  core/test-res/solution/test/xml/flash_dotchart.xml
  core/test-src/org/pentaho/platform/uifoundation/chart/ChartHelperTest.java

Checkstyle violations:
======================
File core/test-src/org/pentaho/platform/uifoundation/chart/ChartHelperTest.java
1. Message: '}' is not followed by whitespace. at Line: 121 Column: 10


License header violations:
==========================
No violations found


Newly Broken Tests:
-----------------
junit.framework.TestSuite$1.warning: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: No tests found in org.pentaho.platform.util.JSONComparitorTest

```





Unit test coverage change:
============
org.pentaho.platform.uifoundation.messages.Messages:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.platform.engine.services.ActionSequenceJCRHelper:
 * branchPercentCoverage :1.09%
 * linePercentCoverage :1.39%
 * methodPercentCoverage :8.33%
 * complexityPercentCoverage :1.72%
 * instructionPercentCoverage :1.51%
    
org.pentaho.platform.engine.core.system.objfac.AggregateObjectFactory.ReferencePriorityComparitor:
 * instructionPercentCoverageChange : +4.44%
 * branchPercentCoverageChange : +10.00%
 * linePercentCoverageChange : +7.69%
 * complexityPercentCoverageChange : +12.50%
    
org.pentaho.platform.uifoundation.chart.AbstractChartComponent:
 * linePercentCoverage :1.48%
 * methodPercentCoverage :2.78%
 * complexityPercentCoverage :1.92%
 * instructionPercentCoverage :1.13%
    
org.pentaho.platform.uifoundation.component.xml.XmlComponent:
 * linePercentCoverage :4.17%
 * methodPercentCoverage :33.33%
 * complexityPercentCoverage :14.29%
 * instructionPercentCoverage :4.49%
    
org.pentaho.platform.uifoundation.chart.ChartHelper.LogWriter:
 * branchPercentCoverage :75.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :87.50%
 * instructionPercentCoverage :97.78%
    
org.pentaho.platform.uifoundation.chart.ChartHelper.Error:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :50.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :84.48%
    
org.pentaho.platform.util.logging.SimpleLogger:
 * instructionPercentCoverageChange : +6.06%
 * linePercentCoverageChange : +8.33%
 * complexityPercentCoverageChange : +5.00%
 * methodPercentCoverageChange : +5.26%
    
org.pentaho.platform.engine.security.event.OrderedApplicationEventMulticaster.new Comparator() {...}:
 * instructionPercentCoverageChange : +6.25%
 * branchPercentCoverageChange : +25.00%
 * linePercentCoverageChange : +12.50%
 * complexityPercentCoverageChange : +33.33%
    
org.pentaho.platform.engine.services.runtime.TemplateUtil:
 * instructionPercentCoverageChange : +1.26%
 * branchPercentCoverageChange : +0.85%
 * linePercentCoverageChange : +1.97%
 * complexityPercentCoverageChange : +1.35%
 * methodPercentCoverageChange : +7.14%
    
org.pentaho.platform.uifoundation.chart.ChartHelper.Builder:
 * branchPercentCoverage :20.00%
 * linePercentCoverage :40.00%
 * methodPercentCoverage :57.14%
 * complexityPercentCoverage :19.35%
 * instructionPercentCoverage :31.88%

**Comment by brosander** [comment]
@AliaksandrDrebenchuk still seeing checkstyle erros, also is the test failure coming from the new jmockit dependency?

**Comment by AliaksandrDrebenchuk** [comment]
"testJSONComparator" method of JSONComparitorTest class must be non-static

**Comment by brosander** [comment]
@AliaksandrDrebenchuk I agree that is probably why, not sure why it's flagged as newly broken though, that means it didn't fail when master built...

**Comment by AliaksandrDrebenchuk** [comment]
@brosander. Branch was updated. But I not sure the checkstyle error is fixed because Eclipse don't show any checkstyle erros by https://github.com/pentaho/pentaho-coding-standards/blob/master/pentaho_checkStyle.xml

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  core/ivy.xml
  core/src/org/pentaho/platform/uifoundation/chart/ChartHelper.java
  core/test-res/solution/test/xml/flash_dotchart.xml
  core/test-src/org/pentaho/platform/uifoundation/chart/ChartHelperTest.java

Checkstyle violations:
======================
No errors found

License header violations:
==========================
No violations found


Newly Broken Tests:
-----------------
junit.framework.TestSuite$1.warning: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: No tests found in org.pentaho.platform.util.JSONComparitorTest

```





Unit test coverage change:
============
org.pentaho.platform.uifoundation.messages.Messages:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.platform.engine.services.ActionSequenceJCRHelper:
 * branchPercentCoverage :1.09%
 * linePercentCoverage :1.39%
 * methodPercentCoverage :8.33%
 * complexityPercentCoverage :1.72%
 * instructionPercentCoverage :1.51%
    
org.pentaho.platform.uifoundation.chart.AbstractChartComponent:
 * linePercentCoverage :1.48%
 * methodPercentCoverage :2.78%
 * complexityPercentCoverage :1.92%
 * instructionPercentCoverage :1.13%
    
org.pentaho.platform.uifoundation.component.xml.XmlComponent:
 * linePercentCoverage :4.17%
 * methodPercentCoverage :33.33%
 * complexityPercentCoverage :14.29%
 * instructionPercentCoverage :4.49%
    
org.pentaho.platform.uifoundation.chart.ChartHelper.LogWriter:
 * branchPercentCoverage :75.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :87.50%
 * instructionPercentCoverage :97.78%
    
org.pentaho.platform.uifoundation.chart.ChartHelper.Error:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :50.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :84.48%
    
org.pentaho.platform.util.logging.SimpleLogger:
 * instructionPercentCoverageChange : +6.06%
 * linePercentCoverageChange : +8.33%
 * complexityPercentCoverageChange : +5.00%
 * methodPercentCoverageChange : +5.26%
    
org.pentaho.platform.engine.security.event.OrderedApplicationEventMulticaster.new Comparator() {...}:
 * branchPercentCoverageChange : +12.50%
 * complexityPercentCoverageChange : +16.67%
    
org.pentaho.platform.engine.services.runtime.TemplateUtil:
 * instructionPercentCoverageChange : +1.26%
 * branchPercentCoverageChange : +0.85%
 * linePercentCoverageChange : +1.97%
 * complexityPercentCoverageChange : +1.35%
 * methodPercentCoverageChange : +7.14%
    
org.pentaho.platform.uifoundation.chart.ChartHelper.Builder:
 * branchPercentCoverage :20.00%
 * linePercentCoverage :40.00%
 * methodPercentCoverage :57.14%
 * complexityPercentCoverage :19.35%
 * instructionPercentCoverage :31.88%

**Comment by brosander** [comment]
@AliaksandrDrebenchuk master is building with no unit test failures, something changed to cause the JSONComparitorTest to start erroring.  Please try removing the static from the test method signature and see if you still have unit test errors locally.

**Comment by AliaksandrDrebenchuk** [comment]
I tried remove the static from the test method signature and ran JSONComparitorTest without any exceptions YESTERDAY, before my comment about the exception. Why we are still discussing the exception that doesn't concern my changes?

**Comment by brosander** [comment]
@AliaksandrDrebenchuk I'm aware that this isn't a file you touched.  However something (I suspect the new dependency) in your pull request is causing that test to fail.  I just verified manually to be sure it wasn't a problem with the automated build.  As such, this does concern your changes.

Repro:
```
git checkout master && git pull upstream master
ant -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco jacoco-integration checkstyle
```
Verify that in core/bin/reports/test/html/index.html that there are no unit test failures
```
git checkout -b AliaksandrDrebenchuk-ChartHelperTesting master
git pull https://github.com/AliaksandrDrebenchuk/pentaho-platform.git ChartHelperTesting
ant -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco jacoco-integration checkstyle
```
Notice that there is now 1 unit test falure in core/bin/reports/test/html/index.html

**Comment by bkemper-pentaho** [comment]
Can I ask why the MAJOR refactor to ChartHelper?    This is a huge amount of changes for a case labeled "[TEST]" .   Is there a Jira on this?   Was there a rationale for making this level of change to an existing module which required this work to be done?

If nothing else  - the test cases need to be validated against the code PRIOR to a refactor of this magnitude - so we can be sure there aren't any regressions....




Bob Kemper
Executive Vice President of Engineering
Pentaho, a Hitachi Data Systems company.
5950 Hazeltine National Dr.
Suite 340
Orlando, FL 32822
(407)-965-4019

[cid:426DECD2-5937-4B05-B438-69ACAE1D4CB6]

**Comment by AliaksandrDrebenchuk** [comment]
@bkemper-pentaho  Before refactoring the "ChartHelper" class was too complicated for testing because it contains all logic in one large method with duplicates. So, have you any suggestions what do next?

**Comment by AliaksandrDrebenchuk** [comment]
@bkemper-pentaho. By the way, i didn't found where this class is used. I tried use different charts in browser, but the class wasn't executed. Maybe it class is deprecated.

**Comment by brosander** [comment]
@AliaksandrDrebenchuk it's used in [HttpWebService] (https://github.com/pentaho/pentaho-platform/blob/3b7147ece8aa28dfc3a645d0f13601fedeb53a46/extensions/src/org/pentaho/platform/web/servlet/HttpWebService.java)

FYI, getting all coding standards (checkstyle, unit tests, coverage, etc) addressed is step 0 in the review process.  I was planning on asking @rmansoor to do the actual code review once the tests are all passing as I'm not that familiar with this portion of the code base.

/cc @bkemper-pentaho

**Comment by AliaksandrDrebenchuk** [comment]
@brosander.
[10/19/2015 17:35:21] Aliaksandr_Drebenchuk:     <servlet-name>ServiceAction</servlet-name>
    <servlet-class>org.pentaho.platform.web.servlet.HttpWebService</servlet-class>
[10/19/2015 17:36:20] Aliaksandr_Drebenchuk: I didn't found another java classes wich use the ChartHelper but HttpWebService
[10/19/2015 17:37:33] Ramaiz Mansoor: This is one of our old classes. May be cdf is using them through serviceaction
.........
[10/20/2015 17:04:47] Ramaiz Mansoor: I did not find any xaction or xcdf resources that uses ChartHelper.
[10/20/2015 17:05:00] Ramaiz Mansoor: seems like it has been deprecard but I want to look some more

**Comment by AliaksandrDrebenchuk** [comment]
@brosander. I tested your ant examples many times and found out that static test methods can be ignored without errors after jmockit dependecy adding. So, I will investigate this issue even more. Thanks for your attentiveness.

**Comment by rmansoor** [comment]
Closing this pull request. We will be deprecating the use of chart helper in the platform http://jira.pentaho.com/browse/BISERVER-12899.

**Pull request closed without merging**
