### PR TITLE
[PDI - 18988]: Fixed Username and Password exposed in cleartext on Server logs when adding or importing Hadoop Cluster

### PR DESCRIPTION
**Pull request by VootkoorSamhitha**
[PDI - 18988]: Fixed Username and Password exposed in cleartext on Server logs when adding or importing Hadoop Cluster

### CODE REVIEW

**Review by peterrinehart — APPROVED** [review]

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 36m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 35m 51s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 34m 18s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 34m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 34m 36s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Pull request closed without merging**
