### PR TITLE
[BACKLOG-5384] [TEST] - Increasing code coverage for pentaho-platform-extensions

### PR DESCRIPTION
**Pull request by rfellows**
[BACKLOG-5384] [TEST] - Increasing code coverage for pentaho-platform-extensions

This contains unit tests for the packages:
  * org.pentaho.platform.admin
  * org.pentaho.platform.config.*

Also adding BeanTester to the core. anyone who resolves in pentaho-platform-core-test will be able to use it to unit test bean classes

### CODE REVIEW

**Comment by rfellows** [comment]
@dkincade please review.

**Comment by rfellows** [comment]
@lucboudreau please review.

I'm still working on more tests in extensions but it's slow going. there are 128,000+ lines of code. I'm averaging about +1% coverage per day. The 80% coverage has to be a long term goal. No way we will get there in the near-term.

**Comment by lucboudreau** [comment]
I can't build your branch. Getting compile errors. Can you double check on your side? Thanks.

```
compile-tests:
    [javac] /Users/lboudreau/git/pentaho-platform/extensions/build-res/subfloor.xml:1775: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 256 source files to /Users/lboudreau/git/pentaho-platform/extensions/bin/test/classes
    [javac] warning: Supported source version 'RELEASE_6' from annotation processor 'org.tuckey.web.filters.urlrewrite.annotation.UrlRewriteAnnotationProcessor' less than -source '1.7'
    [javac] /Users/lboudreau/git/pentaho-platform/extensions/test-src/org/pentaho/platform/config/AclEntryTest.java:4: error: cannot find symbol
    [javac] import org.pentaho.test.BeanTester;
    [javac]                        ^
    [javac]   symbol:   class BeanTester
    [javac]   location: package org.pentaho.test
    [javac] /Users/lboudreau/git/pentaho-platform/extensions/test-src/org/pentaho/platform/config/AclEntryTest.java:13: error: cannot find symbol
    [javac] public class AclEntryTest extends BeanTester {
    [javac]                                   ^
    [javac]   symbol: class BeanTester
    [javac] /Users/lboudreau/git/pentaho-platform/extensions/test-src/org/pentaho/platform/web/http/api/resources/proxies/BlockStatusProxyTest.java:3: error: cannot find symbol
    [javac] import org.pentaho.test.BeanTester;
    [javac]                        ^
    [javac]   symbol:   class BeanTester
    [javac]   location: package org.pentaho.test
    [javac] /Users/lboudreau/git/pentaho-platform/extensions/test-src/org/pentaho/platform/web/http/api/resources/proxies/BlockStatusProxyTest.java:5: error: cannot find symbol
    [javac] public class BlockStatusProxyTest extends BeanTester {
    [javac]                                           ^
    [javac]   symbol: class BeanTester
    [javac] /Users/lboudreau/git/pentaho-platform/extensions/test-src/org/pentaho/platform/config/AclEntryTest.java:4: error: cannot find symbol
    [javac] import org.pentaho.test.BeanTester;
    [javac]                        ^
    [javac]   symbol:   class BeanTester
    [javac]   location: package org.pentaho.test
    [javac] /Users/lboudreau/git/pentaho-platform/extensions/test-src/org/pentaho/platform/config/AclEntryTest.java:13: error: cannot find symbol
    [javac] public class AclEntryTest extends BeanTester {
    [javac]                                   ^
    [javac]   symbol: class BeanTester
    [javac] /Users/lboudreau/git/pentaho-platform/extensions/test-src/org/pentaho/platform/web/http/api/resources/proxies/BlockStatusProxyTest.java:3: error: cannot find symbol
    [javac] import org.pentaho.test.BeanTester;
    [javac]                        ^
    [javac]   symbol:   class BeanTester
    [javac]   location: package org.pentaho.test
    [javac] /Users/lboudreau/git/pentaho-platform/extensions/test-src/org/pentaho/platform/web/http/api/resources/proxies/BlockStatusProxyTest.java:5: error: cannot find symbol
    [javac] public class BlockStatusProxyTest extends BeanTester {
    [javac]                                           ^
    [javac]   symbol: class BeanTester
    [javac] /Users/lboudreau/git/pentaho-platform/extensions/test-src/org/pentaho/platform/config/AclEntryTest.java:18: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] /Users/lboudreau/git/pentaho-platform/extensions/test-src/org/pentaho/platform/config/AclEntryTest.java:24: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 6 errors
    [javac] 1 warning
```

**Comment by dkincade** [comment]
@lucboudreau did you do a publish local? The new BeanTester class will only be included in the test library once it is published. I am running through this currently....

**Comment by dkincade** [comment]
Looks great to me!!!!!

**Pull request merged**
