### PR TITLE
[PPP-3755] "Inherits folder permissions" after giving suzy access to her folder the authenticated role appears. Remove this role, login as pat or tiffany there's infinite reload, errors in pentaho server logs and need to restart the server

### PR DESCRIPTION
**Pull request by Advent51**
- Exception wasn't handled properly (it was thrown too far)

### CODE REVIEW

**Comment by Advent51** [comment]
@pamval @mbatchelor @mdamour1976 please review

**Comment by Advent51** [comment]
@pamval @mbatchelor @mdamour1976 @mchen-len-son please review

**Comment by Advent51** [comment]
@pamval @mbatchelor @mdamour1976 @duarteteixeira please review

**Comment by mbatchelor** [comment]
Re-running Wingman as this was from Feb 7 (a month ago!)

**Comment by Advent51** [comment]
@mbatchelor please review

**Pull request merged**
