### PR TITLE
[SP-6512] - Backport of PPP-5053 - Intercepting few Get request with Burp Suite allows un-authorised user to access data (9.3 Suite)

### PR DESCRIPTION
**Pull request by renato-s**
Original PR:
 - https://github.com/pentaho/pentaho-scheduler-plugin/pull/138/
 - https://github.com/pentaho/pentaho-platform/pull/5559

### CODE REVIEW

**Review by andreramos89 — APPROVED** [review]
Changed git repo and location, but seem consistent

**Comment by buildguy** [comment]
### :x: Build failed in 46m 25s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
core,extensions,user-console
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 5 test(s) failed:

<details><summary><b>org.pentaho.platform.util.versionchecker.PentahoVersionCheckReflectHelperTest.performVersionCheckTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportSchedules_FailsToCreateScheduleWithSpaceOnWindows</b> (click to expand)</summary><p>

```
org.pentaho.commons.util.repository.exception.PermissionDeniedException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportSchedules_FailsToCreateScheduleWithSpace</b> (click to expand)</summary><p>

```
org.pentaho.commons.util.repository.exception.PermissionDeniedException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportSchedules_FailsToCreateSchedule</b> (click to expand)</summary><p>

```
org.pentaho.commons.util.repository.exception.PermissionDeniedException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportSchedules</b> (click to expand)</summary><p>

```
org.pentaho.commons.util.repository.exception.PermissionDeniedException
```

</p></details>

  
Tests run: **1607**, Failures: **5**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5574/1/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code -2
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 35m 20s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
core,extensions,user-console
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 16 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportGlobalUserSetting</b> (click to expand)</summary><p>

```

Wanted but not invoked:
iUserSettingService.setGlobalUserSetting(
    "language",
    "en_US"
);
-> at org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportGlobalUserSetting(SolutionImportHandlerTest.java:455)
Actually, there were zero interactions with this mock.

```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportUsers_userAlreadyExists_overwriteFalse</b> (click to expand)</summary><p>

```
expected:<1> but was:<0>
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportUsers_oneUserManyRoles</b> (click to expand)</summary><p>

```
expected:<3> but was:<0>
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportUserSettings_NoOverwrite</b> (click to expand)</summary><p>

```

Wanted but not invoked:
iAnyUserSettingService.setUserSetting(
    "pentaho",
    "language",
    "en_US"
);
-> at org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportUserSettings_NoOverwrite(SolutionImportHandlerTest.java:439)
Actually, there were zero interactions with this mock.

```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportUserSettings</b> (click to expand)</summary><p>

```

Wanted but not invoked:
iAnyUserSettingService.setUserSetting(
    "pentaho",
    "theme",
    "crystal"
);
-> at org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportUserSettings(SolutionImportHandlerTest.java:419)
Actually, there were zero interactions with this mock.

```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportUsers_manyUserManyRoles</b> (click to expand)</summary><p>

```
expected:<4> but was:<0>
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportGlobalUserSetting_noOverwrite</b> (click to expand)</summary><p>

```

Wanted but not invoked:
iUserSettingService.setGlobalUserSetting(
    "language",
    "en_US"
);
-> at org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportGlobalUserSetting_noOverwrite(SolutionImportHandlerTest.java:475)
Actually, there were zero interactions with this mock.

```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportUsers_userAlreadyExists</b> (click to expand)</summary><p>

```
expected:<1> but was:<0>
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportRoles</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportRoles_roleAlreadyExists_overwriteFalse</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportRoles_roleAlreadyExists</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.platform.util.versionchecker.PentahoVersionCheckReflectHelperTest.performVersionCheckTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportSchedules_FailsToCreateScheduleWithSpaceOnWindows</b> (click to expand)</summary><p>

```

For org.pentaho.platform.engine.core.system.PentahoSystem, static mocking is already registered in the current thread

To create a new mock, the existing static mock registration must be deregistered
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportSchedules_FailsToCreateScheduleWithSpace</b> (click to expand)</summary><p>

```

For org.pentaho.platform.engine.core.system.PentahoSystem, static mocking is already registered in the current thread

To create a new mock, the existing static mock registration must be deregistered
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportSchedules_FailsToCreateSchedule</b> (click to expand)</summary><p>

```

For org.pentaho.platform.engine.core.system.PentahoSystem, static mocking is already registered in the current thread

To create a new mock, the existing static mock registration must be deregistered
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.testImportSchedules</b> (click to expand)</summary><p>

```

For org.pentaho.platform.engine.core.system.PentahoSystem, static mocking is already registered in the current thread

To create a new mock, the existing static mock registration must be deregistered
```

</p></details>

  
Tests run: **2175**, Failures: **16**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5574/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by smmribeiro** [comment]
Failing unit test is unrelated to these changes and is one that fails periodically.

**Pull request merged**
