### PR TITLE
[BACKLOG-32587] - Include .df mime type to the import handler mime ty…

### PR DESCRIPTION
**Pull request by marcoslarsen**
…pe definitions.

### CODE REVIEW

**Comment by marcoslarsen** [comment]
@pentaho/kashyyyk Please review.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 13s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/pentaho-solutions
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 36s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/pentaho-solutions
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 22s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/pentaho-solutions
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Pull request closed without merging**
