### PR TITLE
[BISERVER-14971] - Schedule runs twice if using 'Run Now' after the time that a daily (every weekday) schedule is due to run

### PR DESCRIPTION
**Pull request by andreramos89**
Added condition for not picking up the manual scheduled job execution twice

----------

@smmribeiro 
@bcostahitachivantara 
@renato-s

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1h 39m 39s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl scheduler
```
---
:ok_hand: All tests passed!
 
Tests run: **1745**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5391/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by bcostahitachivantara — APPROVED** [review]
Clever solution :)

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1h 30m 58s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl scheduler
```
---
:ok_hand: All tests passed!
 
Tests run: **1745**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5391/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1h 35m 55s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl scheduler
```
---
:ok_hand: All tests passed!
 
Tests run: **1745**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5391/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1h 35m 56s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl scheduler
```
---
:ok_hand: All tests passed!
 
Tests run: **1745**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5391/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1h 32m 30s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl scheduler
```
---
:ok_hand: All tests passed!
 
Tests run: **1745**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5391/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Looks good.

**Pull request merged**
