### PR TITLE
[BISERVER-13065] Scheduled task with deleted/renamed source report

### PR DESCRIPTION
**Pull request by davidmsantos90**
@pentaho/millenniumfalcon please review

Merge After:
 - https://github.com/pentaho/pentaho-commons-gwt-modules/pull/761

Changed the execute now button, to check if it can execute the selected jobs, before the actual execution. In case it can not execute, a prompt will appear asking if the user want to remove those schedules.

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 1m 14s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 17s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 7m 16s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4636/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 7m 10s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4636/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by dcleao** [comment]
Still smells somewhat ;-)

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 8m 1s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4636/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
