### PR TITLE
[BACKLOG-7786] Report execution cancelled when dashboard with unsaved…

### PR DESCRIPTION
**Pull request by Aliaksandr-Kastenka**
… changes is closed

### CODE REVIEW

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f user-console/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f user-console/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  user-console/source/org/pentaho/mantle/client/ui/tabs/MantleTabPanel.java

License header violations:
==========================
1. Copyright year is not the current year on user-console/source/org/pentaho/mantle/client/ui/tabs/MantleTabPanel.java. Found 2013. Was expecting 2016

**Comment by Aliaksandr-Kastenka** [comment]
@tmorgner 
Please take a look.

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f user-console/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f user-console/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  user-console/source/org/pentaho/mantle/client/ui/tabs/MantleTabPanel.java

**Comment by tmorgner** [comment]
Wingman says we are happy. And the code is looking good too. So merge is on its way ..

**Pull request merged**
