### PR TITLE
[PPP-4745] - Security Scan vulnerability - Insecure Object Rendering in PUC

### PR DESCRIPTION
**Pull request by andreramos89**
@smmribeiro 
@renato-s 
@bcostahitachivantara

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 27m 42s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/pentaho-solutions,extensions,user-console
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 29m 1s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/pentaho-solutions,extensions,user-console
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 29m 15s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/pentaho-solutions,extensions,user-console
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Looks good.

**Pull request merged**
