### PR TITLE
[SP-5800] - Backport of BISERVER-14534 - Running jobs or transformations via Schedules created on PUC stop running after multiple executions (8.3 Suite)

### PR DESCRIPTION
**Pull request by bcostahitachivantara**
@pentaho-lmartins 
@ssamora 
@smmribeiro

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 38m 33s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,core,repository,scheduler
```
---
:ok_hand: All tests passed!
 
Tests run: **2550**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4775/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 17m 56s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,core,repository,scheduler
```
---
:ok_hand: All tests passed!
 
Tests run: **1035**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4775/2/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 17m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,core,repository,scheduler
```
---
:ok_hand: All tests passed!
 
Tests run: **1035**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4775/3/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 17m 20s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,core,repository,scheduler
```
---
:ok_hand: All tests passed!
 
Tests run: **1035**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4775/4/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 37m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,core,repository,scheduler
```
---
:ok_hand: All tests passed!
 
Tests run: **2550**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4775/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by pentaho-lmartins — APPROVED** [review]

**Pull request merged**
