### PR TITLE
[BISERVER-13832]-Server is no longer displaying the appropriate error page for URLs starting with /pentaho/api

### PR DESCRIPTION
**Pull request by stepanovdg**

### CODE REVIEW

**Comment by stepanovdg** [comment]
@mbatchelor Could you please take a look?

**Comment by lucboudreau** [comment]
Can we add tests to this PR please? Thanks.

**Comment by stepanovdg** [comment]
@lucboudreau @mbatchelor Test attached

**Comment by stepanovdg** [comment]
Test failures are the same on master.

**Comment by lucboudreau** [comment]
Please re-read my comment above. 

 - We need to handle Spring authentication exceptions - your code does not.

 - The tests are testing only positive outcomes. None of the tests run your error handling logic so none of it is covered.

 - Please see if the other failures can be fixed, or reference a pull request that fixes them.

**Pull request merged**
