### PR TITLE
[BISERVER-13379] Xaction Output Destination File throws error on PUC …

### PR DESCRIPTION
**Pull request by ivanpogodin**
…it fails on / (slash) Separator but writes files folder
No tests yet

### CODE REVIEW

**Comment by ivanpogodin** [comment]
@pamval , @mbatchelor  , could you review it, please?

**Comment by pamval** [comment]
@rmansoor @rfellows @e-cuellar please review

**Comment by ivanpogodin** [comment]
@rmansoor , @rfellows , @e-cuellar , could you review it, please?

**Comment by rmansoor** [comment]
@ivanpogodin reviewed and validated the PR locally. It is working well. Processing the PR now

**Pull request merged**
