### PR TITLE
[BISERVER-12863] Database Connection Options - Order is not being kep…

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**
[BISERVER-12863] Database Connection Options - Order is not being kept after saving connection - preserver insertion order, fix checkstyles

### CODE REVIEW

**Comment by stanislau-strelchanka** [comment]
@mdamour1976, @rmansoor, @e-cuellar, @mdamour1976, @pentaho-nbaker, @mchen-len-son please review

**Comment by stanislau-strelchanka** [comment]
@mdamour1976, @rmansoor, @e-cuellar, @mdamour1976, @pentaho-nbaker, @mchen-len-son, @pamval please review

**Comment by mchen-len-son** [comment]
@stanislau-strelchanka please add a unit test for the changes.
Also, there are checkstyle violations in DatabaseHelper.java

**Comment by stanislau-strelchanka** [comment]
@mchen-len-son updated

**Pull request merged**
