### PR TITLE
[PPP-3828] - Not able to delete the blank files that are generated wh…

### PR DESCRIPTION
**Pull request by YuryBY**
…ile scheduling the transformation.

 - additional changes, remove only empty files

### CODE REVIEW

**Comment by YuryBY** [comment]
@pamval, @mbatchelor, could you please take a look?

**Comment by YuryBY** [comment]
@pamval, @mbatchelor, any updates?

**Comment by mchen-len-son** [comment]
@pamval @mbatchelor can you please take a look?
thanks.

**Comment by Aliaksandr-Kastenka** [comment]
@kurtwalker @DFieldFL
Please review.

**Pull request merged**
