### PR TITLE
[BISERVER-11649] Mondrian role mappers don't pass the role name of a user when his username and group are both 'Admin'

### PR DESCRIPTION
**Pull request by IvanNikolaychuk**
- Updating roles in current session, after any role is deleted
- Test witten

@akhayrutdinov, that's another PR, related to https://github.com/pentaho/pentaho-platform/pull/2788. It solves a problem of updating user-session after deleting any roles. Review it please.

@pedrovfteixeira, @pamval, could you please start WM?

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@pedrofvteixeira

**Comment by lucboudreau** [comment]
Good catch. Wingman in progress.

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
  extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
  extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource_RolesUpdatedTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
1. Message: Using a static member import should be avoided - org.junit.Assert.assertEquals. at Line: 20 Column: None
2. Message: Using a static member import should be avoided - org.junit.Assert.assertNotNull. at Line: 21 Column: None
3. Message: Using a static member import should be avoided - org.mockito.Matchers.any. at Line: 22 Column: None
4. Message: Using a static member import should be avoided - org.mockito.Matchers.anyString. at Line: 23 Column: None
5. Message: Using a static member import should be avoided - org.mockito.Mockito.*. at Line: 24 Column: None

File extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource_RolesUpdatedTest.java
1. Message: Using a static member import should be avoided - junit.framework.Assert.assertTrue. at Line: 40 Column: None
2. Message: Using a static member import should be avoided - org.mockito.Mockito.*. at Line: 41 Column: None









Unit test coverage change:
============
org.pentaho.platform.web.http.api.resources.UserRoleDaoResource:
 * instructionPercentCoverageChange : +0.08%
 * linePercentCoverageChange : +0.16%
    
org.pentaho.platform.admin.GeneratedContentCleaner:
 * branchPercentCoverageChange :**-10.00%**
 * complexityPercentCoverageChange :**-9.09%**
    
Integration test coverage change:
============
org.pentaho.platform.plugin.action.chartbeans.ChartAction:
 * instructionPercentCoverageChange : +0.45%
    
org.pentaho.platform.plugin.services.pluginmgr.PentahoSystemPluginManager:
 * instructionPercentCoverageChange : +0.04%
 * branchPercentCoverageChange : +0.45%
 * linePercentCoverageChange : +0.21%
 * complexityPercentCoverageChange : +0.65%

**Comment by lucboudreau** [comment]
There is a 10% drop of coverage in GeneratedContentCleaner. Please check if this can be addressed.

Thanks!

**Comment by IvanNikolaychuk** [comment]
@lucboudreau, thanks!
I added a new commit with updated tests, that increase coverage

**Comment by akhayrutdinov** [comment]
@pamval, @pedrofvteixeira, run WM over this PR please

**Comment by pamval** [comment]
running wingman

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
  extensions/test-src/org/pentaho/platform/admin/GeneratedContentCleanerTest.java
  extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
  extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource_RolesUpdatedTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File extensions/test-src/org/pentaho/platform/admin/GeneratedContentCleanerTest.java
1. Message: Using a static member import should be avoided - org.junit.Assert.*. at Line: 38 Column: None
2. Message: Using a static member import should be avoided - org.mockito.Matchers.*. at Line: 39 Column: None
3. Message: Using a static member import should be avoided - org.mockito.Mockito.*. at Line: 40 Column: None

File extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
1. Message: Using a static member import should be avoided - org.junit.Assert.assertEquals. at Line: 20 Column: None
2. Message: Using a static member import should be avoided - org.junit.Assert.assertNotNull. at Line: 21 Column: None
3. Message: Using a static member import should be avoided - org.mockito.Matchers.any. at Line: 22 Column: None
4. Message: Using a static member import should be avoided - org.mockito.Matchers.anyString. at Line: 23 Column: None
5. Message: Using a static member import should be avoided - org.mockito.Mockito.*. at Line: 24 Column: None

File extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource_RolesUpdatedTest.java
1. Message: Using a static member import should be avoided - junit.framework.Assert.assertTrue. at Line: 40 Column: None
2. Message: Using a static member import should be avoided - org.mockito.Mockito.*. at Line: 41 Column: None









Unit test coverage change:
============
org.pentaho.platform.web.http.api.resources.UserRoleDaoResource:
 * instructionPercentCoverageChange : +0.08%
 * linePercentCoverageChange : +0.16%
    
org.pentaho.platform.admin.GeneratedContentCleaner:
 * instructionPercentCoverageChange : +13.33%
 * branchPercentCoverageChange : +40.00%
 * linePercentCoverageChange : +10.71%
 * complexityPercentCoverageChange : +27.27%

**Comment by akhayrutdinov** [comment]
@kolinus, @aliakseihaidukou, review it please

**Comment by aliakseihaidukou** [comment]
don't we squash commits in pull request? Especially if they have equal comments

**Comment by IvanNikolaychuk** [comment]
@aliakseihaidukou, I'd prefer to change the commit commend, because this commit it is absolutly not related to the fix itself. 
Thanks.

**Comment by lucboudreau** [comment]
Thanks Ivan, Well done. One comment; make sure to use one of the 'official' commit tags. 'COVERAGE' is not one of them. You can use 'TEST' for cases like these.

**Comment by IvanNikolaychuk** [comment]
@lucboudreau, ok, got it, thanks!

**Pull request merged**
