### PR TITLE
[SP-2773] Backport of BISERVER-13112 - Favourites and recents not bei…

### PR DESCRIPTION
**Pull request by ivanpogodin**
…ng listed since SP SP201602-6.0.1.2 applied (6.1 Suite)

pick [BISERVER-13112] Favourites and recents not being listed since SP SP201602-6.0.1.2 applied

### CODE REVIEW

**Comment by pamval** [comment]
@ivanpogodin please address the code style issue in UserSettingsResource

**Comment by ivanpogodin** [comment]
@pamval , @rfellows , @pedrofvteixeira , could you review it, please.
This is a simple cherry-pick, The files are identical to the root case ( BISERVER-12717, https://github.com/pentaho/data-access/pull/763 )
Check style warning on static imports is resolved in src (not in test-src, there are junit and mockito imports only)

**Comment by pamval** [comment]
there's a drop in coverage on the UserSettingsResource. Was this the case in master as well?

**Comment by ivanpogodin** [comment]
@pamval , there wasn't drop in coverage on the UserSettingsResource in master

**Pull request merged**
