### PR TITLE
[BACKLOG-37004] Change FileDialog to not duplicate GlassPane management with FileChooserDialog

### PR DESCRIPTION
**Pull request by dcleao**
@pentaho/wcag please review.

Part of PR group: https://github.com/pentaho/pentaho-commons-gwt-modules/pull/839.

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 11m 18s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5215/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by rmansoor — APPROVED** [review]

**Review by soagarwal1 — CHANGES_REQUESTED** [review]
Need to update Copyright year

**Review by soagarwal1 — APPROVED** [review]

**Review by singletonc — APPROVED** [review]

**Comment by dcleao** [comment]
Rebased and fixed copyright year.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 10m 43s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5215/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 10m 7s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5215/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 10m 17s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5215/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
