### PR TITLE
BISERVER-11632 - Schedule executed while the scheduler is paused crea…

### PR DESCRIPTION
**Pull request by Aliaksandr-Kastenka**
…tes an extra schedule line that can't be deleted

### CODE REVIEW

**Comment by Aliaksandr-Kastenka** [comment]
@rfellows @rmansoor 
Please review. I wrote email about this one.

**Comment by rmansoor** [comment]
@Aliaksandr-Kastenka I am reviewing it. It does look ok, I will need to test some additional scenarios and will merge it in tomorrow

**Comment by dkincade** [comment]
I would like to see a unit (or integration) test illustrating this issue (meaning it should fail without the fix). Once the fix is applied, then the test would start passing.

**Comment by Aliaksandr-Kastenka** [comment]
@dkincade @rmansoor 
Pull-request updated.

**Comment by pamval** [comment]
@rmansoor please review and merge (if acceptable). This is part of the October SP and we're trying to wrap it today/tomorrow.

**Pull request merged**
