### PR TITLE
[PDI-13961] Spoon firstly tries to conect via JNDI although connection type is JDBC

### PR DESCRIPTION
**Pull request by akhayrutdinov**
- introduce two interfaces for sharing different data source providers
- update PlatformKettleDataSourceProvider to implement new method in DataSourceProviderInterface

@pentaho-nbaker, @rmansoor, please review it.
This PR comes together with https://github.com/pentaho/pentaho-kettle/pull/1655 and **should not be merged before it**
/cc @pamval

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@pentaho-nbaker, @rmansoor, please let me know before merging the PR. Its partner https://github.com/pentaho/pentaho-kettle/issues/1660 was merged by @deinspanjer, but then he was forced to revert the changes not to break the build

**Comment by rmansoor** [comment]
@akhayrutdinov the code looks ok. I did notice that none of the unit tests were change. Were they all working with this change. I do have to download this locally and run some test before I process this pull request.

**Comment by deinspanjer** [comment]
https://github.com/pentaho/pentaho-kettle/pull/1655 is reviewed and ready for merge.  Please merge it at the same time as this one when ready.

**Comment by akhayrutdinov** [comment]
Here is my new PR instead of already merged and reverted: https://github.com/pentaho/pentaho-kettle/pull/1674

**Pull request merged**
