### PR TITLE
[BACKLOG-4822] - Refactored a list to a set.

### PR DESCRIPTION
**Pull request by brendan-lynch**
Refactored the getAllRoles to use a set instead of a list for merging two collections together into one.

### CODE REVIEW

**Comment by dkincade** [comment]
@dkincade or @pamval should be the only people to merge this into 6.0.0.0 after review ...

**Comment by rfellows** [comment]
Looks good to me

**Comment by brendan-lynch** [comment]
@dkincade Also updating the API documentation, let me know if this is ok or if you want separate PRs

**Comment by dkincade** [comment]
One PR works for this.

**Pull request merged**
