### PR TITLE
[SP-6362] - Backport of PPP-4787 - Security Vulnerability: JNDI Injection in /pentaho/ServiceAction (9.5 Suite)

### PR DESCRIPTION
**Pull request by renato-s**
@andreramos89 
@smmribeiro 

Original PRs:
 - https://github.com/pentaho/pentaho-platform/pull/5336
 - https://github.com/pentaho/pentaho-platform/pull/5337

### CODE REVIEW

**Review by andreramos89 — APPROVED** [review]

**Comment by buildguy** [comment]
### :x: Build failed in 19m 35s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **3**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5352/1/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 1h 10m 17s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.platform.util.versionchecker.PentahoVersionCheckReflectHelperTest.performVersionCheckTest</b> (click to expand)</summary><p>

```
unexpected exception
```

</p></details>

  
Tests run: **2760**, Failures: **1**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5352/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Consistent with the original PRs.

**Comment by smmribeiro** [comment]
Wingman's test failure seems to be one of the "random" ones.

**Pull request merged**
