### PR TITLE
[SP-6584]-Backport of PPP-5004 - Tomcat Configuration vulnerable to Server-Side Request Forgery (9.3 Suite)

### PR DESCRIPTION
**Pull request by SahithiKommagani6**
[SP-6584]-Backport of PPP-5004 - Tomcat Configuration vulnerable to Server-Side Request Forgery (9.3 Suite)

[SP-6584]: https://hv-eng.atlassian.net/browse/SP-6584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 4m 54s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
assemblies/pentaho-solutions,extensions
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 4m 9s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
assemblies/pentaho-solutions,extensions
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Consistent with the original PRs ([pentaho-platform#5589](https://github.com/pentaho/pentaho-platform/pull/5589) and [pentaho-platform#5620](https://github.com/pentaho/pentaho-platform/pull/5620)).

**Comment by buildguy** [comment]
### :warning: Build finished in 1h 3m 16s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 4 test(s) failed:

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsRunWhenNoBlockout</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsBlockedDuringABlockout</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testMDCContext</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsRunWhenThereIsAnExceptionRetrievingTheBlockoutManager</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

  
Tests run: **2809**, Failures: **4**, Skipped: **3** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform-jdk11/job/PR-5715/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
