### PR TITLE
[TEST] Increase test coverage

### PR DESCRIPTION
**Pull request by DFieldFL**

### CODE REVIEW

**Comment by DFieldFL** [comment]
@mattyb149 please review and merge

**Comment by mattyb149** [comment]
Changed files:
==============
  api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileAclTest.java
  api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileSidTest.java
  api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileTreeTest.java

Checkstyle violations:
----------------------
Errors:File api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileAclTest.java
1. Message: 'catch' is not followed by whitespace. at Line: 79 Column: 12File api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileSidTest.java
1. Message: ')' is not preceded with whitespace. at Line: 48 Column: 61File api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileTreeTest.java
1. Message: 'catch' is not followed by whitespace. at Line: 69 Column: 12
2. Message: '(' is not followed by whitespace. at Line: 82 Column: 102
3. Message: ')' is not preceded with whitespace. at Line: 82 Column: 103

Newly Broken Tests:
=================
Test Case Errors:
-----------------
  org.pentaho.platform.api.repository2.unified.RepositoryFileTreeTest.testBuilderWithNullChildren: java.lang.NullPointerException
```
java.lang.NullPointerException
	at org.pentaho.platform.api.repository2.unified.RepositoryFileTree$Builder.toBuilderChildren(RepositoryFileTree.java:201)
	at org.pentaho.platform.api.repository2.unified.RepositoryFileTree$Builder.<init>(RepositoryFileTree.java:180)
	at org.pentaho.platform.api.repository2.unified.RepositoryFileTree$Builder.toBuilderChildren(RepositoryFileTree.java:203)
	at org.pentaho.platform.api.repository2.unified.RepositoryFileTree$Builder.<init>(RepositoryFileTree.java:180)
	at org.pentaho.platform.api.repository2.unified.RepositoryFileTreeTest.testBuilderWithNullChildren(RepositoryFileTreeTest.java:100)

```


Unit test coverage change:
============
org.pentaho.platform.api.repository2.unified.RepositoryFileSid:
 * instructionPercentCoverageChange : +73.60%
 * branchPercentCoverageChange : +65.00%
 * linePercentCoverageChange : +62.16%
 * complexityPercentCoverageChange : +61.11%
 * methodPercentCoverageChange : +62.50%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileAcl.Builder:
 * instructionPercentCoverageChange : +61.02%
 * branchPercentCoverageChange : +100.00%
 * linePercentCoverageChange : +75.00%
 * complexityPercentCoverageChange : +61.11%
 * methodPercentCoverageChange : +58.82%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileAcl:
 * instructionPercentCoverageChange : +91.13%
 * branchPercentCoverageChange : +69.44%
 * linePercentCoverageChange : +91.67%
 * complexityPercentCoverageChange : +66.67%
 * methodPercentCoverageChange : +100.00%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileTree:
 * instructionPercentCoverageChange : +90.16%
 * branchPercentCoverageChange : +75.00%
 * linePercentCoverageChange : +92.00%
 * complexityPercentCoverageChange : +74.07%
 * methodPercentCoverageChange : +92.31%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileTree.Builder:
 * instructionPercentCoverageChange : +85.57%
 * branchPercentCoverageChange : +100.00%
 * linePercentCoverageChange : +82.61%
 * complexityPercentCoverageChange : +72.73%
 * methodPercentCoverageChange : +66.67%
    
org.pentaho.platform.api.repository2.unified.RepositoryFile:
 * instructionPercentCoverageChange : +0.72%
 * branchPercentCoverageChange : +3.23%
 * linePercentCoverageChange : +1.12%
 * complexityPercentCoverageChange : +3.33%

**Comment by brosander** [comment]
Changed files:
==============
  api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileAclTest.java
  api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileSidTest.java
  api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileTreeTest.java

Checkstyle violations:
----------------------
Errors:File api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileAclTest.java
1. Message: 'catch' is not followed by whitespace. at Line: 79 Column: 12File api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileSidTest.java
1. Message: ')' is not preceded with whitespace. at Line: 48 Column: 61File api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileTreeTest.java
1. Message: 'catch' is not followed by whitespace. at Line: 69 Column: 12
2. Message: '(' is not followed by whitespace. at Line: 82 Column: 102
3. Message: ')' is not preceded with whitespace. at Line: 82 Column: 103

Newly Broken Tests:
-----------------
org.pentaho.platform.api.repository2.unified.RepositoryFileTreeTest.testBuilderWithNullChildren: java.lang.NullPointerException
```
java.lang.NullPointerException
	at org.pentaho.platform.api.repository2.unified.RepositoryFileTree$Builder.toBuilderChildren(RepositoryFileTree.java:201)
	at org.pentaho.platform.api.repository2.unified.RepositoryFileTree$Builder.<init>(RepositoryFileTree.java:180)
	at org.pentaho.platform.api.repository2.unified.RepositoryFileTree$Builder.toBuilderChildren(RepositoryFileTree.java:203)
	at org.pentaho.platform.api.repository2.unified.RepositoryFileTree$Builder.<init>(RepositoryFileTree.java:180)
	at org.pentaho.platform.api.repository2.unified.RepositoryFileTreeTest.testBuilderWithNullChildren(RepositoryFileTreeTest.java:100)

```





Unit test coverage change:
============
org.pentaho.platform.api.repository2.unified.RepositoryFileSid:
 * instructionPercentCoverageChange : +73.60%
 * branchPercentCoverageChange : +65.00%
 * linePercentCoverageChange : +62.16%
 * complexityPercentCoverageChange : +61.11%
 * methodPercentCoverageChange : +62.50%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileAcl.Builder:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :75.00%
 * methodPercentCoverage :58.82%
 * complexityPercentCoverage :61.11%
 * instructionPercentCoverage :61.02%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileAcl:
 * branchPercentCoverage :69.44%
 * linePercentCoverage :91.67%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :66.67%
 * instructionPercentCoverage :91.13%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileTree:
 * branchPercentCoverage :75.00%
 * linePercentCoverage :92.00%
 * methodPercentCoverage :92.31%
 * complexityPercentCoverage :74.07%
 * instructionPercentCoverage :90.16%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileTree.Builder:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :82.61%
 * methodPercentCoverage :66.67%
 * complexityPercentCoverage :72.73%
 * instructionPercentCoverage :85.57%
    
org.pentaho.platform.api.repository2.unified.RepositoryFile:
 * instructionPercentCoverageChange : +0.72%
 * branchPercentCoverageChange : +3.23%
 * linePercentCoverageChange : +1.12%
 * complexityPercentCoverageChange : +3.33%

**Comment by DFieldFL** [comment]
Fixed break on null children when using the builder

**Comment by mattyb149** [comment]
Changed files:
==============
  api/src/org/pentaho/platform/api/repository2/unified/RepositoryFileTree.java
  api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileAclTest.java
  api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileSidTest.java
  api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileTreeTest.java

Checkstyle violations:
----------------------
Errors:File api/src/org/pentaho/platform/api/repository2/unified/RepositoryFileTree.java
1. Message: Line has trailing spaces. at Line: 53 Column: NoneFile api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileAclTest.java
1. Message: 'catch' is not followed by whitespace. at Line: 79 Column: 12File api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileSidTest.java
1. Message: ')' is not preceded with whitespace. at Line: 48 Column: 61




Unit test coverage change:
============
org.pentaho.platform.api.repository2.unified.RepositoryFileSid:
 * instructionPercentCoverageChange : +73.60%
 * branchPercentCoverageChange : +65.00%
 * linePercentCoverageChange : +62.16%
 * complexityPercentCoverageChange : +61.11%
 * methodPercentCoverageChange : +62.50%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileAcl.Builder:
 * instructionPercentCoverageChange : +61.02%
 * branchPercentCoverageChange : +100.00%
 * linePercentCoverageChange : +75.00%
 * complexityPercentCoverageChange : +61.11%
 * methodPercentCoverageChange : +58.82%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileAcl:
 * instructionPercentCoverageChange : +91.13%
 * branchPercentCoverageChange : +69.44%
 * linePercentCoverageChange : +91.67%
 * complexityPercentCoverageChange : +66.67%
 * methodPercentCoverageChange : +100.00%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileTree:
 * instructionPercentCoverageChange : +90.16%
 * branchPercentCoverageChange : +75.00%
 * linePercentCoverageChange : +92.00%
 * complexityPercentCoverageChange : +74.07%
 * methodPercentCoverageChange : +92.31%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileTree.Builder:
 * instructionPercentCoverageChange : +86.67%
 * branchPercentCoverageChange : +100.00%
 * linePercentCoverageChange : +85.19%
 * complexityPercentCoverageChange : +76.92%
 * methodPercentCoverageChange : +66.67%
    
org.pentaho.platform.api.repository2.unified.RepositoryFile:
 * instructionPercentCoverageChange : +0.72%
 * branchPercentCoverageChange : +3.23%
 * linePercentCoverageChange : +1.12%
 * complexityPercentCoverageChange : +3.33%

**Comment by mattyb149** [comment]
Changed files:
==============
  api/src/org/pentaho/platform/api/repository2/unified/RepositoryFileTree.java
  api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileAclTest.java
  api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileSidTest.java
  api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileTreeTest.java

Checkstyle violations:
----------------------
No errors found




Unit test coverage change:
============
org.pentaho.platform.api.repository2.unified.RepositoryFileSid:
 * instructionPercentCoverageChange : +73.60%
 * branchPercentCoverageChange : +65.00%
 * linePercentCoverageChange : +62.16%
 * complexityPercentCoverageChange : +61.11%
 * methodPercentCoverageChange : +62.50%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileAcl.Builder:
 * instructionPercentCoverageChange : +61.02%
 * branchPercentCoverageChange : +100.00%
 * linePercentCoverageChange : +75.00%
 * complexityPercentCoverageChange : +61.11%
 * methodPercentCoverageChange : +58.82%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileAcl:
 * instructionPercentCoverageChange : +91.13%
 * branchPercentCoverageChange : +69.44%
 * linePercentCoverageChange : +91.67%
 * complexityPercentCoverageChange : +66.67%
 * methodPercentCoverageChange : +100.00%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileTree:
 * instructionPercentCoverageChange : +90.16%
 * branchPercentCoverageChange : +75.00%
 * linePercentCoverageChange : +92.00%
 * complexityPercentCoverageChange : +74.07%
 * methodPercentCoverageChange : +92.31%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileTree.Builder:
 * instructionPercentCoverageChange : +86.67%
 * branchPercentCoverageChange : +100.00%
 * linePercentCoverageChange : +85.19%
 * complexityPercentCoverageChange : +76.92%
 * methodPercentCoverageChange : +66.67%
    
org.pentaho.platform.api.repository2.unified.RepositoryFile:
 * instructionPercentCoverageChange : +0.72%
 * branchPercentCoverageChange : +3.23%
 * linePercentCoverageChange : +1.12%
 * complexityPercentCoverageChange : +3.33%

**Comment by DFieldFL** [comment]
@dkincade Had to change a small portion of the core api based on a broken test I wrote. 
https://github.com/pentaho/pentaho-platform/pull/2672/files#diff-fc218965aaa183f982ac4059963f4407R205
https://github.com/pentaho/pentaho-platform/pull/2672/files#diff-fc218965aaa183f982ac4059963f4407R193

**Comment by lucboudreau** [comment]
Changed files:
==============
  api/src/org/pentaho/platform/api/repository2/unified/RepositoryFileTree.java
  api/src/org/pentaho/platform/api/repository2/unified/RepositoryRequest.java
  api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileAclTest.java
  api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileSidTest.java
  api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileTreeTest.java
  api/test-src/org/pentaho/platform/api/repository2/unified/VersionSummaryTest.java
  api/test-src/org/pentaho/platform/api/repository2/unified/data/node/DataPropertyTest.java

Checkstyle violations:
----------------------
Errors:File api/test-src/org/pentaho/platform/api/repository2/unified/VersionSummaryTest.java
1. Message: ')' is not preceded with whitespace. at Line: 60 Column: 59
2. Message: ')' is not preceded with whitespace. at Line: 67 Column: 59
3. Message: ')' is not preceded with whitespace. at Line: 74 Column: 59
4. Message: ')' is not preceded with whitespace. at Line: 81 Column: 59







Unit test coverage change:
============
org.pentaho.platform.api.repository2.unified.RepositoryFileSid:
 * instructionPercentCoverageChange : +73.60%
 * branchPercentCoverageChange : +65.00%
 * linePercentCoverageChange : +62.16%
 * complexityPercentCoverageChange : +61.11%
 * methodPercentCoverageChange : +62.50%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileAcl.Builder:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :75.00%
 * methodPercentCoverage :58.82%
 * complexityPercentCoverage :61.11%
 * instructionPercentCoverage :61.02%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileAcl:
 * branchPercentCoverage :69.44%
 * linePercentCoverage :91.67%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :66.67%
 * instructionPercentCoverage :91.13%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileTree:
 * branchPercentCoverage :75.00%
 * linePercentCoverage :92.00%
 * methodPercentCoverage :92.31%
 * complexityPercentCoverage :74.07%
 * instructionPercentCoverage :90.16%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileTree.Builder:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :85.19%
 * methodPercentCoverage :66.67%
 * complexityPercentCoverage :76.92%
 * instructionPercentCoverage :86.92%
    
org.pentaho.platform.api.repository2.unified.VersionSummary:
 * branchPercentCoverage :81.82%
 * linePercentCoverage :95.56%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :87.50%
 * instructionPercentCoverage :96.30%
    
org.pentaho.platform.api.repository2.unified.data.node.DataProperty:
 * instructionPercentCoverageChange : +0.88%
 * branchPercentCoverageChange : +2.27%
    
org.pentaho.platform.api.repository2.unified.RepositoryFile:
 * instructionPercentCoverageChange : +0.72%
 * branchPercentCoverageChange : +3.23%
 * linePercentCoverageChange : +1.12%
 * complexityPercentCoverageChange : +3.33%

**Comment by lucboudreau** [comment]
Changed files:
==============
  api/src/org/pentaho/platform/api/repository2/unified/RepositoryFileTree.java
  api/src/org/pentaho/platform/api/repository2/unified/RepositoryRequest.java
  api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileAclTest.java
  api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileSidTest.java
  api/test-src/org/pentaho/platform/api/repository2/unified/RepositoryFileTreeTest.java
  api/test-src/org/pentaho/platform/api/repository2/unified/VersionSummaryTest.java
  api/test-src/org/pentaho/platform/api/repository2/unified/data/node/DataPropertyTest.java

Checkstyle violations:
----------------------
No errors found







Unit test coverage change:
============
org.pentaho.platform.api.repository2.unified.RepositoryFileSid:
 * instructionPercentCoverageChange : +73.60%
 * branchPercentCoverageChange : +65.00%
 * linePercentCoverageChange : +62.16%
 * complexityPercentCoverageChange : +61.11%
 * methodPercentCoverageChange : +62.50%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileAcl.Builder:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :75.00%
 * methodPercentCoverage :58.82%
 * complexityPercentCoverage :61.11%
 * instructionPercentCoverage :61.02%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileAcl:
 * branchPercentCoverage :69.44%
 * linePercentCoverage :91.67%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :66.67%
 * instructionPercentCoverage :91.13%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileTree:
 * branchPercentCoverage :75.00%
 * linePercentCoverage :92.00%
 * methodPercentCoverage :92.31%
 * complexityPercentCoverage :74.07%
 * instructionPercentCoverage :90.16%
    
org.pentaho.platform.api.repository2.unified.RepositoryFileTree.Builder:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :85.19%
 * methodPercentCoverage :66.67%
 * complexityPercentCoverage :76.92%
 * instructionPercentCoverage :86.92%
    
org.pentaho.platform.api.repository2.unified.VersionSummary:
 * branchPercentCoverage :81.82%
 * linePercentCoverage :95.56%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :87.50%
 * instructionPercentCoverage :96.30%
    
org.pentaho.platform.api.repository2.unified.data.node.DataProperty:
 * instructionPercentCoverageChange : +0.88%
 * branchPercentCoverageChange : +2.27%
    
org.pentaho.platform.api.repository2.unified.RepositoryFile:
 * instructionPercentCoverageChange : +0.72%
 * branchPercentCoverageChange : +3.23%
 * linePercentCoverageChange : +1.12%
 * complexityPercentCoverageChange : +3.33%

**Comment by DFieldFL** [comment]
@bytekast @rmansoor @kurtwalker please review and merge. David is good with adding the null check.

**Pull request merged**
