### PR TITLE
[SP-2662] Backport of BISERVER-13184 - IE8 - Empty UI after login to …

### PR DESCRIPTION
**Pull request by mchen-len-son**
…PUC (5.4 Suite)

- added json2.js lib to the app
- added custom GWT linker adding json2.js for IE8,IE9 permutations
- added unit test for the new linker

### CODE REVIEW

**Comment by mchen-len-son** [comment]
@pamval @rfellows please review

**Comment by mchen-len-son** [comment]
fixed a couple of checkstyle violations

**Comment by pamval** [comment]
@mchen-len-son the json2.js file doesn't look right. Is it supposed to be an html file ?

**Comment by pamval** [comment]
Also, if this file was not yet part of our deliverables, we need to create a new component ticket for it.

**Pull request merged**
