### PR TITLE
[BACKLOG-5720] - Static html page doesn't have fonts and background i…

### PR DESCRIPTION
**Pull request by apratkin**
…mage before plugins are initialized

Changes:
I copied images and fonts files to html page.
I updated InitState.html to look files at the same folder.
I updated SystemInitStatusFilter: if requested resource is related to initState page forward to it. To avoid check if user is logged in.

### CODE REVIEW

**Comment by apratkin** [comment]
@rmansoor could you take a look?

**Comment by rmansoor** [comment]
@apratkin we can not hard code pentaho webapp. This is not guaranteed. So please remove this and try it without the webapp name

**Comment by apratkin** [comment]
@rmansoor updated

**Comment by rmansoor** [comment]
@apratkin please rebase your branch and rebuild. There is a compile error in SystemInitStatusFilter
import org.pentaho.platform.engine.core.system.status.ServerStatusProvider;
has been moved to 
import org.pentaho.platform.api.engine.ServerStatusProvider;

**Comment by apratkin** [comment]
@rmansoor Done.
I rebased and removed unused import. Verified compilation passed successfully and server starts successfully.

**Comment by rmansoor** [comment]
After review, we have decided that we do not need this work right now. I have reverted all the changes related to the static page. Closing this PR now

**Pull request closed without merging**
