### PR TITLE
[SP-2791] Backport of BISERVER-12069 - MdxBaseComponent forces all ca…

### PR DESCRIPTION
**Pull request by ivanpogodin**
…talog URLs to start with http: or solution: (6.1 Suite)

pick [BISERVER-12069] MdxBaseComponent forces all catalog URLs to start with http: or solution:

### CODE REVIEW

**Comment by ivanpogodin** [comment]
@lucboudreau , @rfellows , could you review it?
Using static imports wasn't a problem in master branch. Should the imports be removed here?

**Comment by rfellows** [comment]
the broken tests are concerning. can you look into those? it doesn't look like you broke them, but if you are in there we should clean up the broken tests too.

**Comment by ivanpogodin** [comment]
@rfellows , test is fixed

**Comment by pamval** [comment]
@ivanpogodin please update the license header on that file

**Comment by ivanpogodin** [comment]
@pamval , license is updated

**Pull request merged**
