### PR TITLE
[SP-5801] - Backport of BISERVER-14534 - Running jobs or transformations via Schedules created on PUC stop running after multiple executions (9.1 Suite)

### PR DESCRIPTION
**Pull request by bcostahitachivantara**
@pentaho-lmartins 
@ssamora 
@smmribeiro

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 20m 30s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,core,repository,scheduler
```
---
:ok_hand: All tests passed!
 
Tests run: **1090**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4777/1/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 17m 52s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,core,repository,scheduler
```
---
:ok_hand: All tests passed!
 
Tests run: **1035**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4777/2/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 17m 38s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,core,repository,scheduler
```
---
:ok_hand: All tests passed!
 
Tests run: **1035**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4777/3/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 19m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,core,repository,scheduler
```
---
:ok_hand: All tests passed!
 
Tests run: **1090**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4777/4/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by pentaho-lmartins — APPROVED** [review]

**Pull request merged**
