### PR TITLE
[SP-2512] Backport of BISERVER-11649 - Mondrian role mappers don't pass the role name of a user when his username and group are both 'Admin' (6.0 Suite)

### PR DESCRIPTION
**Pull request by IvanNikolaychuk**
**UserRoleDaoResource**

- Track every update of roles, and if this update is touching a user in current session, updating IPentahoSession.SESSION_ROLES attribute, that represents the roles, avalible for current user.

We are doing it via userRoleDaoService, because data there is always up-to-date
- Added few helper methods and changed visibility of some methods for testing reasongs

**UserRoleDaoResource_RoleUpdatesTest**
- A separate test, written specially for checking, that roles were/were not (depending on whether user is session-user or not) updated.

**UserRoleDaoResourceTest**
- Changed few tests a little,(added several mocks), as method content changed.

@akhayrutdinov, could you please review it? It is a backport of https://github.com/pentaho/pentaho-platform/pull/2788

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@tgf, @pamval, could you please start WM?

**Comment by pamval** [comment]
started wingman

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
  extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
  extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource_RolesUpdatedTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
1. Message: Using a static member import should be avoided - org.junit.Assert.assertEquals. at Line: 20 Column: None
2. Message: Using a static member import should be avoided - org.mockito.Matchers.any. at Line: 21 Column: None
3. Message: Using a static member import should be avoided - org.mockito.Matchers.anyString. at Line: 22 Column: None
4. Message: Using a static member import should be avoided - org.mockito.Mockito.*. at Line: 23 Column: None
5. Message: Unused import - org.mockito.Mockito. at Line: 32 Column: 8

File extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource_RolesUpdatedTest.java
1. Message: Using a static member import should be avoided - org.junit.Assert.assertTrue. at Line: 40 Column: None
2. Message: Using a static member import should be avoided - org.mockito.Mockito.*. at Line: 41 Column: None



Newly Broken Tests:
-----------------
org.pentaho.test.platform.web.ui.component.FilterDefinitionIT.testNothing: java.lang.NoClassDefFoundError
```
java.lang.NoClassDefFoundError: Could not initialize class org.pentaho.platform.repository.hibernate.HibernateUtil
	at org.pentaho.platform.repository.hibernate.HibernateUtil.$jacocoInit(HibernateUtil.java)
	at org.pentaho.platform.repository.hibernate.HibernateUtil.systemExitPoint(HibernateUtil.java)
	at org.pentaho.platform.engine.core.system.StandaloneApplicationContext.invokeExitPoints(StandaloneApplicationContext.java:181)
	at org.pentaho.platform.engine.core.system.PentahoSystem.systemExitPoint(PentahoSystem.java:1203)
	at org.pentaho.test.platform.engine.core.BaseTest.tearDown(BaseTest.java:174)

```
org.pentaho.test.platform.web.ui.component.FilterDefinitionIT.testFilterCreation: java.lang.ExceptionInInitializerError
```
java.lang.ExceptionInInitializerError
	at org.pentaho.platform.repository.hibernate.HibernateUtil.initialize(HibernateUtil.java:199)
	at org.pentaho.platform.repository.hibernate.HibernateUtil.<clinit>(HibernateUtil.java:90)
	at org.pentaho.platform.repository.runtime.RuntimeRepository.setSession(RuntimeRepository.java:72)
	at org.pentaho.platform.repository.runtime.RuntimeRepository.init(RuntimeRepository.java:77)
	at org.pentaho.platform.engine.core.system.objfac.AbstractSpringPentahoObjectFactory.retreiveObject(AbstractSpringPentahoObjectFactory.java:266)
	at org.pentaho.platform.engine.core.system.objfac.AbstractSpringPentahoObjectFactory.get(AbstractSpringPentahoObjectFactory.java:82)
	at org.pentaho.platform.engine.core.system.objfac.AggregateObjectFactory.get(AggregateObjectFactory.java:273)
	at org.pentaho.platform.engine.core.system.objfac.AggregateObjectFactory.get(AggregateObjectFactory.java:137)
	at org.pentaho.platform.engine.core.system.PentahoSystem.get(PentahoSystem.java:757)
	at org.pentaho.platform.engine.core.system.PentahoSystem.get(PentahoSystem.java:738)
	at org.pentaho.platform.engine.services.solution.SolutionEngine.execute(SolutionEngine.java:219)
	at org.pentaho.platform.engine.services.solution.SolutionEngine.execute(SolutionEngine.java:179)
	at org.pentaho.platform.uifoundation.component.ActionFilterDefinition.getResultSet(ActionFilterDefinition.java:85)
	at org.pentaho.platform.uifoundation.component.FilterDefinition.populate(FilterDefinition.java:243)
	at org.pentaho.test.platform.web.ui.component.FilterDefinitionIT.testFilterCreation(FilterDefinitionIT.java:106)
Caused by: org.hibernate.HibernateException: Could not parse configuration: test-src/web-solution/system/hibernate/hsql.hibernate.cfg.xml
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2246)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:2216)
	at org.pentaho.platform.repository.hibernate.HibernateUtil.initialize(HibernateUtil.java:138)
Caused by: org.dom4j.DocumentException: Server returned HTTP response code: 503 for URL: http://hibernate.sourceforge.net/hibernate-configuration-3.0.dtd Nested exception: Server returned HTTP response code: 503 for URL: http://hibernate.sourceforge.net/hibernate-configuration-3.0.dtd
	at org.dom4j.io.SAXReader.read(SAXReader.java:484)
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2238)

```



Still Broken Tests:
-----------------
org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillImportAllZipsInADirectory: org.mockito.exceptions.verification.junit.ArgumentsAreDifferent
```
Argument(s) are different! Wanted:
file.renameTo(
    
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillImportAllZipsInADirectory(ArchiveLoaderTest.java:66)
Actual invocation has different arguments:
file.renameTo(
    /root/path/jobs.zip.197001021017
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoader.loadAll(ArchiveLoader.java:68)

	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillImportAllZipsInADirectory(ArchiveLoaderTest.java:66)

```
org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillContinueToLoadOnException: org.mockito.exceptions.verification.junit.ArgumentsAreDifferent
```
Argument(s) are different! Wanted:
file.renameTo(
    
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillContinueToLoadOnException(ArchiveLoaderTest.java:93)
Actual invocation has different arguments:
file.renameTo(
    /root/path/jobs.zip.197001021017
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoader.loadAll(ArchiveLoader.java:68)

	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillContinueToLoadOnException(ArchiveLoaderTest.java:93)

```

Unit test coverage change:
============
org.pentaho.platform.plugin.services.metadata.PentahoMetadataDomainRepository:
 * instructionPercentCoverageChange :**-0.95%**
 * branchPercentCoverageChange :**-1.32%**
 * linePercentCoverageChange :**-0.58%**
 * complexityPercentCoverageChange :**-0.83%**
    
org.pentaho.platform.web.http.api.resources.UserRoleDaoResource:
 * instructionPercentCoverageChange : +26.29%
 * branchPercentCoverageChange : +43.38%
 * linePercentCoverageChange : +18.72%
 * complexityPercentCoverageChange : +19.18%
 * methodPercentCoverageChange : +13.48%
    
Integration test coverage change:
============
org.pentaho.platform.plugin.services.connections.sql.SQLResultSet:
 * instructionPercentCoverageChange :**-0.65%**
 * linePercentCoverageChange :**-1.53%**
 * complexityPercentCoverageChange :**-2.33%**
 * methodPercentCoverageChange :**-5.88%**
    
org.pentaho.platform.plugin.action.sql.SQLBaseComponent:
 * instructionPercentCoverageChange :**-1.99%**
 * branchPercentCoverageChange :**-2.27%**
 * linePercentCoverageChange :**-2.90%**
 * complexityPercentCoverageChange :**-1.75%**
 * methodPercentCoverageChange :**-3.85%**
    
org.pentaho.platform.plugin.action.chartbeans.ChartAction:
 * instructionPercentCoverageChange :**-0.45%**

**Comment by akhayrutdinov** [comment]
suspended

**Comment by IvanNikolaychuk** [comment]
@akhayrutdinov updated.

@pedrofvteixeira, @pamval, could you please start WM?

**Comment by pedrofvteixeira** [comment]
[Starting wingman](http://10.100.11.222:8080/job/wingman-ant/355)

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
  extensions/test-src/org/pentaho/platform/admin/GeneratedContentCleanerTest.java
  extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
  extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource_RolesUpdatedTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
1. Message: Line has trailing spaces at Line: 527 Column: None
2. Message: Line has trailing spaces at Line: 528 Column: None
3. Message: Line has trailing spaces at Line: 529 Column: None
4. Message: Line has trailing spaces at Line: 577 Column: None
5. Message: Line has trailing spaces at Line: 578 Column: None
6. Message: Line has trailing spaces at Line: 579 Column: None
7. Message: Line has trailing spaces at Line: 614 Column: None
8. Message: Line has trailing spaces at Line: 615 Column: None
9. Message: Line has trailing spaces at Line: 616 Column: None
10. Message: Line has trailing spaces at Line: 618 Column: None
11. Message: ')' is not preceded with whitespace. at Line: 620 Column: 72
12. Message: '}' have incorrect indentation level 2, expected level should be 4. at Line: 816 Column: None
13. Message: 'catch' child have incorrect indentation level 5, expected level should be 6. at Line: 821 Column: None
14. Message: '}' have incorrect indentation level 3, expected level should be 4. at Line: 855 Column: None

File extensions/test-src/org/pentaho/platform/admin/GeneratedContentCleanerTest.java
1. Message: Using a static member import should be avoided - org.junit.Assert.*. at Line: 38 Column: None
2. Message: Using a static member import should be avoided - org.mockito.Matchers.*. at Line: 39 Column: None
3. Message: Using a static member import should be avoided - org.mockito.Mockito.*. at Line: 40 Column: None

File extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
1. Message: Using a static member import should be avoided - org.junit.Assert.assertEquals. at Line: 20 Column: None
2. Message: Using a static member import should be avoided - org.mockito.Matchers.any. at Line: 21 Column: None
3. Message: Using a static member import should be avoided - org.mockito.Matchers.anyString. at Line: 22 Column: None
4. Message: Using a static member import should be avoided - org.mockito.Mockito.*. at Line: 23 Column: None
5. Message: Unused import - org.mockito.Mockito. at Line: 32 Column: 8

File extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource_RolesUpdatedTest.java
1. Message: Using a static member import should be avoided - org.junit.Assert.assertTrue. at Line: 40 Column: None
2. Message: Using a static member import should be avoided - org.mockito.Mockito.*. at Line: 41 Column: None







Still Broken Tests:
-----------------
org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillImportAllZipsInADirectory: org.mockito.exceptions.verification.junit.ArgumentsAreDifferent
```
Argument(s) are different! Wanted:
file.renameTo(
    
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillImportAllZipsInADirectory(ArchiveLoaderTest.java:66)
Actual invocation has different arguments:
file.renameTo(
    /root/path/jobs.zip.197001021017
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoader.loadAll(ArchiveLoader.java:68)

	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillImportAllZipsInADirectory(ArchiveLoaderTest.java:66)

```
org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillContinueToLoadOnException: org.mockito.exceptions.verification.junit.ArgumentsAreDifferent
```
Argument(s) are different! Wanted:
file.renameTo(
    
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillContinueToLoadOnException(ArchiveLoaderTest.java:93)
Actual invocation has different arguments:
file.renameTo(
    /root/path/jobs.zip.197001021017
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoader.loadAll(ArchiveLoader.java:68)

	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillContinueToLoadOnException(ArchiveLoaderTest.java:93)

```

Unit test coverage change:
============
org.pentaho.platform.web.http.api.resources.UserRoleDaoResource:
 * instructionPercentCoverageChange : +26.37%
 * branchPercentCoverageChange : +43.38%
 * linePercentCoverageChange : +18.89%
 * complexityPercentCoverageChange : +19.18%
 * methodPercentCoverageChange : +13.48%
    
org.pentaho.platform.admin.GeneratedContentCleaner:
 * branchPercentCoverage :90.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :90.91%
 * instructionPercentCoverage :100.00%
    
Integration test coverage change:
============
org.pentaho.platform.plugin.action.chartbeans.ChartAction:
 * instructionPercentCoverageChange :**-0.45%**

**Comment by akhayrutdinov** [comment]
```
File extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
1. Message: Line has trailing spaces at Line: 527 Column: None
2. Message: Line has trailing spaces at Line: 528 Column: None
3. Message: Line has trailing spaces at Line: 529 Column: None
4. Message: Line has trailing spaces at Line: 577 Column: None
5. Message: Line has trailing spaces at Line: 578 Column: None
6. Message: Line has trailing spaces at Line: 579 Column: None
7. Message: Line has trailing spaces at Line: 614 Column: None
8. Message: Line has trailing spaces at Line: 615 Column: None
9. Message: Line has trailing spaces at Line: 616 Column: None
10. Message: Line has trailing spaces at Line: 618 Column: None
11. Message: ')' is not preceded with whitespace. at Line: 620 Column: 72
12. Message: '}' have incorrect indentation level 2, expected level should be 4. at Line: 816 Column: None
13. Message: 'catch' child have incorrect indentation level 5, expected level should be 6. at Line: 821 Column: None
14. Message: '}' have incorrect indentation level 3, expected level should be 4. at Line: 855 Column: None
```
and others

**Comment by IvanNikolaychuk** [comment]
@akhayrutdinov, I'm sorry, everything is fixed now

**Comment by pedrofvteixeira** [comment]
[wingman](http://10.100.11.222:8080/job/wingman-ant/356)

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
  extensions/test-src/org/pentaho/platform/admin/GeneratedContentCleanerTest.java
  extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
  extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource_RolesUpdatedTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File extensions/test-src/org/pentaho/platform/admin/GeneratedContentCleanerTest.java
1. Message: Using a static member import should be avoided - org.junit.Assert.*. at Line: 38 Column: None
2. Message: Using a static member import should be avoided - org.mockito.Matchers.*. at Line: 39 Column: None
3. Message: Using a static member import should be avoided - org.mockito.Mockito.*. at Line: 40 Column: None

File extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
1. Message: Using a static member import should be avoided - org.junit.Assert.assertEquals. at Line: 20 Column: None
2. Message: Using a static member import should be avoided - org.mockito.Matchers.any. at Line: 21 Column: None
3. Message: Using a static member import should be avoided - org.mockito.Matchers.anyString. at Line: 22 Column: None
4. Message: Using a static member import should be avoided - org.mockito.Mockito.*. at Line: 23 Column: None

File extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource_RolesUpdatedTest.java
1. Message: Using a static member import should be avoided - org.junit.Assert.assertTrue. at Line: 40 Column: None
2. Message: Using a static member import should be avoided - org.mockito.Mockito.*. at Line: 41 Column: None







Still Broken Tests:
-----------------
org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillImportAllZipsInADirectory: org.mockito.exceptions.verification.junit.ArgumentsAreDifferent
```
Argument(s) are different! Wanted:
file.renameTo(
    
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillImportAllZipsInADirectory(ArchiveLoaderTest.java:66)
Actual invocation has different arguments:
file.renameTo(
    /root/path/jobs.zip.197001021017
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoader.loadAll(ArchiveLoader.java:68)

	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillImportAllZipsInADirectory(ArchiveLoaderTest.java:66)

```
org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillContinueToLoadOnException: org.mockito.exceptions.verification.junit.ArgumentsAreDifferent
```
Argument(s) are different! Wanted:
file.renameTo(
    
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillContinueToLoadOnException(ArchiveLoaderTest.java:93)
Actual invocation has different arguments:
file.renameTo(
    /root/path/jobs.zip.197001021017
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoader.loadAll(ArchiveLoader.java:68)

	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillContinueToLoadOnException(ArchiveLoaderTest.java:93)

```

Unit test coverage change:
============
org.pentaho.platform.web.http.api.resources.UserRoleDaoResource:
 * instructionPercentCoverageChange : +26.37%
 * branchPercentCoverageChange : +43.38%
 * linePercentCoverageChange : +18.89%
 * complexityPercentCoverageChange : +19.18%
 * methodPercentCoverageChange : +13.48%
    
org.pentaho.platform.admin.GeneratedContentCleaner:
 * branchPercentCoverage :90.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :90.91%
 * instructionPercentCoverage :100.00%
    
Integration test coverage change:
============
org.pentaho.platform.plugin.action.chartbeans.ChartAction:
 * instructionPercentCoverageChange : +0.45%

**Comment by akhayrutdinov** [comment]
On CI, no tests fail. Is it a WM error?

**Pull request merged**
