### PR TITLE
[SP-3081][BISERVER-13264] When using a custom AccessVoter, cut/paste does not check for write permission on destination

### PR DESCRIPTION
**Pull request by mchen-len-son**

### CODE REVIEW

**Comment by mchen-len-son** [comment]
@pamval @mbatchelor @rfellows please take a look.

This is a backport of #3030.

**Comment by pamval** [comment]
@mchen-len-son what's the issue with FileResource and why isn't that warning triggered in master? Was there a refactoring for this file?

**Comment by mchen-len-son** [comment]
@pamval I have removed static imports from FileResource.
During replacing, I accidently replaced logging string constants values - that was catched by unit test.
Now it's all clear - I verified.

**Comment by pamval** [comment]
I meant why is this file so large in the 6.1 branch ?

 

Pedro Vale

Senior Director of Development

phone: +351 214870076       fax: +351 218041985

Taguspark - Edificio Qualidade C2

Avenida Prof. Dr. Cavaco Silva, nr 1, 3rd floor

2740-296 Porto Salvo, Portugal

pentaho.com

 

 

 

De: Mikhail Chen-Len-Son <notifications@github.com>
Responder A: pentaho/pentaho-platform <reply@reply.github.com>
Data: quinta-feira, 22 de dezembro de 2016, 10:03
Para: pentaho/pentaho-platform <pentaho-platform@noreply.github.com>
Cc: Pedro Vale <pedro.vale@webdetails.pt>, Mention <mention@noreply.github.com>
Assunto: Re: [pentaho/pentaho-platform] [SP-3081][BISERVER-13264] When using a custom AccessVoter, cut/paste does not check for write permission on destination (#3318)

 

@pamval I have removed static imports from FileResource.
During replacing, I accidently replaced logging string constants values - that was catched by unit test.
Now it's all clear - I verified.

**Comment by mchen-len-son** [comment]
File length rule was removed in [pentaho-checkstyle-1.0.5.xml](http://nexus.pentaho.org/content/groups/omni/com/pentaho/pentaho-coding-standards/pentaho-checkstyle/1.0.5/pentaho-checkstyle-1.0.5.xml), but it's still existing in [pentaho-checkstyle-1.0.3.xml](http://nexus.pentaho.org/content/groups/omni/com/pentaho/pentaho-coding-standards/pentaho-checkstyle/1.0.3/pentaho-checkstyle-1.0.3.xml), which is used for 6.1.

**Pull request merged**
