### PR TITLE
[SP-6203] Backport of PPP-4761 - File Upload Path Disclosure exposed on Pentaho Server when file_name parameter uses special character (9.3 Suite)

### PR DESCRIPTION
**Pull request by andreramos89**

### CODE REVIEW

**Comment by andreramos89** [comment]
@smmribeiro 
@bcostahitachivantara 
@renato-s

**Comment by buildguy** [comment]
### :x: Build failed in 44m 49s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]

**Comment by smmribeiro** [comment]
Consistent with the original PR.

**Comment by buildguy** [comment]
### :x: Build failed in 34m 55s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 51m 29s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 27m 34s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
