### PR TITLE
MOBILE-525 - REGRESSION [IOS 8.1.1] Synchronization between the mobile a...

### PR DESCRIPTION
**Pull request by Aliaksandr-Kastenka**
...nd a desktop versions of PUC is performed not correctly

### CODE REVIEW

**Comment by Aliaksandr-Kastenka** [comment]
@rmansoor 
Please review.

**Comment by rmansoor** [comment]
@mdamour1976 can you please review this

**Comment by Aliaksandr-Kastenka** [comment]
@mdamour1976 
Please review.

**Comment by mdamour1976** [comment]
There are a few check-style problems.  I'm curious if this was a regression from 5.2.1 what the root cause was.

**Comment by Aliaksandr-Kastenka** [comment]
@mdamour1976 
As far as i understand this is not a regression.

**Comment by mdamour1976** [comment]
Interesting, according to QA:
REGRESSION:
Worked in:
5.2.1
Broken:
5.3.0

If that is true, I'd like to know why it regressed, otherwise, your fix is great, other than code format issues.

**Comment by Aliaksandr-Kastenka** [comment]
@mdamour1976 @wfaulkner 
According to my test result it is not working with provided steps in 5.2(verified using 5.2.NIGHTLY.201),  check-style problems fixed.

**Pull request merged**
