### PR TITLE
Async execution enhancements

### PR DESCRIPTION
**Pull request by EgorZhuk**
Seems to be sane to merge even before reporting plugin.

@tmorgner

### CODE REVIEW

**Comment by brosander** [comment]
Head build failed with return code 1

**Comment by tmorgner** [comment]
Wingman, please wait (you impatient bugger! :) ). The pull request here depends on commons-gwt changes.

**Comment by tmorgner** [comment]
Merged gwt-commons, waiting for it to build officially, then we can re-run wingman here.

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by tmorgner** [comment]
Wingman feels like it wants to throw a tantrum. Recommendation from Bryan: Ignore Wingman for this one.

**Pull request merged**
