### PR TITLE
[BISERVER-12808]-There is no error message if you run import-export.bat file with invalid command

### PR DESCRIPTION
**Pull request by PashkovichAndrei**
* Created validation for charset parameter

### CODE REVIEW

**Comment by PashkovichAndrei** [comment]
@mchen-len-son, could you please do review?

**Comment by PashkovichAndrei** [comment]
Solution was reworked. 
Also refactored class according TODO.

@mbatchelor, please review a fix

**Comment by mchen-len-son** [comment]
@mbatchelor can please take a look?

**Comment by pamval** [comment]
@PashkovichAndrei does this address Marc's comments in JIRA  about unknown options?

**Comment by pamval** [comment]
yeah, a simple test showing that behavior would be good.

**Comment by PashkovichAndrei** [comment]
@pamval, new tests was created.

But there is one possible danger place.
Let's imagine that we have a list of options: "abc" (-a, --abc); "bcd" (-b, --bcd); "cde" (-c, --cde). Then if we pass "-cde=123" to the command line, that lib (which is used at command line processor) will parse that as short option -c with value "de=123". That's how that lib works. 

My fix based on value validation after parsing option. So does that fix is acceptable for that issue or should I rework parsing of options and throw exception during the parsing?

**Comment by pamval** [comment]
that looks like a change in behavior that we should avoid. If this breaks existing behavior, I think you should rework your change

**Comment by PashkovichAndrei** [comment]
ok, I'll rework my solution

**Comment by PashkovichAndrei** [comment]
@pamval, @mbatchelor could you please do review of reworked solution?

**Comment by PashkovichAndrei** [comment]
@pamval, @mbatchelor could you please do review of reworked solution?

**Pull request merged**
