### PR TITLE
[BACKLOG-31898] CSRF - /ServiceAction

### PR DESCRIPTION
**Pull request by davidmsantos90**
@pentaho/millenniumfalcon please review

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 53s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/pentaho-solutions,assemblies/pentaho-war
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 52s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/pentaho-solutions,assemblies/pentaho-war
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 47s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/pentaho-solutions,assemblies/pentaho-war
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 1s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/pentaho-solutions,assemblies/pentaho-war
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by davidmsantos90** [comment]
@pentaho/millenniumfalcon pr updated. please review

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 1s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/pentaho-solutions,assemblies/pentaho-war
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 20s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/pentaho-solutions,assemblies/pentaho-war
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
