### PR TITLE
[PPP-3506] - XXE Security Vulnerability in xml parsers

### PR DESCRIPTION
**Pull request by YuryBY**
- additional fix

@mbatchelor, @rmansoor, @pamval, @CodeOnCoffee, could you please take a look?

### CODE REVIEW

**Comment by pamval** [comment]
Do not merge before 7.0 branches are created

**Comment by mbatchelor** [comment]
https://github.com/pentaho/pentaho-platform/blob/master/core/src/org/pentaho/platform/util/xml/XMLParserFactoryProducer.java - shouldn't this have the features set for XML entities, not just FEATURE_SECURE_PROCESSING - I didn't see it in your PR

**Comment by mbatchelor** [comment]
Also shouldn't https://github.com/pentaho/pentaho-platform/blob/master/core/src/org/pentaho/platform/util/xml/dom4j/XmlDom4JHelper.java be updated ?

**Comment by mbatchelor** [comment]
Seems like you're also missing fixes for:
https://github.com/pentaho/pentaho-platform/blob/master/extensions/src/org/pentaho/platform/plugin/services/pluginmgr/FileSystemXmlPluginProvider.java#L108
https://github.com/pentaho/pentaho-platform/blob/master/extensions/src/org/pentaho/platform/web/html/themes/PluginThemeResolver.java#L114
https://github.com/pentaho/pentaho-platform/blob/master/extensions/src/org/pentaho/platform/web/http/api/resources/FileResource.java#L2229-L2231

**Comment by YuryBY** [comment]
@mbatchelor, 
1)  FEATURE_SECURE_PROCESSING was changed in scope of http://jira.pentaho.com/browse/PPP-3453. If we need more properties set could you provide whole list?
2) XmlDom4JHelper.java was updated in scope of this PR: https://github.com/YuryBY/pentaho-platform/blob/48ef5df2e5ff6f5dbad53caf4790dc43c24907f2/core/src/org/pentaho/platform/util/xml/dom4j/XmlDom4JHelper.java#L114
3) FileSystemXmlPluginProvider.java#L108, PluginThemeResolver.java#L114, FileResource.java#L2229-L2231 - work in progress - will update the PR 
Thanks.

**Pull request merged**
