### PR TITLE
[SP-6576][PDI-20086] Backport to 10.2 Suite

### PR DESCRIPTION
**Pull request by ddiroma**

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 3m 30s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl extensions
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Consistent with the original code.

**Comment by buildguy** [comment]
### :x: Build failed in 2m 24s
Build command:
```console
mvn deploy -B -e -Daudit -U -Drelease -pl extensions
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 3m 8s
Build command:
```console
mvn deploy -B -e -Daudit -U -Drelease -pl extensions
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 42m 27s
Build command:
```console
mvn deploy -B -e -Daudit -U -Drelease -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1572**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5718/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
