### PR TITLE
[BISERVER-13916] Mondrian roles displaying errors with: Lorg.springframework.security.core.GrantedAuthority; cannot be cast to java.util.Collection

### PR DESCRIPTION
**Pull request by Advent51**
- type mismatch were fixed
- tests were fixed
- new tests were added

### CODE REVIEW

**Comment by Advent51** [comment]
@pedrofvteixeira @e-cuellar @rmansoor @mdamour1976 please review

**Comment by pamval** [comment]
@Advent51 Why is the drop in coverage so large? Do all the modules compile and run tests locally with your change?

**Comment by Advent51** [comment]
@pamval as I can see the coverage increased. Isn't it?
But we triggered wingman again to check it again.

**Comment by mchen-len-son** [comment]
wingman's report actually says the test coverage increased.
but I can't say for sure why. probably, due to fixed tests

**Pull request merged**
