### PR TITLE
[BISERVER-12637] - Ensuring all versions are purged when a file is de…

### PR DESCRIPTION
**Pull request by pentaho-nbaker**
…leted. This will ensure that the datastore references are cleaned on the next GC

### CODE REVIEW

**Comment by dkincade** [comment]
And way to add unit or integration tests to make sure this doesn't regress in the future?

**Comment by pentaho-nbaker** [comment]
Going to be an integration test. I can work on that, or try to help debug the pdi-client startup issue

**Comment by bkemper-pentaho** [comment]
What PDI Client startup issue?

Bob Kemper
Executive Vice President of Engineering
Pentaho, a Hitachi Data Systems company.
5950 Hazeltine National Dr.
Suite 340
Orlando, FL 32822
(407)-965-4019

[cid:9BD91647-026D-4D1A-88C7-275C05D88A4E]

**Comment by pentaho-nbaker** [comment]
Added unit test

**Comment by dkincade** [comment]
@rmansoor @tkafalas please take a look at this work as well...

**Comment by pentaho-nbaker** [comment]
I've found a problem with permanently deleting folders. The current code only works for files. Adjusting the code to handle this case.

**Pull request merged**
