### PR TITLE
[BISERVER-12815] - Manage Data Sources: User can import an .xmi using "Import Analysis"

### PR DESCRIPTION
**Pull request by andrei-viaryshka**
Updated version of https://github.com/pentaho/pentaho-platform/pull/2929.

### CODE REVIEW

**Comment by andrei-viaryshka** [comment]
@mdamour1976, @rmansoo, @e-cuellar, @pentaho-nbaker could you please review?

**Comment by pamval** [comment]
why the drop in coverage ? Specially for PentahoMetadataInformationMap ?

**Comment by lucboudreau** [comment]
Looks like a glitch. Says that the complexity of PentahoMetadataInformationMap has changed, even though the file was untouched. If I'd have to guess, I'd say that a test running on a background thread didn't have the time to mock an object before the main test class was canceled.

**Comment by pamval** [comment]
@rmansoor @e-cuellar can you take a look at this one ? Thanks!

**Comment by rmansoor** [comment]
@pamval looks good. Processing the PR now

**Comment by YuryBY** [comment]
@rmansoor @e-cuellar, @pamval here is another part of the fix: https://github.com/pentaho/data-access/pull/732#issuecomment-219391461. It should be also merged. Thanks.

**Pull request merged**
