### PR TITLE
[BISERVER-11747] While renaming folder with insufficient privileges o…

### PR DESCRIPTION
**Pull request by SergeyTravin**
…ccurs inconsistent behaviour.

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@pentaho-nbaker, @mdamour1976, @e-cuellar, review it please

**Comment by akhayrutdinov** [comment]
@pentaho-nbaker, @mdamour1976, @e-cuellar, review it please

**Comment by akhayrutdinov** [comment]
@rmansoor, you are welcomed as well

**Comment by akhayrutdinov** [comment]
@pentaho-nbaker, @rmansoor, @mdamour1976, @e-cuellar, review it please

**Comment by akhayrutdinov** [comment]
@pentaho-nbaker, @rmansoor, @mdamour1976, @e-cuellar, review it please

**Comment by pamval** [comment]
@rpbouman please review this pull request.

**Comment by akhayrutdinov** [comment]
@pentaho-nbaker, @rmansoor, @mdamour1976, @e-cuellar, review it please if you have time

**Pull request merged**
