### PR TITLE
[ANALYZER-3942] Add ability to set the locale via ProxyTrustingFilter

### PR DESCRIPTION
**Pull request by dcleao**
- `ProxyServlet`, `ProxyTrustingFilter` - send and receive the new `_TRUST_LOCALE_OVERRIDE_` argument
- `LocaleHelper.parseAndSetLocaleOverride` now accepts `null` or empty, simplifying some use cases
  - `Mantle.jsp`, `MantleDebug.jsp`, `HttpSessionPentahoSessionIntegrationFilter` - simplified to use the new interface of `LocaleHelper.parseAndSetLocaleOverride`

These changes allow CGG to request localized resources, via the `/i18n` service (the address of the platform's `LocalizationServlet`). The `/i18n` address is configured to allow being proxied/fetched from _localhost_ ([web.xml configuration of localhost](https://github.com/pentaho/pentaho-platform/blob/master/assemblies/pentaho-war/src/main/webapp/WEB-INF/web.xml#L86-L88) and [web.xml configuration of i18n](https://github.com/pentaho/pentaho-platform/blob/master/assemblies/pentaho-war/src/main/webapp/WEB-INF/web.xml#L127-L130)).

CGG is performing these HTTP requests to the server itself in [WebResourceLoader](https://github.com/webdetails/cgg/blob/master/pentaho/src/main/java/pt/webdetails/cgg/scripts/WebResourceLoader.java#L67-L69). See the corresponding proposed changes in the CGG PR: https://github.com/webdetails/cgg/pull/148.

CGG does not use the provided `ProxyServlet`. However, to maintain capability symmetry with `ProxyTrustingFilter`, I added the locale override capability to `ProxyServlet` as well. The new/improved integration tests test its use.

@bennychow please review.
/cc @jcarneirohv

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 39m 33s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,extensions,user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **2558**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4873/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 39m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,extensions,user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **2558**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4873/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 37m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,extensions,user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **2558**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4873/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 38m 53s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,extensions,user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **2558**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4873/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 39m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,extensions,user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **2558**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4873/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 38m 56s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,extensions,user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **2558**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4873/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by dcleao** [comment]
Ok, things finally seem good for Sonar Cube.

The exception is that of the [1 Security Hotspot](https://sonar.orl.eng.hitachivantara.com/security_hotspots?id=pentaho%3Apentaho-platform-ce-parent&pullRequest=4873), which I don't intend to address, as this was already there and is probably scattered throughout the Pentaho Server code.

I kept the changes I did to satisfy Sonar Cube in separate commits, so that you may ignore them and focus on the main changes.

Regarding the reported coverage, note that I added tests for all (if not all, almost all) paths of the `ProxyServlet` class, but these are made in integration tests, `ProxyServletIT`, which are not being taken into account by SonarCube. (out of curiosity, the `ProxyServletIT` class had a single **dummy** test case...).

**Review by bennychow — APPROVED** [review]
Looks good to me.  Glad we can now pass the locales through to the i18n service.  Interesting to note that Analyzer doesn't use this i18n service and maintains its own resource bundles.

**Comment by dcleao** [comment]
@bennychow Yes, the `/i18n` service is used only _indirectly_ by Analyzer, by the _plugged in_ visualizations. In Viz. API 2, stock visualizations consumed Analyzer's own `cv_catalog` strings, which we had long started passing to the CGG print script.
Thanks!

**Pull request merged**
