### PR TITLE
[BISERVER-12069] MdxBaseComponent forces all catalog URLs to start wi…

### PR DESCRIPTION
**Pull request by mchen-len-son**
…th http: or solution:

- added a unit test to increase the test coverage

### CODE REVIEW

**Comment by mchen-len-son** [comment]
@pamval 
to clarify what was changed:
at previous PR (#3008) the method coverage dropped, since I added two methods (factory methods for testing) not covered - thats why it had -10% method coverage drop.

here I simple covered one of the newly added methods. That gives us +5%

**Comment by pamval** [comment]
can we get the other 5%? :)

**Comment by mchen-len-son** [comment]
this is one line factory method. it's too simple to break.
I'm not sure if we should work on it.

**Comment by pamval** [comment]
ok, but the "too simple to break" will come back to bite you (it usually does).

**Pull request merged**
