### PR TITLE
[BISERVER-11359] Code changes to provide functionality to upload multiple files at once

### PR DESCRIPTION
**Pull request by SaiPrasannaL**

### CODE REVIEW

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 30m 56s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
extensions,user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **1572**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5591/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 55m 21s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
extensions,user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **1572**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5591/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by rmansoor — APPROVED** [review]

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 33m 13s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
extensions,user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **1573**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5591/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by tkafalas — APPROVED** [review]
My only concern, and maybe you have addressed this, is there is code at 187 of the old ImportDialog that looks to be replacing windows style "\" with linux style "/".  I see no replacement for this code and wonder if it will have side effects on Windows.

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 29m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
extensions,user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **1572**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5591/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
