### PR TITLE
[BISERVER-13533] - Remove old soap discovery UI

### PR DESCRIPTION
**Pull request by mbatchelor**

### CODE REVIEW

**Comment by mchen-len-son** [comment]
@mbatchelor could you please add JIRA number to the commit message?
thanks.

I missed that in a sibling PR #3420, my bad.

**Comment by mbatchelor** [comment]
@mchen-len-son - the commit message has the JIRA number in it - BISERVER-13533

**Comment by mchen-len-son** [comment]
@mbatchelor 
hmm, I see it in the PR title, but not in the commit message:
https://github.com/pentaho/pentaho-platform/pull/3430/commits

**Comment by mchen-len-son** [comment]
Also, please update the PR:
xml file is now located here:
pentaho-solutions/system/default-plugin/plugin.xml

**Comment by mbatchelor** [comment]
Everything changed due to mavenization. Closing.

**Pull request closed without merging**
