### PR TITLE
[SP-3189] Backport of BISERVER-13379 - Xaction Output Destination Fil…

### PR DESCRIPTION
**Pull request by ivanpogodin**
…e throws error on PUC it fails on / (slash) Separator but writes files folder (6.1 Suite)

cherry-pick:
        [BISERVER-13379] Xaction Output Destination File throws error on PUC it fails on / (slash) Separator but writes files folder
cherry-pick:
        [BISERVER-13379] Xaction Output Destination File throws error on PUC it fails on / (slash) Separator but writes files folder

### CODE REVIEW

**Comment by mbatchelor** [comment]
@ivanpogodin - please fix the checkstyle issues.

**Comment by ivanpogodin** [comment]
rebased on the top

**Comment by ivanpogodin** [comment]
@mbatchelor , @rmansoor , @pamval , @mchen-len-son , could you review it, please?
Compile errors look like class FileContentItem added in pentaho-platform\core is not available in pentaho-platform\extensions

**Comment by mchen-len-son** [comment]
Looks like a wingman issue - it only tries to run extensions module, whereas there are another changed modules.
Going to re-issue PR and to see if this helps.

**Pull request closed without merging**
