### PR TITLE
[BACKLOG-7784] PDI MapReduce jobs fail on "Mapper" part with "ClassNo…

### PR DESCRIPTION
**Pull request by pedrofvteixeira**
…tFoundException"

	- removed hard dependency on reporting engine extensions

### CODE REVIEW

**Comment by pedrofvteixeira** [comment]
@rmansoor , @CodeOnCoffee , @brosander please review

**Comment by brosander** [comment]
@pedrofvteixeira could you add a unit test asserting that disregardClassNames contains KettleDataFactoryModuleInitializer.class.getName()?

That way we'll have warning if a refactor is going to break this logic but no hard dependency in code

**Comment by pedrofvteixeira** [comment]
@brosander PR rebased: added unit test for default disregardClassNames and while I was on it, added one for default targetClassNames as well.

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/osgi/ExceptionBasedClientTypeProvider.java
  extensions/test-src/org/pentaho/platform/osgi/ExceptionBasedClientTypeProviderTest.java

Newly Fixed Tests:
======================
org.pentaho.platform.plugin.services.metadata.PentahoMetadataDomainRepositoryConcurrencyTest.addDomain_getDomain_Simultaneously:
-----------------------------------------------
junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: The following errors occurred: 
Expected not to find domain [domain_28], but got it
Expected not to find domain [domain_22], but got it
Expected not to find domain [domain_18], but got it

	at org.pentaho.platform.plugin.services.metadata.PentahoMetadataDomainRepositoryConcurrencyTest.runTest(PentahoMetadataDomainRepositoryConcurrencyTest.java:224)
	at org.pentaho.platform.plugin.services.metadata.PentahoMetadataDomainRepositoryConcurrencyTest.addDomain_getD
```

Unit test coverage change:
============
org.pentaho.platform.config.MondrianConfigProperties:
 * Branch Change :  + 7.14%
 * Instruction Change :  + 3.16%

org.pentaho.platform.osgi.ExceptionBasedClientTypeProvider:
 * Instruction Change : **-.08%**
 * Line Change :  + .33%

org.pentaho.platform.plugin.services.metadata.PentahoMetadataDomainRepository:
 * Branch Change :  + 1.25%
 * Complexity Change :  + .80%
 * Instruction Change :  + .93%
 * Line Change :  + .82%

Integration test coverage change:
============
org.pentaho.platform.plugin.action.chartbeans.ChartAction:
 * Instruction Change : **-.22%**

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/extensions/test-src/org/pentaho/platform/osgi/ExceptionBasedClientTypeProviderTest.java

1. Message: '(' is followed by whitespace. at Line: 69 Column: 20
2. Message: ')' is preceded with whitespace. at Line: 69 Column: 63
3. Message: '(' is followed by whitespace. at Line: 70 Column: 20
4. Message: ')' is preceded with whitespace. at Line: 70 Column: 63
5. Message: '(' is followed by whitespace. at Line: 77 Column: 20
6. Message: ')' is preceded with whitespace. at Line: 77 Column: 63
7. Message: '(' is followed by whitespace. at Line: 78 Column: 20
8. Message: ')' is preceded with whitespace. at Line: 78 Column: 63
9. Message: '(' is followed by whitespace. at Line: 80 Column: 20
10. Message: ')' is preceded with whitespace. at Line: 80 Column: 63

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/osgi/ExceptionBasedClientTypeProvider.java
  extensions/test-src/org/pentaho/platform/osgi/ExceptionBasedClientTypeProviderTest.java

Unit test coverage change:
============
org.pentaho.platform.config.MondrianConfigProperties:
 * Branch Change :  + 7.14%
 * Instruction Change :  + 3.16%

org.pentaho.platform.osgi.ExceptionBasedClientTypeProvider:
 * Instruction Change : **-.08%**
 * Line Change :  + .33%

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/osgi/ExceptionBasedClientTypeProvider.java
  extensions/test-src/org/pentaho/platform/osgi/ExceptionBasedClientTypeProviderTest.java

Unit test coverage change:
============
org.pentaho.platform.config.MondrianConfigProperties:
 * Branch Change :  + 7.14%
 * Instruction Change :  + 3.16%

org.pentaho.platform.osgi.ExceptionBasedClientTypeProvider:
 * Instruction Change : **-.08%**
 * Line Change :  + .33%

org.pentaho.platform.plugin.services.metadata.PentahoMetadataDomainRepository:
 * Branch Change :  + 1.25%
 * Complexity Change :  + .80%
 * Instruction Change :  + .93%
 * Line Change :  + .82%

org.pentaho.platform.web.http.PreAuthenticatedSessionHolder.new Runnable() {...}:
 * Branch Change :  + 25.00%
 * Complexity Change :  + 25.00%

**Pull request merged**
