### PR TITLE
[BISERVER-13184] IE8 - Empty UI after login to PUC

### PR DESCRIPTION
**Pull request by mchen-len-son**
added doctype adding to html generated by GWT to force IE9 and earlier using Standards Mode

### CODE REVIEW

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f user-console/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f user-console/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  user-console/build-res/subfloor-gwt.xml

**Comment by pamval** [comment]
@rfellows can you review this change ? 

I'm uncertain on whether we should add this to master, since it's IE8 specific. We definitely need it in 5.4 but I'm not sure about master.

**Comment by rfellows** [comment]
@pamval we shouldn't need this in master since we aren't going to be supporting IE8 or 9 in the next release.

I would be cautious with this change in general, however. Changing GWT-generated code to force standards-mode might cause other issues. There are cases elsewhere in the platform that where we had to force Quirks-mode for old browser support and standards mode would break it. If GWT is generating it this way, there may be a good/required reason for it. I'd make sure to fully regression test PUC after this change just to be sure.

Why did this problem just arise now? Did we upgrade GWT or something?

**Comment by pamval** [comment]
Good question. We know this broke in a 5.4 service pack so it's very unlikely that was due to a GWT upgrade. @mchen-len-son please investigate and try to figure out what changed in that service pack.

thanks!

**Comment by mchen-len-son** [comment]
Agreed.
Trying to figure out what really happened there.

**Pull request closed without merging**
