### PR TITLE
[SP-2774] Backport of BISERVER-13112 - Favourites and recents not bei…

### PR DESCRIPTION
**Pull request by ivanpogodin**
…ng listed since SP SP201602-6.0.1.2 applied (5.4 Suite)

pick [BISERVER-13112] Favourites and recents not being listed since SP SP201602-6.0.1.2 applied

### CODE REVIEW

**Comment by ivanpogodin** [comment]
@pamval , @rfellows , @pedrofvteixeira , could you review it, please.
This is a simple cherry-pick, The files are identical to the root case ( BISERVER-12717, https://github.com/pentaho/data-access/pull/763 )

**Comment by pamval** [comment]
@mchen-len-son when you can, please review this

**Comment by mchen-len-son** [comment]
Could not compile extensions' tests.
org.eclipse.jetty.util.ajax.JSON is unavailable in 5.4.

@ivanpogodin, I think we can remove the test data checking. it's not related to what we are testing here.

**Comment by ivanpogodin** [comment]
@mchen-len-son , 
org.mortbay.util.ajax.JSON is used instead of org.eclipse.jetty.util.ajax.JSON

**Pull request merged**
