### PR TITLE
[PPP-3547]-Pentaho Platform vulnerable to "Session Fixation Vulnerabi…

### PR DESCRIPTION
**Pull request by denisprotopopov**
…lity"

 - added preferences in applicationContext-spring-security.xml

### CODE REVIEW

**Comment by denisprotopopov** [comment]
@pamval please review the changes

**Comment by denisprotopopov** [comment]
@pamval please review the changes

**Comment by pamval** [comment]
@pedrofvteixeira can you please review this? Or ask someone from Rogue One to do so.

**Comment by pedrofvteixeira** [comment]
@denisprotopopov this only fixes session fixation for the "interactive" type of authentication; the non-interactive one ( think deep-linking content ) is still suffering with session fixation 

Try this: use the repro path outlined @ http://jira.pentaho.com/browse/PPP-3547?focusedCommentId=261959#comment-261959 , as the base repro path, but instead of 

 7 - Open a browser, and navigate to /Home (e.g. http://localhost:8080/pentaho/Home )

try:

 7 - Open a browser, and navigate to http://localhost:8080/pentaho/api/repos/%3Apublic%3ASteel Wheels%3ATop Customers (report).prpt/viewer

**Comment by denisprotopopov** [comment]
@pedrofvteixeira I made a new fix, can you please review this

**Comment by kolinus** [comment]
@pedrofvteixeira @pamval  could you please take a lokk

**Comment by pedrofvteixeira** [comment]
@denisprotopopov PR looks good to me.

@mbatchelor @CodeOnCoffee are we OK with yet another filter in the filterChain ? 
Would this mean we would need to include this a, on some future "Upgrade path from 7.0 to 7.1" ?

**Pull request merged**
