### PR TITLE
[PPP-4202] Service method should not be initializing all objects Plug…

### PR DESCRIPTION
**Pull request by sailingscally**
…inDispatchServlet and ServletToBeanProxy

@cravobranco @ricardosilva88

### CODE REVIEW

**Comment by pentaho-lmartins** [comment]
Hi @mbatchelor,

So the issue here, besides the instance variables not being thread safe, is the fact that the `doInit()` is being called in the service method when it should be done somewhere else.

The `init()` method already calls `doInit()` so is this call in the service method redundant? Does the J2EE framework call the public `init()` method? Should we explicitly call it in the constructor of the class?

I'm a bit lost here so I need a few additional pointers.

Thanks,
Luis

**Comment by buildguy** [comment]
### :gear: Build finished in 32m 34s with command:
```
mvn clean verify -f pom.xml -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -U -Dmaven-surefire-plugin.argLine=-XX:MaxRAMPercentage=90.0 -Dmaven-failsafe-plugin.argLine=-XX:MaxRAMPercentage=90.0 -pl extensions
```
### :warning: Failed Tests
---
#### :cloud_with_lightning_and_rain: 24 test(s) failed:
- **org.pentaho.platform.plugin.action.LocalActionInvokerTest.invokeActionTest**
```
    org/pentaho/platform/util/ActionUtil
```
- **org.pentaho.platform.plugin.action.LocalActionInvokerTest.invokeActionLocallyTest**
```
    org/pentaho/platform/util/ActionUtil
```
- **org.pentaho.platform.plugin.action.LocalActionInvokerTest.invokeActionLocallyWithNullsThrowsExceptionTest**
```
    Unexpected exception, expected<org.pentaho.platform.api.action.ActionInvocationException> but was<java.lang.NoClassDefFoundError>
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.testImportLocalizedPropertiesFiles_fr**
```
    org/pentaho/platform/api/engine/IPentahoRegistrableObjectFactory
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.testValidImportIndexLocaleFile**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.testInValidImportIndexLocaleFile**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.testImportNotLocaleFile**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.shouldNotFailAndReturnNullWhenMaliciousXmlIsGiven**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.shouldNotFailAndReturnNotNullWhenLegalXmlIsGiven**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.loadPropertiesByXmlTest**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.loadPropertiesByXmlReferenceToVariableInNameTest**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.loadPropertiesByXmlReferenceToVariableInDescriptionTest**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.loadPropertiesByXmlReferenceToVariablesTest**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.loadPropertiesByXmlWrongFormatTest**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.loadPropertiesByXmlInputStreamExceptionTest**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.loadPropertiesByXmlWrongTypeTest**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.testImportLocaleFiles**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.testImportDefaultPropertiesFiles**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.testImportLocalizedPropertiesFiles_en_us**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.testImportLocalizedPropertiesFiles_en_gb**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.testImportDefaultWithFileExtensionPropertiesFiles**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.testImportLocalizedWithFileExtensionPropertiesFiles_fr**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.testImportLocalizedWithFileExtensionPropertiesFiles_en_us**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
- **org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.testImportLocalizedWithFileExtensionPropertiesFiles_en_gb**
```
    Could not initialize class org.pentaho.platform.engine.core.system.PentahoSystem
```
  ---

|Total|Failed|Skipped|
|---|---|---|
|1460|24|1|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/2/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 23m 56s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl extensions
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1460|0|1|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/3/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 22m 33s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl extensions
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1460|0|1|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/4/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 23m 23s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl extensions
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1460|0|1|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/5/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 22m 29s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl extensions
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1461|0|1|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/6/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 22m 7s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl extensions
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1461|0|1|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/7/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 22m 24s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl extensions
```
### :warning: Failed Tests
---
#### :cloud_with_lightning_and_rain: 4 test(s) failed:
- **org.pentaho.platform.plugin.action.mondrian.catalog.MondrianCatalogHelperTest.testLoadCatalogsIntoCache**
```
    org/pentaho/platform/engine/core/system/PentahoSystem
```
- **org.pentaho.platform.plugin.action.mondrian.catalog.MondrianCatalogHelperTest.shouldNotFailAndReturnNotNullWhenLegalXmlIsGiven**
```
    org/pentaho/platform/util/xml/XMLParserFactoryProducer
```
- **org.pentaho.platform.plugin.action.mondrian.catalog.MondrianCatalogHelperTest.shouldNotFailAndReturnNullWhenMaliciousXmlIsGiven**
```
    Unexpected exception, expected<org.xml.sax.SAXException> but was<java.lang.NoClassDefFoundError>
```
- **org.pentaho.platform.web.http.api.resources.FileResourceTest.initializationError**
```
    Failed to transform class with name org.pentaho.platform.web.http.api.resources.FileResourceTest. Reason: cannot find org.pentaho.test.mock.MockPentahoUser
```
  ---

|Total|Failed|Skipped|
|---|---|---|
|1389|4|1|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/9/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 22m 25s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl extensions
```
### :warning: Failed Tests
---
#### :cloud_with_lightning_and_rain: 3 test(s) failed:
- **org.pentaho.platform.plugin.services.importer.NameBaseMimeResolverTest.testResolveMimeForBundle_with_defined_mime_type**
```
    org/pentaho/platform/api/repository2/unified/RepositoryFileAcl
```
- **org.pentaho.platform.plugin.services.importer.NameBaseMimeResolverTest.testResolveMimeForBundle_without_defined_mime_type**
```
    org/pentaho/platform/api/repository2/unified/RepositoryFileAcl
```
- **org.pentaho.platform.web.http.api.resources.operations.CopyFilesOperation_CopyTest.initializationError**
```
    Lorg/pentaho/platform/repository2/unified/webservices/DefaultUnifiedRepositoryWebService;
```
  ---

|Total|Failed|Skipped|
|---|---|---|
|1455|3|1|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/10/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 23m 25s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl extensions
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1467|0|1|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/11/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 23m 3s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl extensions
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1467|0|1|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/13/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 22m 7s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl extensions
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1467|0|1|

|[Details](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/14/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 21m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1465**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/15/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 32m 35s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 42 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.action.builtin.ActionSequenceActionTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/ObjectFactoryException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.action.mdx.MDXBaseComponentTest.shouldAddSolutionPrefixIfFileExistsInRepository</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/data/IDBDatasourceService
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.connections.sql.SQLResultSetTest.testGetDataColumn</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/ObjectFactoryException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.connections.sql.SQLResultSetTest.testGetColumnCountNativeNull</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/ObjectFactoryException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.connections.sql.SQLResultSetTest.testNext</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/ObjectFactoryException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.connections.sql.SQLResultSetTest.testPeek</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/ObjectFactoryException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.connections.sql.SQLResultSetTest.testGetRowCountNonScrolableNullResultSet</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/ObjectFactoryException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.connections.sql.SQLResultSetTest.testGetRowCountResultSetReturnRow</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/ObjectFactoryException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.connections.sql.SQLResultSetTest.testMemoryCopy_setMetadaQuery</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/ObjectFactoryException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.connections.sql.SQLResultSetTest.testMemoryCopy_setMetadaMemory</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/ObjectFactoryException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.connections.sql.SQLResultSetTest.testGetValueAt</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/ObjectFactoryException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.connections.sql.SQLResultSetTest.testMemoryCopy</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/ObjectFactoryException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.connections.sql.SQLResultSetTest.testDispose</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/ObjectFactoryException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.connections.sql.SQLResultSetTest.testGetRowCount</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/ObjectFactoryException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.connections.sql.SQLResultSetTest.testGetColumnCount</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/ObjectFactoryException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.connections.sql.SQLResultSetTest.testGetRowCountResultSetReturn0</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/ObjectFactoryException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.connections.sql.SQLResultSetTest.testGetDataRow</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/ObjectFactoryException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.connections.sql.SQLResultSetTest.testGetValueAtNullResultSet</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/ObjectFactoryException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.LocaleFilesProcessorTest.isXMLLocaleWrongFormatTest</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/mimetype/IPlatformMimeResolver
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.LocaleFilesProcessorTest.isXMLLocaleTest</b> (click to expand)</summary><p>

```
org/pentaho/platform/plugin/services/importer/NameBaseMimeResolver
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.LocaleFilesProcessorTest.testProcessLocaleFilesTwoLocaleFiles</b> (click to expand)</summary><p>

```
org/pentaho/platform/plugin/services/importer/NameBaseMimeResolver
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.LocaleFilesProcessorTest.isXMLLocaleEmptyValuesTest</b> (click to expand)</summary><p>

```
org/pentaho/platform/plugin/services/importer/NameBaseMimeResolver
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.LocaleFilesProcessorTest.testProcessLocaleFilesIgnoreProperties</b> (click to expand)</summary><p>

```
org/pentaho/platform/plugin/services/importer/NameBaseMimeResolver
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.LocaleFilesProcessorTest.testProcessLocaleFilesDontIgnoreProperties</b> (click to expand)</summary><p>

```
org/pentaho/platform/plugin/services/importer/NameBaseMimeResolver
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.LocaleImportHandlerTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/mimetype/IMimeType
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.MondrianImportHandlerTest.initializationError</b> (click to expand)</summary><p>

```
Lorg/pentaho/platform/api/repository2/unified/IPlatformImportBundle;
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.SolutionImportHandlerTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/repository2/unified/RepositoryFile
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importexport.BaseExportProcessorTest.testAddExportHandler</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/repository2/unified/RepositoryFile
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importexport.CommandLineProcessorTest.org.pentaho.platform.plugin.services.importexport.CommandLineProcessorTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.metadata.PentahoMetadataDomainRepositoryTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/metadata/repository/DomainStorageException
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.metadata.SessionCachingMetadataDomainRepositoryTest.testStoreAnnotationsXml</b> (click to expand)</summary><p>

```
org/pentaho/metadata/util/XmiParser
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.metadata.SessionCachingMetadataDomainRepositoryTest.testLoadAnnotationsXml</b> (click to expand)</summary><p>

```
org/pentaho/metadata/util/XmiParser
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.olap.OlapServiceImplTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/IPentahoSession
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.api.resources.RepositoryImportResourceTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/ObjectFactoryException
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.api.resources.RepositoryResourceTest.initializationError</b> (click to expand)</summary><p>

```
Failed to transform class with name org.pentaho.platform.web.http.api.resources.FileResource. Reason: cannot find org.pentaho.platform.api.repository2.unified.RepositoryFile
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.api.resources.UserSettingsResourceTest.initializationError</b> (click to expand)</summary><p>

```
Lorg/pentaho/platform/api/usersettings/IUserSettingService;
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.filters.RequestIdFilterTest.testRequestFilterNoIdProvided</b> (click to expand)</summary><p>

```
org/pentaho/platform/util/RequestIdUtil
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.filters.RequestIdFilterTest.testRequestFilterIdProvided</b> (click to expand)</summary><p>

```
org/pentaho/platform/util/RequestIdUtil
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.security.CsrfGateFilterTest.initializationError</b> (click to expand)</summary><p>

```
Failed to transform class with name org.pentaho.platform.engine.core.system.PentahoSystem. Reason: by javassist.bytecode.BadBytecode: sessionStartup (Lorg/pentaho/platform/api/engine/IPentahoSession;Lorg/pentaho/platform/api/engine/IParameterProvider;)V in org.pentaho.platform.engine.core.system.PentahoSystem: failed to resolve types
```

</p></details>

<details><summary><b>org.pentaho.platform.web.servlet.PluggableUploadFileServletTest.testXSSUsingPathInfo</b> (click to expand)</summary><p>

```
org/pentaho/platform/engine/core/system/PentahoSystem
```

</p></details>

<details><summary><b>org.pentaho.platform.web.servlet.UploadFileUtilsTest.testCheckExtensions</b> (click to expand)</summary><p>

```
org/pentaho/platform/engine/core/system/StandaloneApplicationContext
```

</p></details>

<details><summary><b>org.pentaho.platform.web.servlet.UploadFileUtilsTest.testGetAllExtensions</b> (click to expand)</summary><p>

```
org/pentaho/platform/engine/core/system/StandaloneApplicationContext
```

</p></details>

  
Tests run: **1382**, Failures: **42**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/16/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 22m 1s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1465**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/17/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 22m 25s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1465**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/18/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 21m 41s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1470**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/19/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 22m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1470**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/20/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 22m 18s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1470**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/21/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 22m 30s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1470**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/22/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 22m 14s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1470**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/23/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 22m 33s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1470**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/24/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 22m 33s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1470**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/25/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 22m 9s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1470**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/26/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 21m 56s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1470**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/27/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 21m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1470**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/28/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 23m 13s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1470**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/29/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 23m 8s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1470**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/30/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 22m 47s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1470**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/31/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 20m 53s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1470**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/32/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 2m 32s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 35m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1470**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 57s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 25m 10s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1489**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4260/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 48s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 18m
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Pull request closed without merging**
