### PR TITLE
[SP-6561] Backport of BISERVER-15087 - Issue using the “Execute Now” Option for scheduling with Ignore daylight saving adjustment (Use 24-hour interval) checked. (9.3 Suite)

### PR DESCRIPTION
**Pull request by smmribeiro**
Original commit: https://github.com/pentaho/pentaho-scheduler-plugin/commit/b3878768f7bbf9f7e3487c8686cb995053bb29f5

@pentaho/tatooine_dev

### CODE REVIEW

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 17m 30s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl scheduler
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 4 test(s) failed:

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsRunWhenNoBlockout</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsBlockedDuringABlockout</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testMDCContext</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsRunWhenThereIsAnExceptionRetrievingTheBlockoutManager</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

  
Tests run: **56**, Failures: **4**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform-jdk11/job/PR-5719/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 1h 8m 25s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 4 test(s) failed:

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsRunWhenNoBlockout</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsBlockedDuringABlockout</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testMDCContext</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsRunWhenThereIsAnExceptionRetrievingTheBlockoutManager</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

  
Tests run: **2810**, Failures: **4**, Skipped: **3** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform-jdk11/job/PR-5719/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 17m 49s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl scheduler
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 4 test(s) failed:

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsRunWhenNoBlockout</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsBlockedDuringABlockout</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testMDCContext</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsRunWhenThereIsAnExceptionRetrievingTheBlockoutManager</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

  
Tests run: **56**, Failures: **4**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform-jdk11/job/PR-5719/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 4m 8s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl scheduler
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 4 test(s) failed:

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsRunWhenNoBlockout</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsBlockedDuringABlockout</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testMDCContext</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsRunWhenThereIsAnExceptionRetrievingTheBlockoutManager</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

  
Tests run: **56**, Failures: **4**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform-jdk11/job/PR-5719/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 9m 54s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl scheduler
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 4 test(s) failed:

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsRunWhenNoBlockout</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsBlockedDuringABlockout</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testMDCContext</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsRunWhenThereIsAnExceptionRetrievingTheBlockoutManager</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

  
Tests run: **56**, Failures: **4**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform-jdk11/job/PR-5719/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 13m 32s
Build command:
```console
mvn deploy dependency:tree -B -e -Daudit -U -Drelease -pl scheduler
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 4 test(s) failed:

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsRunWhenNoBlockout</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsBlockedDuringABlockout</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testMDCContext</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsRunWhenThereIsAnExceptionRetrievingTheBlockoutManager</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

  
Tests run: **56**, Failures: **4**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform-jdk11/job/PR-5719/7/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 23m 18s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl scheduler
```
---
:ok_hand: All tests passed!
 
Tests run: **56**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform-jdk11/job/PR-5719/8/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by joana-fb — APPROVED** [review]

**Pull request merged**
