### PR TITLE
[BACKLOG-7872] - Create JMeter script to execute import endpoint usin…

### PR DESCRIPTION
**Pull request by apratkin**
…g admin and non admin user

### CODE REVIEW

**Comment by apratkin** [comment]
@rmansoor could you please review?

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/import-export-file.xdash.zip
  extensions/import-export-jmeter.jmx

Unit test coverage change:
============
org.pentaho.platform.config.MondrianConfigProperties:
 * Branch Change : **-7.14%**
 * Instruction Change : **-3.16%**

org.pentaho.platform.plugin.services.metadata.PentahoMetadataDomainRepository:
 * Branch Change : **-1.25%**
 * Complexity Change : **-.80%**
 * Instruction Change : **-.93%**
 * Line Change : **-.82%**

**Comment by apratkin** [comment]
@pedrofvteixeira could you please review?

**Comment by pedrofvteixeira** [comment]
Aliaksandr, all jmeter tests are running fine. 
I would ask you to simply update this jmeter file (i.e. this PR) with the happy paths **enabled** ( currently those have been set as disabled, only the negative tests being enabled ). 

Once you address this I'm good with merging this PR. Thanks!

**Pull request merged**
