### PR TITLE
[BACKLOG-36949] Page Zoom (AA) - Browse Files - Select Folder - Upload File

### PR DESCRIPTION
**Pull request by varuntangirala**
@pentaho/wcag Please review

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 11m 9s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5232/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by dcleao** [comment]
To be merged with: https://github.com/pentaho/pentaho-commons-gwt-modules/pull/848

**Review by dcleao — CHANGES_REQUESTED** [review]
Looks good.
I know it is using DialogMinimumHeightCategory.CONTENT due to a base issue with the outer vertical scrollbar being displayed "too soon", and which we can change later, if fixed.

Otherwise, I don't think that you have handled the Resize Text issues which should exist. Please, confirm.
1. It's using

**Comment by buildguy** [comment]
### :x: Build failed in 1m 2s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 52s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by dcleao** [comment]
Build failing for unrelated issue.

**Pull request merged**
