### PR TITLE
[CLEANUP] Cleanup for BACKLOG-17100: Trimmed the work item status log…

### PR DESCRIPTION
**Pull request by pentaho-mzur**
… message to only the interesting pieces and cleaned up lifecycle phase enum.

Verified changes of PR #3688 (which was closed) with a minor refactoring/changes on that PR.

### CODE REVIEW

**Comment by pentaho-mzur** [comment]
@pentaho/rebelalliance @pentaho/rogueone

**Comment by pentaho-mzur** [comment]
Fixed the wingman test failure...please continue your review. Thanks.

**Comment by chiltonj** [comment]
Is the correct PR linked here? also checkstyle errors need fixing.

**Comment by pentaho-mzur** [comment]
Responding to the comment about the PR: yes it is linked, see at the top of the conversion: #3688

**Comment by pentaho-mzur** [comment]
This PR should be merged with it counterpart from ee: #1124 

https://github.com/pentaho/pentaho-platform-ee/pull/1124

**Pull request merged**
