### PR TITLE
[PDI-15058] - Read only install fix

### PR DESCRIPTION
**Pull request by brosander**
Removing config read test, adding property to tell Karaf to use working dir as parent cache dir

### CODE REVIEW

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/osgi/KarafBoot.java
  extensions/src/org/pentaho/platform/osgi/KarafInstance.java
  extensions/test-src/org/pentaho/platform/osgi/KarafInstanceTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File extensions/test-src/org/pentaho/platform/osgi/KarafInstanceTest.java
1. Message: Line has trailing spaces at Line: 49 Column: None
2. Message: Line has trailing spaces at Line: 58 Column: None
3. Message: '(' is not followed by whitespace. at Line: 82 Column: 33
4. Message: ')' is not preceded with whitespace. at Line: 82 Column: 36
5. Message: '(' is not followed by whitespace. at Line: 84 Column: 30
6. Message: ')' is not preceded with whitespace. at Line: 84 Column: 33
7. Message: Line has trailing spaces at Line: 95 Column: None







Still Broken Tests:
-----------------
org.pentaho.test.platform.web.http.api.RepositoryResourceIT.b3_HappyPath_GET_withMimeType: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: Response media type incorrect: expected:<application/pdf;[]charset=UTF-8> but was:<application/pdf;[ ]charset=UTF-8>
	at org.pentaho.test.platform.web.http.api.JerseyTestUtil.assertResponse(JerseyTestUtil.java:47)
	at org.pentaho.test.platform.web.http.api.RepositoryResourceIT.b3_HappyPath_GET_withMimeType(RepositoryResourceIT.java:364)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)

```

Unit test coverage change:
============
org.pentaho.platform.osgi.KarafBoot:
 * instructionPercentCoverageChange : +2.79%
 * branchPercentCoverageChange : +2.62%
 * linePercentCoverageChange : +1.92%
 * complexityPercentCoverageChange : +2.78%
    
org.pentaho.platform.osgi.KarafInstance.new FilenameFilter() {...}:
 * branchPercentCoverageChange : +10.00%
 * complexityPercentCoverageChange : +14.29%
    
org.pentaho.platform.osgi.KarafInstance:
 * instructionPercentCoverageChange : +0.69%
 * branchPercentCoverageChange : +2.20%
 * linePercentCoverageChange : +0.53%
 * complexityPercentCoverageChange : +2.29%
 * methodPercentCoverageChange : +0.98%
    
org.pentaho.platform.plugin.services.metadata.PentahoMetadataDomainRepository:
 * instructionPercentCoverageChange : +0.93%
 * branchPercentCoverageChange : +1.25%
 * linePercentCoverageChange : +0.82%
 * complexityPercentCoverageChange : +0.80%

**Comment by lucboudreau** [comment]
@brosander Can you fix ``AssertionFailedError`` while you are in there? It's just a missing space.

**Comment by brosander** [comment]
@lucboudreau deleted the wingman comment before seeing yours, I'll fix with separate pr once the pmr stuff gets in

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/osgi/KarafBoot.java
  extensions/src/org/pentaho/platform/osgi/KarafInstance.java
  extensions/test-src/org/pentaho/platform/osgi/KarafInstanceTest.java








Still Broken Tests:
-----------------
org.pentaho.test.platform.web.http.api.RepositoryResourceIT.b3_HappyPath_GET_withMimeType: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: Response media type incorrect: expected:<application/pdf;[]charset=UTF-8> but was:<application/pdf;[ ]charset=UTF-8>
	at org.pentaho.test.platform.web.http.api.JerseyTestUtil.assertResponse(JerseyTestUtil.java:47)
	at org.pentaho.test.platform.web.http.api.RepositoryResourceIT.b3_HappyPath_GET_withMimeType(RepositoryResourceIT.java:364)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)

```

Unit test coverage change:
============
org.pentaho.platform.osgi.KarafBoot:
 * instructionPercentCoverageChange : +2.79%
 * branchPercentCoverageChange : +2.62%
 * linePercentCoverageChange : +1.92%
 * complexityPercentCoverageChange : +2.78%
    
org.pentaho.platform.config.MondrianConfigProperties:
 * instructionPercentCoverageChange : +3.16%
 * branchPercentCoverageChange : +7.14%
    
org.pentaho.platform.osgi.KarafInstance.new FilenameFilter() {...}:
 * branchPercentCoverageChange : +10.00%
 * complexityPercentCoverageChange : +14.29%
    
org.pentaho.platform.osgi.KarafInstance:
 * instructionPercentCoverageChange : +0.69%
 * branchPercentCoverageChange : +2.20%
 * linePercentCoverageChange : +0.53%
 * complexityPercentCoverageChange : +2.29%
 * methodPercentCoverageChange : +0.98%
    
org.pentaho.platform.plugin.services.metadata.PentahoMetadataDomainRepository:
 * instructionPercentCoverageChange :**-0.93%**
 * branchPercentCoverageChange :**-1.25%**
 * linePercentCoverageChange :**-0.82%**
 * complexityPercentCoverageChange :**-0.80%**

**Pull request merged**
