### PR TITLE
[SP-1900][BISERVER-12570] - Regression: Impossible to see folder prop…

### PR DESCRIPTION
**Pull request by SergeyTravin**
…erties after selection one of the file file from this folder

### CODE REVIEW

**Comment by SergeyTravin** [comment]
@mdamour1976, @rmansoor, @e-cuellar, @mdamour1976, @pentaho-nbaker Could you review it? please? It is backport for https://github.com/pentaho/pentaho-platform/pull/2331

**Comment by SergeyTravin** [comment]
@mdamour1976, @rmansoor, @e-cuellar, @mdamour1976, @pentaho-nbaker 
I would be grateful if you could review the PR before end of the July SP.

**Comment by SergeyTravin** [comment]
@rmansoor, @e-cuellar, @mdamour1976, @pentaho-nbaker 
I would be grateful if you could review the PR before end of the July SP (6.26.2015)

**Comment by rmansoor** [comment]
working properly now

**Pull request merged**
