### PR TITLE
[BISERVER-13722]-Error assigning role permissions through API under JDBC authetication

### PR DESCRIPTION
**Pull request by stepanovdg**

### CODE REVIEW

**Comment by stepanovdg** [comment]
@mdamour1976 @rmansoor @pteixeira Could you please take a look?

**Comment by pteixeira** [comment]
@stepanovdg Hello! Sorry to barge in, but you are tagging the wrong Pedro :D

Cheers!

**Comment by stepanovdg** [comment]
@pteixeira  Hi! Sorry for that.

**Comment by duarteteixeira** [comment]
@pedrofvteixeira please review

**Pull request merged**
