### PR TITLE
[BISERVER-12506] - Folder creation: reserved character validation is only being done client-side

### PR DESCRIPTION
**Pull request by akhayrutdinov**
- introduce new method in FileService with validation of input path
- change FileResource and DirectoryResource to use it
- extract common procedure for validation
- add tests
- fix Checkstyle violations for all affected classes and make some cleanup

@pentaho-nbaker, @rmansoor, review it please

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@pentaho-nbaker, @rmansoor, review it please

**Comment by akhayrutdinov** [comment]
@pentaho-nbaker, @rmansoor, review it please
/cc @pamval

**Comment by akhayrutdinov** [comment]
@pentaho-nbaker, @rmansoor, review it please

**Comment by rmansoor** [comment]
@akhayrutdinov in process of validating this pull request. Will process as soon as it passes the test

**Comment by rmansoor** [comment]
@akhayrutdinov I can still create a folder using a/b
$.ajax({ type:'PUT', url:'http://localhost:8080/pentaho/api/repo/dirs/:home:admin:a/b' });	
Is the code suppose to fix this as well ?

**Comment by akhayrutdinov** [comment]
@rmansoor, thanks for noticing it!
I've updated the PR with guard conditions and two more test cases (for `/` and `\`)

**Comment by rmansoor** [comment]
@akhayrutdinov everything is looking good. processing the pull request now

**Pull request merged**
