### PR TITLE
[BACKLOG-37324] - JS changes for Listox implementation.

### PR DESCRIPTION
**Pull request by phalguni-a**
@pentaho/wcag , Please review.

Merge with - https://github.com/pentaho/pentaho-commons-gwt-modules/pull/888

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 13m
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5278/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by dcleao — COMMENTED** [review]
Looks good. My only question is if the file icons still scale well in the face of Text Zoom.

**Comment by phalguni-a** [comment]
> Looks good. My only question is if the file icons still scale well in the face of Text Zoom.

I did test that. It looks like below right now. But, still I think it needs to be tested and few things should be fixed. (Already discussed with Sourav about TZ)

image

**Comment by dcleao** [comment]
@phalguni-a Ok, so will a follow-up story be created or will it be fixed in a follow-up PR for this same story?

**Comment by phalguni-a** [comment]
@dcleao - Sure. Same story can be used and follow-up PRs be created as required.

**Review by dcleao — APPROVED** [review]

**Review by soagarwal1 — APPROVED** [review]

**Pull request merged**
