### PR TITLE
[BISERVER-11812] - BA Server is telling browser to request content us…

### PR DESCRIPTION
**Pull request by aliakseihaidukou**
…ing http even when using an Apache+SSL as reverse proxy.

fix brightcove video player (Welcome and Tutorials tabs)
@rmansoor @dkincade @kcruzada please review

### CODE REVIEW

**Comment by rmansoor** [comment]
@aliakseihaidukou I tried to test this on my end but it still does not bring the brightcoveExperience.js is not being retrieved from the update url. Can you tell me how did you test this one

**Comment by aliakseihaidukou** [comment]
@rmansoor I used apache ssl engine for testing. After I removed "http" the brightcoveExperience.js url was using parent's page protocol. And secureConnections parameter told the plugin to use https for content stream.

**Comment by rmansoor** [comment]
The issue here is that we need to use a different url
in case of http the url is 
http://admin.brightcove.com/js/BrightcoveExperiences.js

for https
https://sadmin.brightcove.com/js/BrightcoveExperiences.js

**Comment by aliakseihaidukou** [comment]
oh, you are right! It works with "https://admin...", but with incorrect ssl certificate. I'll fix now.

**Comment by kcruzada** [comment]
@aliakseihaidukou I'm closing this pull request... please re-open when you have your fix.

**Pull request closed without merging**
