### PR TITLE
CLEANUP - fix failed test

### PR DESCRIPTION
**Pull request by SergeyTravin**

### CODE REVIEW

**Comment by SergeyTravin** [comment]
@rmansoor, @pedrofvteixeira  could you review it please?

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  core/test-res/solution/test/ActionDelegateTest/testIndexedInputs.xaction
  core/test-src/org/pentaho/platform/engine/services/actions/ActionDelegateTest.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestAllIOAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestDefinitionPreProcessingAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestIndexedInputsAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestLoggingSessionAwareAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestStreamingAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestVarArgsAction.java

Newly Fixed Tests:
======================
org.pentaho.platform.engine.services.actions.ActionDelegateTest.testIndexedInputs:
-----------------------------------------------
org.pentaho.platform.api.engine.ActionSequenceException
```
org.pentaho.platform.api.engine.ActionSequenceException: Action sequence failed!
	at org.pentaho.platform.engine.services.actions.ActionDelegateTest.execute(ActionDelegateTest.java:477)
	at org.pentaho.platform.engine.services.actions.ActionDelegateTest.execute(ActionDelegateTest.java:441)
	at org.pentaho.platform.engine.services.actions.ActionDelegateTest.testIndexedInputs(ActionDelegateTest.java:144)

```

Unit test coverage change:
============
org.pentaho.platform.engine.services.actionsequence.ActionParameter:
 * Branch Change :  + 1.11%
 * Complexity Change :  + 1.37%
 * Instruction Change :  + .50%

org.pentaho.platform.engine.services.PentahoMessenger:
 * Branch Change : **-1.56%**
 * Complexity Change : **-2.04%**

org.pentaho.platform.engine.services.runtime.RuntimeContext:
 * Branch Change : **-.22%**
 * Complexity Change : **-.31%**

org.pentaho.platform.engine.services.solution.ActionDelegate:
 * Complexity Change :  + 3.23%
 * Instruction Change :  + 5.95%
 * Line Change :  + 3.90%
 * Method Change :  + 10.00%

org.pentaho.platform.engine.services.solution.ActionDelegate.InputErrorCallback:
 * Branch Change : **-16.67%**
 * Complexity Change : **-14.29%**
 * Instruction Change : **-6.82%**
 * Line Change : **-18.18%**
 * Method Change : **-25.00%**

org.pentaho.platform.engine.services.solution.ActionDelegate.ResourceCallback:
 * Branch Change : **-25.00%**
 * Complexity Change : **-20.00%**
 * Instruction Change : **-8.00%**
 * Line Change : **-25.00%**
 * Method Change : **-33.33%**

org.pentaho.platform.engine.services.solution.ActionDelegate.StreamOutputErrorCallback:
 * Instruction Change :  + 36.76%
 * Line Change :  + 25.00%

org.pentaho.platform.util.beans.AlternateIndexFormatter:
 * Branch Change : **-50.00%**
 * Complexity Change : **-33.33%**
 * Instruction Change : **-67.44%**
 * Line Change : **-45.45%**

org.pentaho.platform.util.beans.BeanUtil:
 * Branch Change : **-8.33%**
 * Complexity Change : **-3.85%**
 * Instruction Change : **-2.37%**

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/core/test-src/org/pentaho/platform/engine/services/actions/ActionDelegateTest.java

1. Message: ',' is preceded with whitespace. at Line: 143 Column: 106

**Comment by pedrofvteixeira** [comment]
@SergeyTravin please address checkstyle violations; in addition, unit test coverage for ActionDelegate and AlternateIndexFormatter has dropped significantly

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  core/src/org/pentaho/platform/util/beans/AlternateIndexFormatter.java
  core/test-res/solution/test/ActionDelegateTest/testIndexedInputs.xaction
  core/test-res/solution/test/ActionDelegateTest/testUnsupportedInputs.xaction
  core/test-src/org/pentaho/platform/engine/services/actions/ActionDelegateTest.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestAllIOAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestDefinitionPreProcessingAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestIndexedInputsAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestLoggingSessionAwareAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestStreamingAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestUnsupportedInputs.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestVarArgsAction.java
  core/test-src/org/pentaho/platform/util/beans/AlternateIndexFormatterTest.java

Newly Fixed Tests:
======================
org.pentaho.platform.engine.services.actions.ActionDelegateTest.testIndexedInputs:
-----------------------------------------------
org.pentaho.platform.api.engine.ActionSequenceException
```
org.pentaho.platform.api.engine.ActionSequenceException: Action sequence failed!
	at org.pentaho.platform.engine.services.actions.ActionDelegateTest.execute(ActionDelegateTest.java:477)
	at org.pentaho.platform.engine.services.actions.ActionDelegateTest.execute(ActionDelegateTest.java:441)
	at org.pentaho.platform.engine.services.actions.ActionDelegateTest.testIndexedInputs(ActionDelegateTest.java:144)

```

Unit test coverage change:
============
org.pentaho.platform.engine.services.actionsequence.ActionParameter:
 * Branch Change :  + 1.11%
 * Complexity Change :  + 1.37%
 * Instruction Change :  + .50%

org.pentaho.platform.engine.services.PentahoMessenger:
 * Branch Change : **-1.56%**
 * Complexity Change : **-2.04%**

org.pentaho.platform.engine.services.runtime.RuntimeContext:
 * Branch Change : **-.22%**
 * Complexity Change : **-.31%**

org.pentaho.platform.engine.services.solution.ActionDelegate:
 * Complexity Change :  + 3.23%
 * Instruction Change :  + 5.95%
 * Line Change :  + 3.90%
 * Method Change :  + 10.00%

org.pentaho.platform.engine.services.solution.ActionDelegate.InputErrorCallback:
 * Branch Change : **-16.67%**
 * Complexity Change : **-14.29%**
 * Instruction Change : **-6.82%**
 * Line Change : **-18.18%**
 * Method Change : **-25.00%**

org.pentaho.platform.engine.services.solution.ActionDelegate.ResourceCallback:
 * Branch Change : **-25.00%**
 * Complexity Change : **-20.00%**
 * Instruction Change : **-8.00%**
 * Line Change : **-25.00%**
 * Method Change : **-33.33%**

org.pentaho.platform.engine.services.solution.ActionDelegate.StreamOutputErrorCallback:
 * Instruction Change :  + 36.76%
 * Line Change :  + 25.00%

org.pentaho.platform.util.beans.AlternateIndexFormatter:
 * Instruction Change :  + 2.33%
 * Line Change :  + 9.09%

org.pentaho.platform.util.beans.BeanUtil:
 * Branch Change : **-8.33%**
 * Complexity Change : **-3.85%**
 * Instruction Change : **-2.37%**

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  core/src/org/pentaho/platform/util/beans/AlternateIndexFormatter.java
  core/test-res/solution/test/ActionDelegateTest/testIndexedInputs.xaction
  core/test-res/solution/test/ActionDelegateTest/testInputErrorCallbackFailedToSet.xaction
  core/test-res/solution/test/ActionDelegateTest/testInputErrorCallbackNotWritable.xaction
  core/test-src/org/pentaho/platform/engine/services/actions/ActionDelegateTest.java
  core/test-src/org/pentaho/platform/engine/services/actions/InputErrorCallbackFailedToSet.java
  core/test-src/org/pentaho/platform/engine/services/actions/InputErrorCallbackNotWritable.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestAllIOAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestDefinitionPreProcessingAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestIndexedInputsAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestLoggingSessionAwareAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestStreamingAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestVarArgsAction.java
  core/test-src/org/pentaho/platform/util/beans/AlternateIndexFormatterTest.java

Newly Fixed Tests:
======================
org.pentaho.platform.engine.services.actions.ActionDelegateTest.testIndexedInputs:
-----------------------------------------------
org.pentaho.platform.api.engine.ActionSequenceException
```
org.pentaho.platform.api.engine.ActionSequenceException: Action sequence failed!
	at org.pentaho.platform.engine.services.actions.ActionDelegateTest.execute(ActionDelegateTest.java:477)
	at org.pentaho.platform.engine.services.actions.ActionDelegateTest.execute(ActionDelegateTest.java:441)
	at org.pentaho.platform.engine.services.actions.ActionDelegateTest.testIndexedInputs(ActionDelegateTest.java:144)

```

Unit test coverage change:
============
org.pentaho.platform.engine.security.event.OrderedApplicationEventMulticaster.new Comparator() {...}:
 * Branch Change : **-12.50%**
 * Complexity Change : **-16.67%**
 * Instruction Change : **-6.25%**
 * Line Change : **-12.50%**

org.pentaho.platform.engine.services.actionsequence.ActionParameter:
 * Branch Change :  + 1.11%
 * Complexity Change :  + 1.37%
 * Instruction Change :  + .50%

org.pentaho.platform.engine.services.PentahoMessenger:
 * Branch Change : **-1.56%**
 * Complexity Change : **-2.04%**

org.pentaho.platform.engine.services.runtime.RuntimeContext:
 * Branch Change : **-.22%**
 * Complexity Change : **-.31%**

org.pentaho.platform.engine.services.solution.ActionDelegate:
 * Complexity Change :  + 3.23%
 * Instruction Change :  + 5.95%
 * Line Change :  + 3.90%
 * Method Change :  + 10.00%

org.pentaho.platform.engine.services.solution.ActionDelegate.InputErrorCallback:
 * Branch Change :  + 16.67%
 * Instruction Change :  + 36.36%
 * Line Change :  + 27.27%

org.pentaho.platform.engine.services.solution.ActionDelegate.ResourceCallback:
 * Branch Change : **-25.00%**
 * Complexity Change : **-20.00%**
 * Instruction Change : **-8.00%**
 * Line Change : **-25.00%**
 * Method Change : **-33.33%**

org.pentaho.platform.engine.services.solution.ActionDelegate.StreamOutputErrorCallback:
 * Instruction Change :  + 36.76%
 * Line Change :  + 25.00%

org.pentaho.platform.util.beans.AlternateIndexFormatter:
 * Instruction Change :  + 2.33%
 * Line Change :  + 9.09%

org.pentaho.platform.util.beans.BeanUtil:
 * Branch Change : **-8.33%**
 * Complexity Change : **-3.85%**
 * Instruction Change : **-2.37%**

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/core/test-src/org/pentaho/platform/engine/services/actions/InputErrorCallbackNotWritable.java

1. Message: Line has trailing spaces at Line: 29
2. Message: Line has trailing spaces at Line: 32
3. Message: Line has trailing spaces at Line: 48

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  core/src/org/pentaho/platform/util/beans/AlternateIndexFormatter.java
  core/test-res/solution/test/ActionDelegateTest/testIndexedInputs.xaction
  core/test-res/solution/test/ActionDelegateTest/testInputErrorCallbackFailedToSet.xaction
  core/test-res/solution/test/ActionDelegateTest/testInputErrorCallbackNotWritable.xaction
  core/test-res/solution/test/ActionDelegateTest/testResourceCallbackNotWritable.xaction
  core/test-src/org/pentaho/platform/engine/services/actions/ActionDelegateTest.java
  core/test-src/org/pentaho/platform/engine/services/actions/InputErrorCallbackFailedToSet.java
  core/test-src/org/pentaho/platform/engine/services/actions/InputErrorCallbackNotWritable.java
  core/test-src/org/pentaho/platform/engine/services/actions/ResourceCallbackNotWritable.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestAllIOAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestDefinitionPreProcessingAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestIndexedInputsAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestLoggingSessionAwareAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestStreamingAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestVarArgsAction.java
  core/test-src/org/pentaho/platform/util/beans/AlternateIndexFormatterTest.java

Newly Fixed Tests:
======================
org.pentaho.platform.engine.services.actions.ActionDelegateTest.testIndexedInputs:
-----------------------------------------------
org.pentaho.platform.api.engine.ActionSequenceException
```
org.pentaho.platform.api.engine.ActionSequenceException: Action sequence failed!
	at org.pentaho.platform.engine.services.actions.ActionDelegateTest.execute(ActionDelegateTest.java:477)
	at org.pentaho.platform.engine.services.actions.ActionDelegateTest.execute(ActionDelegateTest.java:441)
	at org.pentaho.platform.engine.services.actions.ActionDelegateTest.testIndexedInputs(ActionDelegateTest.java:144)

```

Unit test coverage change:
============
org.pentaho.platform.engine.services.actionsequence.ActionParameter:
 * Branch Change :  + 1.11%
 * Complexity Change :  + 1.37%
 * Instruction Change :  + .50%

org.pentaho.platform.engine.services.PentahoMessenger:
 * Branch Change : **-1.56%**
 * Complexity Change : **-2.04%**

org.pentaho.platform.engine.services.runtime.RuntimeContext:
 * Branch Change : **-.22%**
 * Complexity Change : **-.31%**

org.pentaho.platform.engine.services.solution.ActionDelegate:
 * Complexity Change :  + 3.23%
 * Instruction Change :  + 5.95%
 * Line Change :  + 3.90%
 * Method Change :  + 10.00%

org.pentaho.platform.engine.services.solution.ActionDelegate.InputErrorCallback:
 * Branch Change :  + 16.67%
 * Instruction Change :  + 36.36%
 * Line Change :  + 27.27%

org.pentaho.platform.engine.services.solution.ActionDelegate.ResourceCallback:
 * Instruction Change :  + 33.33%
 * Line Change :  + 25.00%

org.pentaho.platform.engine.services.solution.ActionDelegate.StreamOutputErrorCallback:
 * Instruction Change :  + 36.76%
 * Line Change :  + 25.00%

org.pentaho.platform.util.beans.AlternateIndexFormatter:
 * Instruction Change :  + 2.33%
 * Line Change :  + 9.09%

org.pentaho.platform.util.beans.BeanUtil:
 * Branch Change : **-8.33%**
 * Complexity Change : **-3.85%**
 * Instruction Change : **-2.37%**

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/core/test-src/org/pentaho/platform/engine/services/actions/ActionDelegateTest.java

1. Message: Line has trailing spaces at Line: 353

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  core/src/org/pentaho/platform/util/beans/AlternateIndexFormatter.java
  core/test-res/solution/test/ActionDelegateTest/testIndexedInputs.xaction
  core/test-res/solution/test/ActionDelegateTest/testInputErrorCallbackFailedToSet.xaction
  core/test-res/solution/test/ActionDelegateTest/testInputErrorCallbackNotWritable.xaction
  core/test-res/solution/test/ActionDelegateTest/testResourceCallbackNotWritable.xaction
  core/test-src/org/pentaho/platform/engine/services/actions/ActionDelegateTest.java
  core/test-src/org/pentaho/platform/engine/services/actions/InputErrorCallbackFailedToSet.java
  core/test-src/org/pentaho/platform/engine/services/actions/InputErrorCallbackNotWritable.java
  core/test-src/org/pentaho/platform/engine/services/actions/ResourceCallbackNotWritable.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestAllIOAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestDefinitionPreProcessingAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestIndexedInputsAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestLoggingSessionAwareAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestStreamingAction.java
  core/test-src/org/pentaho/platform/engine/services/actions/TestVarArgsAction.java
  core/test-src/org/pentaho/platform/util/beans/AlternateIndexFormatterTest.java

Newly Fixed Tests:
======================
org.pentaho.platform.engine.services.actions.ActionDelegateTest.testIndexedInputs:
-----------------------------------------------
org.pentaho.platform.api.engine.ActionSequenceException
```
org.pentaho.platform.api.engine.ActionSequenceException: Action sequence failed!
	at org.pentaho.platform.engine.services.actions.ActionDelegateTest.execute(ActionDelegateTest.java:477)
	at org.pentaho.platform.engine.services.actions.ActionDelegateTest.execute(ActionDelegateTest.java:441)
	at org.pentaho.platform.engine.services.actions.ActionDelegateTest.testIndexedInputs(ActionDelegateTest.java:144)

```

Unit test coverage change:
============
org.pentaho.platform.engine.services.actionsequence.ActionParameter:
 * Branch Change :  + 1.11%
 * Complexity Change :  + 1.37%
 * Instruction Change :  + .50%

org.pentaho.platform.engine.services.PentahoMessenger:
 * Branch Change : **-1.56%**
 * Complexity Change : **-2.04%**

org.pentaho.platform.engine.services.runtime.RuntimeContext:
 * Branch Change : **-.22%**
 * Complexity Change : **-.31%**

org.pentaho.platform.engine.services.solution.ActionDelegate:
 * Complexity Change :  + 3.23%
 * Instruction Change :  + 5.95%
 * Line Change :  + 3.90%
 * Method Change :  + 10.00%

org.pentaho.platform.engine.services.solution.ActionDelegate.InputErrorCallback:
 * Branch Change :  + 16.67%
 * Instruction Change :  + 36.36%
 * Line Change :  + 27.27%

org.pentaho.platform.engine.services.solution.ActionDelegate.ResourceCallback:
 * Instruction Change :  + 33.33%
 * Line Change :  + 25.00%

org.pentaho.platform.engine.services.solution.ActionDelegate.StreamOutputErrorCallback:
 * Instruction Change :  + 36.76%
 * Line Change :  + 25.00%

org.pentaho.platform.util.beans.AlternateIndexFormatter:
 * Instruction Change :  + 2.33%
 * Line Change :  + 9.09%

org.pentaho.platform.util.beans.BeanUtil:
 * Branch Change : **-8.33%**
 * Complexity Change : **-3.85%**
 * Instruction Change : **-2.37%**

**Pull request merged**
