### PR TITLE
[BACKLOG-35002] Protecting GWT-RPC bridge against CSRF attacks

### PR DESCRIPTION
**Pull request by dcleao**
Depends on https://github.com/pentaho/pentaho-commons-gwt-modules/pull/795.

Part of the PR group https://github.com/pentaho/data-access/pull/1116.

@bennychow, @ddiroma please review. You might want to read the following first, for context.

### How these work and are currently implemented

There are currently three `Servlet` classes in the platform which take care of exposing GWT-RPC web-services. One common, abstract class, `AbstractGwtRpcProxyServlet`,  and two subclasses:
- `GwtRpcProxyServlet` — handles the **System** GWT-RPC web services, exposed under `/ws/gwt/*`;
- `GwtRpcPluginProxyServlet` — handles the **Plugins**' GWT-RPC web services, exposed under `/gwtrpc/*`.

which is transported in 
GWT-RPC web services use a custom serialization format in HTTP requests and responses. Specifically, the method name which is being called is not in the URL, but, instead, in the body of the HTTP request message.

These classes have the following main functions:

1. finding the _target/service object_ which will receive the remote call,
2. obtaining a _serialization policy_ which indicates the types which are allowed to be part of the request and response messages, and
3. setting up an appropriate "current" class loader for request message deserialization.

The target object is selected exclusively according to (the remainder of) the URL. It may be of any class, even of one which does not implement the interface that represents the service. The only requirement is that the methods which are _called remotely_ exist with same name and arguments — as in _duck typing_.

GWT supports a special serialization policy file format which contains the list of allowed classes. These files are generated automatically by the GWT compiler and placed besides the remaining compiled GWT resources (files with the `.gwt.rpc` extension).

The following describes the differences in the handling of System and Plugin web-services which justify the existence of the two sub-classes.

#### System web services

The path is mapped to a target bean which must be declared in `pentahoServices.spring.xml` (e.g. URL/Path: `ws/gwt/unifiedRepository`, Bean id.: `ws-gwt-unifiedRepository`).

The serialization policies are accepted only as standard policy files present in the Pentaho web app's `pentaho/mantle` folder. The classes present in the policy files must exist in the main class-loader. The code that deserializes request messages must execute having the main class-loader as _current_ in the current thread.

#### Plugin web services

The path is mapped to a target object which is declared in a plugin's `plugin.xml` file, via the special `<webservice type="gwt" id="serviceName" ... />` element.

The serialization policies can be provided as an explicit plugin bean of type `SerializationPolicy`, or by standard GWT serialization policy files, present anywhere within the plugin's "file system". The classes present in the serialization policy files must exist in the **plugin's** class-loader. The code that deserializes request messages must execute having the **plugin's** class-loader as current in the current thread.

### Adding CSRF protection

Protecting these services against CSRF would be straight forward if, like normal REST or SOAP services, the _service method_ being called was somehow indicated in the URL. The existing request matchers could then be used to configure security for the URLs of specific methods of a service.

Unfortunately, given that the _service method_ of the remote call is only present in the encoded body of the HTTP request, special request matcher classes had to be developed that know how to deserialize GWT-RPC bodies and test for the service method, for both the System and Plugins cases. Additionally, care had to be taken to minimize the harm to performance.

A new class, `AbstractGwtRpc`, was defined that represents a single remote service call, and which is associated with a single `HttpServletRequest` instance, from which the call is deserialized. The same GWT-RPC instance which is used by the request matcher, which is evaluated within the `CsrfGateFilter` filter, is used by the corresponding GWT-RPC servlet (`AbstractGwtRpcProxyServlet`) instance. Thus, the request is only deserialized once. The GWT-RPC instance is stored as an attribute of the HTTP request object.

Logically, two concrete sub-classes exist:
1. `SystemGwtRpc`
2. `PluginGwtRpc`

These three new classes now house most of the code which existed in the servlet classes. The request matcher classes and the servlet classes now delegate most of the work to these new shared objects.

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 50m 21s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **2744**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4931/1/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 49m 40s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **2744**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4931/2/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 52m 14s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **2747**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4931/3/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by bennychow — APPROVED** [review]

**Comment by ddiroma** [comment]
@dcleao Approved

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 45m 48s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **2759**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4931/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
