### PR TITLE
BACKLOG-4174 BA Server in 6.0 build: User can't save dashboard.

### PR DESCRIPTION
**Pull request by AliaksandrDrebenchuk**
handling of parameters was fixed

### CODE REVIEW

**Comment by AliaksandrDrebenchuk** [comment]
@bennychow @pentaho-nbaker @rfellows @pamval please review

**Comment by AliaksandrDrebenchuk** [comment]
@bennychow @pentaho-nbaker @rfellows @pamval please review

**Comment by AliaksandrDrebenchuk** [comment]
@bennychow @pentaho-nbaker @rfellows @pamval please review

**Comment by rfellows** [comment]
Looks good to me. I'll merge it since no one else seems to be responsive to this Pull Request.

**Pull request merged**
