### PR TITLE
[PDI-16111]-When performing system restore on PDI Server, some schedu…

### PR DESCRIPTION
**Pull request by ArtsiomYurhevich**
…les are not restored

### CODE REVIEW

**Comment by ArtsiomYurhevich** [comment]
@mbatchelor , @pamval  Could please take a look?

**Comment by kolinus** [comment]
@rmansoor could you please take a look

**Comment by mchen-len-son** [comment]
@pamval @rmansoor can you please take a look?
thanks.

**Comment by kolinus** [comment]
@mbatchelor could you please take a look

**Pull request merged**
