### PR TITLE
BACKLOG-7363 Operation Permissions from plugins are not used in merged server

### PR DESCRIPTION
**Pull request by AliaksandrDrebenchuk**
authorization's actions refreshes after plugins loaded

### CODE REVIEW

**Comment by AliaksandrDrebenchuk** [comment]
@rmansoor @pentaho-nbaker please review

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f repository/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f repository/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  repository/src/org/pentaho/platform/security/policy/rolebased/AbstractJcrBackedRoleBindingDao.java

Unit test coverage change:
============
org.pentaho.platform.security.policy.rolebased.AbstractJcrBackedRoleBindingDao:
 * Branch Change : **-.03%**
 * Complexity Change : **-.07%**
 * Instruction Change : **-.27%**
 * Line Change : **-.10%**
 * Method Change : **-.76%**

Integration test coverage change:
============
org.pentaho.platform.repository2.unified.jcr.sejcr.CredentialsStrategySessionFactory:
 * Branch Change :  + 5.56%
 * Complexity Change :  + 4.71%
 * Instruction Change :  + 2.57%
 * Line Change :  + 3.91%
 * Method Change :  + 7.50%

org.pentaho.platform.security.policy.rolebased.AbstractJcrBackedRoleBindingDao:
 * Branch Change : **-.61%**
 * Complexity Change : **-.70%**
 * Instruction Change : **-.50%**
 * Line Change : **-.25%**

License header violations:
==========================
1. Copyright year is not the current year on repository/src/org/pentaho/platform/security/policy/rolebased/AbstractJcrBackedRoleBindingDao.java. Found 2013. Was expecting 2016

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f repository/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f repository/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  repository/src/org/pentaho/platform/security/policy/rolebased/AbstractJcrBackedRoleBindingDao.java

Unit test coverage change:
============
org.pentaho.platform.security.policy.rolebased.AbstractJcrBackedRoleBindingDao:
 * Branch Change : **-.03%**
 * Complexity Change : **-.07%**
 * Instruction Change : **-.27%**
 * Line Change : **-.10%**
 * Method Change : **-.76%**

Integration test coverage change:
============
org.pentaho.platform.security.policy.rolebased.AbstractJcrBackedRoleBindingDao:
 * Branch Change : **-.61%**
 * Complexity Change : **-.70%**
 * Instruction Change : **-.50%**
 * Line Change : **-.25%**

License header violations:
==========================
1. Copyright year is not the current year on repository/src/org/pentaho/platform/security/policy/rolebased/AbstractJcrBackedRoleBindingDao.java. Found 2013. Was expecting 2016

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f repository/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f repository/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  repository/src/org/pentaho/platform/security/policy/rolebased/AbstractJcrBackedRoleBindingDao.java

Unit test coverage change:
============
org.pentaho.platform.security.policy.rolebased.AbstractJcrBackedRoleBindingDao:
 * Branch Change : **-.03%**
 * Complexity Change : **-.07%**
 * Instruction Change : **-.27%**
 * Line Change : **-.10%**
 * Method Change : **-.76%**

Integration test coverage change:
============
org.pentaho.platform.security.policy.rolebased.AbstractJcrBackedRoleBindingDao:
 * Branch Change : **-.61%**
 * Complexity Change : **-.70%**
 * Instruction Change : **-.50%**
 * Line Change : **-.25%**

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f repository/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f repository/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  repository/src/org/pentaho/platform/security/policy/rolebased/AbstractJcrBackedRoleBindingDao.java

Unit test coverage change:
============
org.pentaho.platform.security.policy.rolebased.AbstractJcrBackedRoleBindingDao:
 * Branch Change : **-.09%**
 * Complexity Change : **-.18%**
 * Instruction Change : **-.36%**
 * Line Change : **-.22%**
 * Method Change : **-1.40%**

Integration test coverage change:
============
org.pentaho.platform.security.policy.rolebased.AbstractJcrBackedRoleBindingDao:
 * Branch Change : **-4.07%**
 * Complexity Change : **-4.34%**
 * Instruction Change : **-3.68%**
 * Line Change : **-3.60%**
 * Method Change : **-7.69%**

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/repository/src/org/pentaho/platform/security/policy/rolebased/AbstractJcrBackedRoleBindingDao.java

1. Message: File does not end with a newline. at Line: 0

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f repository/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f repository/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  repository/src/org/pentaho/platform/security/policy/rolebased/AbstractJcrBackedRoleBindingDao.java

Unit test coverage change:
============
org.pentaho.platform.security.policy.rolebased.AbstractJcrBackedRoleBindingDao:
 * Branch Change : **-.09%**
 * Complexity Change : **-.18%**
 * Instruction Change : **-.36%**
 * Line Change : **-.22%**
 * Method Change : **-1.40%**

Integration test coverage change:
============
org.pentaho.platform.repository2.unified.jcr.sejcr.CredentialsStrategySessionFactory:
 * Branch Change : **-5.56%**
 * Complexity Change : **-4.71%**
 * Instruction Change : **-2.57%**
 * Line Change : **-3.91%**
 * Method Change : **-7.50%**

org.pentaho.platform.security.policy.rolebased.AbstractJcrBackedRoleBindingDao:
 * Branch Change : **-4.07%**
 * Complexity Change : **-4.34%**
 * Instruction Change : **-3.68%**
 * Line Change : **-3.60%**
 * Method Change : **-7.69%**

**Pull request closed without merging**
