### PR TITLE
[BISERVER-14353] Database Connection's Password is exposed in clear t…

### PR DESCRIPTION
**Pull request by smmribeiro**
…ext in exportManifest.xml

@pentaho/tatooine @pentaho-lmartins

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 25m 53s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1470**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4620/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 25m 16s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1470**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4620/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 35m 2s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1470**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4620/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by pentaho-lmartins** [comment]
@ssamora, @befc, can you please review this PR?
I'm OK with the changes but would like your opinion.

**Comment by befc** [comment]
@smmribeiro, @pentaho-lmartins, overall the code looks good. I'd just recommend looking into some object mapping libraries to replace the logic in `DatabaseConnectionConverter.java` class to increase maintainability. This article has a good compilation of this kind of libraries: https://www.baeldung.com/java-performance-mapping-frameworks

Also, take a look at sonar, it's complaining about code duplication. From what I understood it's the `Entry` class that was added to `DatabaseType`, since it already existed in `DatabaseConnection`. If possible, it would be good to extract it so it can be reused in both classes instead of declaring it in both.

**Comment by ssamora** [comment]
Seems ok from me also. Was going to refer the  code duplication also as @befc said.
If it is possible to use something like JMapper as suggested it could be nice, it will be less error-prone. If not i'm ok with it.

**Comment by buildguy** [comment]
### :x: Build failed in 1m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 25m 10s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1489**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4620/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by smmribeiro** [comment]
@ssamora, @befc, @pentaho-lmartins 

I had a look at the mapping frameworks and decided to go more in-depth with MapStruct.
After reading some tutorials and a few tries, I was able to start defining the Mapper for the DatabaseConnection objects.

I found MapStruct rather light and, after understanding its moods, easy to advance...
It's good that the scope of the dependency only needs to be "Compile" - it generates the needed classes which are completely normal and stand-alone (in the sense that they don't need any external library; they can refer to other mappers) Java classes.

For the specific case here, however, I found that I needed to declare several custom mappings and a few extra mappers for other classes (which, in turn, needed some more custom mappers and, most likely, other mappers).

As so, and while the MapStruct use is feasible, I think it's too much for this current issue.
In my opinion, an improvement issue should be created to address the use of MapStruct here (and maybe in other places). I can even save the work I did on this and add it to the issue for future reference.

I'm adding some tests on the Converter class I implemented to give some assurance that it works correctly :-)

As for the duplicated code, I've extracted it as suggested.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 26m 27s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1492**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4620/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by smmribeiro** [comment]
Please DON'T merge this yet. Based on the tests I had for the mapper, I found a problem on the converter :-)

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 25m 24s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1493**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4620/7/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 24m 41s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.services.importexport.DatabaseConnectionConverterTest.testExport2model</b> (click to expand)</summary><p>

```
expected:<6> but was:<1>
```

</p></details>

  
Tests run: **1493**, Failures: **1**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4620/8/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 24m 34s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.services.importexport.DatabaseConnectionConverterTest.testExport2model</b> (click to expand)</summary><p>

```
expected:<6> but was:<1>
```

</p></details>

  
Tests run: **1493**, Failures: **1**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4620/9/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 25m 8s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1493**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/platform/job/PR-4620/10/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
