### PR TITLE
BISERVER-12899 Deprecate the use of ChartHelper in platform

### PR DESCRIPTION
**Pull request by AliaksandrDrebenchuk**
deprecated classes are marked

### CODE REVIEW

**Comment by AliaksandrDrebenchuk** [comment]
@brosander please verify

**Comment by dkincade** [comment]
THis would be @rmansoor @mbatchelor for verification...

**Comment by rmansoor** [comment]
@AliaksandrDrebenchuk  Can we please update this message string to say. Class {0} is deprecated and will be removed in the next major release.

**Comment by AliaksandrDrebenchuk** [comment]
@rmansoor Done

**Pull request merged**
