### PR TITLE
BISERVER-12725 L10N - Home folder should start with upper-case "H" letter when localized

### PR DESCRIPTION
**Pull request by AliaksandrDrebenchuk**
default node title and locale no longer linked

### CODE REVIEW

**Comment by mchen-len-son** [comment]
@rfellows @pamval @rmansoor @pentaho-nbaker please take a look

**Comment by pamval** [comment]
What's the effort of building an unit test for this fix?

**Comment by AliaksandrDrebenchuk** [comment]
my mistake. a test will be added

**Comment by AliaksandrDrebenchuk** [comment]
@rfellows @pamval @rmansoor @pentaho-nbaker please take a look

**Comment by pamval** [comment]
@AliaksandrDrebenchuk tests are failing

**Comment by AliaksandrDrebenchuk** [comment]
@pamval tests are fixed

**Pull request merged**
