### PR TITLE
[SP-5812] - Backport of PPP-4431 - IBM ASoC DAST Scan: Improper Restriction of Excessive Authentication Attempts (/pentaho/j_spring_security_check: j_password) (9.1 Suite)

### PR DESCRIPTION
**Pull request by bcostahitachivantara**
@pentaho-lmartins 
@ssamora 
@smmribeiro

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 17m 14s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
api,assemblies/pentaho-solutions,assemblies/pentaho-war,core,extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1089**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4783/1/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 17m 17s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
api,assemblies/pentaho-solutions,assemblies/pentaho-war,core,extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1089**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4783/2/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Consistent with the original PR.

**Comment by buildguy** [comment]
### :x: Build failed in 6m 30s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
api,assemblies/pentaho-solutions,assemblies/pentaho-war,core,extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **874**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4783/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 40m 14s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
api,assemblies/pentaho-solutions,assemblies/pentaho-war,core,extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **2640**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4783/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by ssamora — APPROVED** [review]

**Pull request merged**
