### PR TITLE
[BACKLOG-36996] PUC Dialogs - Fix semantics of all PUC Message Dialog box instances

### PR DESCRIPTION
**Pull request by varuntangirala**
@pentaho/wcag Please review

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 13m 41s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5274/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 13m 45s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5274/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 13m 27s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5274/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by soagarwal1 — APPROVED** [review]

**Review by NJtwentyone — APPROVED** [review]

**Comment by NJtwentyone** [comment]
SonarQube findings (https://sonar.orl.eng.hitachivantara.com/project/issues?id=pentaho%3Apentaho-platform-ce-parent&pullRequest=5274&resolved=false&types=CODE_SMELL) is basically OverwitePromptDialog has 11 parents, there is nothing we can do about that at this moment.

**Review by NJtwentyone — CHANGES_REQUESTED** [review]
@varuntangirala clean up commits. 

Can you squash your 3 commits into one commit? It seems the same message is commit message is repeated.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 35m
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5274/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
