### PR TITLE
[SP-6512] Partial revert "[SP-6512] - Backport of PPP-5053 - Intercep…

### PR DESCRIPTION
**Pull request by smmribeiro**
…ting few Get request with Burp Suite allows un-authorised user to access data (9.3 Suite) (#5574)"

This **partially** reverts commit f9b2d9ac3e7a5d1913d8c7c4841e3ebd590b33ab.

@mbrasil @pentaho/tatooine_dev

### CODE REVIEW

**Review by mbrasil — APPROVED** [review]

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 48m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core,extensions
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.platform.util.versionchecker.PentahoVersionCheckReflectHelperTest.performVersionCheckTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **2163**, Failures: **1**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform-jdk11/job/PR-5650/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 35m 19s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core,extensions
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.platform.util.versionchecker.PentahoVersionCheckReflectHelperTest.performVersionCheckTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **2163**, Failures: **1**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform-jdk11/job/PR-5650/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 55m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 5 test(s) failed:

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsRunWhenNoBlockout</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsBlockedDuringABlockout</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testMDCContext</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.scheduler2.quartz.BlockingQuartzJobTest.testJobIsRunWhenThereIsAnExceptionRetrievingTheBlockoutManager</b> (click to expand)</summary><p>

```
org/hamcrest/collection/IsArray
```

</p></details>

<details><summary><b>org.pentaho.platform.util.versionchecker.PentahoVersionCheckReflectHelperTest.performVersionCheckTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **2803**, Failures: **5**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform-jdk11/job/PR-5650/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 39m 37s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core,extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **2163**, Failures: **0**, Skipped: **3** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform-jdk11/job/PR-5650/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
