### PR TITLE
[SP-2607] Backport of BISERVER-13057 - User with multiple roles/groups gets blank screen when logs in to Pentaho User Console (5.4 Suite)

### PR DESCRIPTION
**Pull request by mchen-len-son**
Actually couldn't reproduce the issue on biserver-ee-5.4-NIGHTLY-349, but partially reproduced on biserver-ee-5.4-NIGHTLY-335 (is not reproduced with current fix).

- cherry-picked two commits for BISERVER-13081
- fixed checkstyle violations
- bumped down Spring version for test libs in order to be consistent with the project version and to fix failing tests
- fixed two another failing tests

### CODE REVIEW

**Comment by mchen-len-son** [comment]
@pamval, @pedrofvteixeira, please, run wingman and review

**Comment by brosander** [comment]
http://wingman.pentaho.com:8080/job/wingman/16/

**Comment by brosander** [comment]
http://wingman.pentaho.com:8080/job/wingman/17/

**Comment by mchen-len-son** [comment]
@pamval @mdamour1976 @pentaho-nbaker review please

**Pull request merged**
