### PR TITLE
[BACKLOG-7904] After user tries to close dashboard with report except…

### PR DESCRIPTION
**Pull request by Aliaksandr-Kastenka**
…ion is thrown

### CODE REVIEW

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f user-console/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f user-console/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  user-console/source/org/pentaho/mantle/client/commands/SaveCommand.java

License header violations:
==========================
1. Copyright year is not the current year on user-console/source/org/pentaho/mantle/client/commands/SaveCommand.java. Found 2013. Was expecting 2016

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f user-console/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f user-console/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  user-console/source/org/pentaho/mantle/client/commands/SaveCommand.java

**Comment by Aliaksandr-Kastenka** [comment]
@tmorgner 
Please review.

**Comment by tmorgner** [comment]
The save-command is not only used in dashboards - PIR for instance uses it as well - it is a public API. And so is the "tabClose" event now. It is a generic event - it is not private to the report viewer and future OEMs can use this event in their own code. So sending it semi-randomly just to unregister the event-listeners in an eventually existing report-viewer just because dashboarding does something silly is wrong. 

Please investigate the dashboard system and its "handle_puc_save" method for a more targeted fix. If they manipulate the DOM there, then the fix should be there too.

**Pull request closed without merging**
