### PR TITLE
[PDI-19084] Backward slash ( \ ) is not resolved in the transformatio…

### PR DESCRIPTION
**Pull request by ssamora**
…n path after upgrading from 8.1 to 8.3

@bcostahitachivantara @smmribeiro

### CODE REVIEW

**Comment by buildguy** [comment]
### :warning: Build finished in 29m 35s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl repository
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 10 test(s) failed:

<details><summary><b>org.pentaho.platform.web.http.filters.PentahoAwareCharacterEncodingFilterTest.doFilter_noEncodingIsProvided</b> (click to expand)</summary><p>

```
javax/servlet/http/HttpUpgradeHandler
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.filters.PentahoAwareCharacterEncodingFilterTest.doFilter_ignoreFlagIsCleared_requestEncodingNotNull</b> (click to expand)</summary><p>

```
javax/servlet/http/HttpUpgradeHandler
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.filters.PentahoAwareCharacterEncodingFilterTest.doFilter_ignoreFlagIsCleared_requestEncodingIsNull</b> (click to expand)</summary><p>

```
javax/servlet/http/HttpUpgradeHandler
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.filters.PentahoAwareCharacterEncodingFilterTest.doFilter_ignoreFlagIsSet</b> (click to expand)</summary><p>

```
javax/servlet/http/HttpUpgradeHandler
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.security.CsrfGateFilterTest.testDoFilterWhileReloadAndCsrfProtectionEnabled</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.security.CsrfGateFilterTest.testDoFilterWhenInitializedAndCsrfProtectionEnabled</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.security.CsrfTokenResponseHeaderFilterTest.TestStatusCodeNoContent</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.security.CsrfTokenResponseHeaderFilterTest.testWhenCsrfTokenThenCsrfResponseHeaders</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.security.CsrfTokenResponseHeaderFilterTest.TestWhenCsrfTokenThenCorsResponseHeaders</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.test.platform.plugin.services.security.userrole.ldap.UnionizingLdapAuthoritiesPopulatorTests.org.pentaho.test.platform.plugin.services.security.userrole.ldap.UnionizingLdapAuthoritiesPopulatorTests</b> (click to expand)</summary><p>

```
Configuration problem: You cannot use a spring-security-2.0.xsd or spring-security-3.0.xsd or spring-security-3.1.xsd schema or spring-security-3.2.xsd schema or spring-security-4.0.xsd schema with Spring Security 5.4. Please update your schema declarations to the 5.4 schema.
Offending resource: class path resource [ldapIntegrationTestContext.xml]
```

</p></details>

  
Tests run: **1960**, Failures: **10**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4829/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 18s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl repository
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 7m 10s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl repository
```
---
:ok_hand: All tests passed!
 
Tests run: **412**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4829/3/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 7m 45s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl repository
```
---
:ok_hand: All tests passed!
 
Tests run: **412**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4829/4/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 28m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl repository
```
---
:ok_hand: All tests passed!
 
Tests run: **1960**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4829/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 28m 14s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl repository
```
---
:ok_hand: All tests passed!
 
Tests run: **1960**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4829/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 25s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
Command "git checkout -f 37ab744088167e22dfb714bb47df0ffd7733da87" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: 37ab744088167e22dfb714bb47df0ffd7733da87
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 27m 33s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl repository
```
---
:ok_hand: All tests passed!
 
Tests run: **1960**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4829/8/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by bcostahitachivantara — APPROVED** [review]

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 28m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl repository
```
---
:ok_hand: All tests passed!
 
Tests run: **1980**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4829/9/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 29m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl repository
```
---
:ok_hand: All tests passed!
 
Tests run: **1980**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4829/10/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
