### PR TITLE
[BISERVER-14442] - Database connections using connection pooling will not adhere to changes in the connection details

### PR DESCRIPTION
**Pull request by bcostahitachivantara**
@pentaho-lmartins
@ssamora
@ppatricio
@smmribeiro

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 2m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by bcostahitachivantara** [comment]
This build will fail until https://github.com/pentaho/pentaho-kettle/pull/7535 be merged

**Comment by buildguy** [comment]
### :x: Build failed in 3m 38s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 32m 17s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1516**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4718/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
