### PR TITLE
[PDB-1427] Default date formats in dashboard and PIR are not same

### PR DESCRIPTION
**Pull request by SergeyTravin**

### CODE REVIEW

**Comment by SergeyTravin** [comment]
It should be merged after https://github.com/pentaho/pentaho-chartbeans/pull/17

**Comment by SergeyTravin** [comment]
@pedrofvteixeira, @pamval Could you start wingman please?

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-osgi/49/

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-osgi/51/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  extensions/src/org/pentaho/platform/plugin/action/chartbeans/ChartComponent.java
  extensions/src/org/pentaho/platform/plugin/action/pentahometadata/MetadataQueryComponent.java
  extensions/src/org/pentaho/platform/plugin/services/connections/sql/SQLResultSet.java
  extensions/test-src/org/pentaho/platform/plugin/services/connections/sql/SQLResultSetTest.java
  extensions/test-src/org/pentaho/test/platform/plugin/MetadataQueryComponentIT.java

Still Broken Tests:
======================
org.pentaho.platform.osgi.SystemPackageExtrapolatorTest.testJBossProvider: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: 
Expected: iterable containing ["org.apache", "org.apache.log4j"]
     but: item 0: was "org.apache.log4j"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.pentaho.platform.osgi.SystemPackageExtrapolatorTest.testJBossProvider(SystemPackageExtrapolatorTest.java:85)

```
org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillContinueToLoadOnException: org.mockito.exceptions.verification.junit.ArgumentsAreDifferent
```
Argument(s) are different! Wanted:
file.renameTo(
    
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillContinueToLoadOnException(ArchiveLoaderTest.java:93)
Actual invocation has different arguments:
file.renameTo(
    /root/path/jobs.zip.197001021017
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoader.loadAll(ArchiveLoader.java:68)

	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillContinueToLoadOnException(ArchiveLoaderTest.java:93)

```
org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillImportAllZipsInADirectory: org.mockito.exceptions.verification.junit.ArgumentsAreDifferent
```
Argument(s) are different! Wanted:
file.renameTo(
    
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillImportAllZipsInADirectory(ArchiveLoaderTest.java:66)
Actual invocation has different arguments:
file.renameTo(
    /root/path/jobs.zip.197001021017
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoader.loadAll(ArchiveLoader.java:68)

	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillImportAllZipsInADirectory(ArchiveLoaderTest.java:66)

```

Unit test coverage change:
============
org.pentaho.platform.plugin.services.connections.sql.SQLResultSet:
 * Branch Change :  + 2.99%
 * Complexity Change :  + 1.74%
 * Instruction Change :  + .47%
 * Line Change :  + .86%



Integration test coverage change:
============
org.pentaho.platform.plugin.action.chartbeans.ChartAction:
 * Instruction Change :  + .22%

org.pentaho.platform.plugin.action.pentahometadata.MetadataQueryComponent:
 * Branch Change : **-1.48%**
 * Complexity Change : **-1.42%**
 * Instruction Change : **-1.15%**
 * Line Change : **-1.10%**

org.pentaho.platform.plugin.services.connections.sql.SQLResultSet:
 * Branch Change :  + 2.85%
 * Complexity Change :  + 1.53%
 * Instruction Change :  + 2.03%
 * Line Change :  + 1.43%



Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/extensions/src/org/pentaho/platform/plugin/action/chartbeans/ChartComponent.java

1. Message: Line has trailing spaces at Line: 200

**Comment by SergeyTravin** [comment]
@pedrofvteixeira, @pamval Could you start wingman one more time?

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-osgi/67/

**Comment by lucboudreau** [comment]
Error building command: /home/devuser/docker-build/assembly/build/assembly-0.0.1/source/pentaho-platform-base-2842-af33ff44-37e5-4b90-87dc-043cfa6c70b6/pom.xml (No such file or directory)

**Comment by SergeyTravin** [comment]
@pedrofvteixeira, @pamval 

Error building command: /home/devuser/docker-build/assembly/build/assembly-0.0.1/source/pentaho-platform-base-2842-af33ff44-37e5-4b90-87dc-043cfa6c70b6/pom.xml (No such file or directory)

It looks like the wingman start was failing, restart it again please.

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-osgi/68/

**Comment by lucboudreau** [comment]
Error building command: /home/devuser/docker-build/assembly/build/assembly-0.0.1/source/pentaho-platform-base-2842-7db90013-71d3-4481-9071-66aa69fe7b74/pom.xml (No such file or directory)

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman/6/

**Comment by lucboudreau** [comment]
Error building command: /home/devuser/docker-build/assembly/build/assembly-0.0.1/source/pentaho-platform-base-2842-6ea6870b-4be7-4c13-9bfa-61a3becd1fe5/pom.xml (No such file or directory)

**Comment by SergeyTravin** [comment]
@pentaho-nbaker, @rmansoor, @pamval, could you review it please?

**Comment by SergeyTravin** [comment]
@kolinus could you review it please?

**Comment by kolinus** [comment]
I'm ok with the changes, but do bot see latest wingman report.
Can it be rerun?

**Comment by SergeyTravin** [comment]
@pedrofvteixeira, @pamval Is it able to restart wingman? The last two times it fails during self initialization.

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-osgi/90/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  extensions/src/org/pentaho/platform/plugin/action/chartbeans/ChartComponent.java
  extensions/src/org/pentaho/platform/plugin/action/pentahometadata/MetadataQueryComponent.java
  extensions/src/org/pentaho/platform/plugin/services/connections/sql/SQLResultSet.java
  extensions/test-src/org/pentaho/platform/plugin/services/connections/sql/SQLResultSetTest.java
  extensions/test-src/org/pentaho/test/platform/plugin/MetadataQueryComponentIT.java

Still Broken Tests:
======================
org.pentaho.platform.osgi.SystemPackageExtrapolatorTest.testJBossProvider:
-----------------------------------------------
junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: 
Expected: iterable containing ["org.apache", "org.apache.log4j"]
     but: item 0: was "org.apache.log4j"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.pentaho.platform.osgi.SystemPackageExtrapolatorTest.testJBossProvider(SystemPackageExtrapolatorTest.java:85)

```
org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillContinueToLoadOnException:
-----------------------------------------------
org.mockito.exceptions.verification.junit.ArgumentsAreDifferent
```
Argument(s) are different! Wanted:
file.renameTo(
    
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillContinueToLoadOnException(ArchiveLoaderTest.java:93)
Actual invocation has different arguments:
file.renameTo(
    /root/path/jobs.zip.197001021017
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoader.loadAll(ArchiveLoader.java:68)

	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.pentaho.platform.plugin.services.import
```
org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillImportAllZipsInADirectory:
-----------------------------------------------
org.mockito.exceptions.verification.junit.ArgumentsAreDifferent
```
Argument(s) are different! Wanted:
file.renameTo(
    
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillImportAllZipsInADirectory(ArchiveLoaderTest.java:66)
Actual invocation has different arguments:
file.renameTo(
    /root/path/jobs.zip.197001021017
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoader.loadAll(ArchiveLoader.java:68)

	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.pentaho.platform.plugin.services.import
```

Unit test coverage change:
============
org.pentaho.platform.plugin.services.connections.sql.SQLResultSet:
 * Branch Change :  + 2.99%
 * Complexity Change :  + 1.74%
 * Instruction Change :  + .47%
 * Line Change :  + .86%

org.pentaho.platform.plugin.services.metadata.PentahoMetadataDomainRepository:
 * Branch Change :  + 1.25%
 * Complexity Change :  + .80%
 * Instruction Change :  + .93%
 * Line Change :  + .82%



Integration test coverage change:
============
org.pentaho.platform.plugin.action.pentahometadata.MetadataQueryComponent:
 * Branch Change :  + 3.06%
 * Complexity Change :  + 6.48%
 * Instruction Change :  + 5.44%
 * Line Change :  + 9.15%
 * Method Change :  + 12.50%

org.pentaho.platform.plugin.services.connections.sql.SQLResultSet:
 * Branch Change :  + 2.85%
 * Complexity Change :  + 1.53%
 * Instruction Change :  + 2.03%
 * Line Change :  + 1.43%

**Pull request merged**
