### PR TITLE
[SP-5729] Backport of BISERVER-14442 - Database connections using con…

### PR DESCRIPTION
**Pull request by pentaho-lmartins**
…nection pooling will not adhere to changes in the connection details (9.1 Suite)

Cherry-pick of #4718 into 9.1 branch.

Merge after https://github.com/pentaho/pentaho-kettle/pull/7707 and before https://github.com/pentaho/pdi-platform-plugin/pull/84

@ssamora @ppatricio

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 1m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 2m 4s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 23s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 3m 7s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 31m 11s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1524**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4762/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by ssamora — APPROVED** [review]

**Pull request merged**
