### PR TITLE
[BISERVER-12794] Permissions can delete but not restore file

### PR DESCRIPTION
**Pull request by IvanNikolaychuk**
- Expanded doRestore functionality (added ability to restore files in home folder, choosing one of overwrite modes)
- Created new user dialog, suggesting user to restore files in his home folder when he has no write permissions to original file folder.
- Test written
- Checkstyle applied

@pentaho-nbaker, @mdamour1976, @rmansoor, review it please

### CODE REVIEW

**Comment by IvanNikolaychuk** [comment]
@pentaho-nbaker, @mdamour1976, @rmansoor, review it please

**Comment by pamval** [comment]
@rmansoor please review

**Comment by rmansoor** [comment]
@IvanNikolaychuk is there a way for you to reduce this to two commits one for the code change and other for check style. 

I have verified the code is working properly using all the scenarios described in the case. I have also ran the unit test and they are all good. 

Once you can reduce the commits, I will process the pull request

**Comment by IvanNikolaychuk** [comment]
@rmansoor updated

**Pull request merged**
