### PR TITLE
[BACKLOG-7604] Added a manager to write and update the karaf ports file

### PR DESCRIPTION
**Pull request by JoaoLMPereira**
PortAssigned.txt that was removed.

### CODE REVIEW

**Comment by JoaoLMPereira** [comment]
@pedrofvteixeira please run wingman

**Comment by lucboudreau** [comment]
http://wingman.pentaho.com:8080/job/wingman/137/console

**Comment by brosander** [comment]
Base build failed with return code 143

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/osgi/KarafInstance.java
  extensions/src/org/pentaho/platform/settings/PortFileManager.java
  extensions/src/org/pentaho/platform/settings/ServerPort.java
  extensions/test-src/org/pentaho/platform/settings/PortFileManagerTest.java

Newly Broken Tests:
======================
org.pentaho.platform.plugin.services.metadata.PentahoMetadataDomainRepositoryConcurrencyTest.addDomain_getDomain_Simultaneously:
-----------------------------------------------
junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: The following errors occurred: 
Expected not to find domain [domain_29], but got it

	at org.pentaho.platform.plugin.services.metadata.PentahoMetadataDomainRepositoryConcurrencyTest.runTest(PentahoMetadataDomainRepositoryConcurrencyTest.java:224)
	at org.pentaho.platform.plugin.services.metadata.PentahoMetadataDomainRepositoryConcurrencyTest.addDomain_getDomain_Simultaneously(PentahoMetadataDomainRepositoryConcurrencyTest.java:178)

```


Still Broken Tests:
======================
org.pentaho.platform.osgi.SystemPackageExtrapolatorTest.testJBossProvider:
-----------------------------------------------
junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: 
Expected: iterable containing ["org.apache", "org.apache.log4j"]
     but: item 0: was "org.apache.log4j"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.pentaho.platform.osgi.SystemPackageExtrapolatorTest.testJBossProvider(SystemPackageExtrapolatorTest.java:85)

```
org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillContinueToLoadOnException:
-----------------------------------------------
org.mockito.exceptions.verification.junit.ArgumentsAreDifferent
```
Argument(s) are different! Wanted:
file.renameTo(
    
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillContinueToLoadOnException(ArchiveLoaderTest.java:93)
Actual invocation has different arguments:
file.renameTo(
    /root/path/jobs.zip.197001021017
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoader.loadAll(ArchiveLoader.java:68)

	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.pentaho.platform.plugin.services.import
```
org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillImportAllZipsInADirectory:
-----------------------------------------------
org.mockito.exceptions.verification.junit.ArgumentsAreDifferent
```
Argument(s) are different! Wanted:
file.renameTo(
    
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillImportAllZipsInADirectory(ArchiveLoaderTest.java:66)
Actual invocation has different arguments:
file.renameTo(
    /root/path/jobs.zip.197001021017
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoader.loadAll(ArchiveLoader.java:68)

	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.pentaho.platform.plugin.services.import
```

Unit test coverage change:
============
org.pentaho.platform.config.MondrianConfigProperties:
 * Branch Change :  + 7.14%
 * Instruction Change :  + 3.16%

org.pentaho.platform.osgi.KarafInstance:
 * Instruction Change : **-.85%**
 * Line Change : **-1.10%**

org.pentaho.platform.settings.PortFileManager:
 * Branch New Coverage : 70.00%
 * Complexity New Coverage : 83.33%
 * Instruction New Coverage : 85.96%
 * Line New Coverage : 82.35%
 * Method New Coverage : 100.00%

org.pentaho.platform.settings.ServerPort:
 * Instruction Change : **-3.31%**
 * Line Change : **-1.74%**

null

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/osgi/KarafInstance.java
  extensions/src/org/pentaho/platform/settings/PortFileManager.java
  extensions/src/org/pentaho/platform/settings/ServerPort.java
  extensions/test-src/org/pentaho/platform/settings/PortFileManagerTest.java

Still Broken Tests:
======================
org.pentaho.platform.osgi.SystemPackageExtrapolatorTest.testJBossProvider:
-----------------------------------------------
junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: 
Expected: iterable containing ["org.apache", "org.apache.log4j"]
     but: item 0: was "org.apache.log4j"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.pentaho.platform.osgi.SystemPackageExtrapolatorTest.testJBossProvider(SystemPackageExtrapolatorTest.java:85)

```
org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillContinueToLoadOnException:
-----------------------------------------------
org.mockito.exceptions.verification.junit.ArgumentsAreDifferent
```
Argument(s) are different! Wanted:
file.renameTo(
    
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillContinueToLoadOnException(ArchiveLoaderTest.java:93)
Actual invocation has different arguments:
file.renameTo(
    /root/path/jobs.zip.197001021017
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoader.loadAll(ArchiveLoader.java:68)

	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.pentaho.platform.plugin.services.import
```
org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillImportAllZipsInADirectory:
-----------------------------------------------
org.mockito.exceptions.verification.junit.ArgumentsAreDifferent
```
Argument(s) are different! Wanted:
file.renameTo(
    
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.testWillImportAllZipsInADirectory(ArchiveLoaderTest.java:66)
Actual invocation has different arguments:
file.renameTo(
    /root/path/jobs.zip.197001021017
);
-> at org.pentaho.platform.plugin.services.importer.ArchiveLoader.loadAll(ArchiveLoader.java:68)

	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.pentaho.platform.plugin.services.import
```

Unit test coverage change:
============
org.pentaho.platform.config.MondrianConfigProperties:
 * Branch Change :  + 7.14%
 * Instruction Change :  + 3.16%

org.pentaho.platform.osgi.KarafInstance:
 * Instruction Change : **-.85%**
 * Line Change : **-1.10%**

org.pentaho.platform.settings.PortFileManager:
 * Branch New Coverage : 70.00%
 * Complexity New Coverage : 83.33%
 * Instruction New Coverage : 85.96%
 * Line New Coverage : 82.35%
 * Method New Coverage : 100.00%

org.pentaho.platform.settings.ServerPort:
 * Instruction Change : **-3.31%**
 * Line Change : **-1.74%**

null

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/osgi/KarafInstance.java
  extensions/src/org/pentaho/platform/settings/PortFileManager.java
  extensions/src/org/pentaho/platform/settings/ServerPort.java
  extensions/test-src/org/pentaho/platform/settings/PortFileManagerTest.java

Unit test coverage change:
============
org.pentaho.platform.osgi.KarafInstance:
 * Instruction Change : **-.85%**
 * Line Change : **-1.10%**

org.pentaho.platform.plugin.services.metadata.PentahoMetadataDomainRepository:
 * Branch Change :  + .62%
 * Complexity Change :  + .80%

org.pentaho.platform.plugin.services.metadata.PentahoMetadataInformationMap:
 * Branch Change :  + 6.25%
 * Complexity Change :  + 5.00%

org.pentaho.platform.settings.PortFileManager:
 * Branch New Coverage : 70.00%
 * Complexity New Coverage : 83.33%
 * Instruction New Coverage : 85.96%
 * Line New Coverage : 82.35%
 * Method New Coverage : 100.00%

org.pentaho.platform.settings.ServerPort:
 * Instruction Change : **-3.31%**
 * Line Change : **-1.74%**

null

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/osgi/KarafInstance.java
  extensions/src/org/pentaho/platform/settings/PortFileManager.java
  extensions/src/org/pentaho/platform/settings/ServerPort.java
  extensions/test-src/org/pentaho/platform/osgi/KarafInstanceTest.java
  extensions/test-src/org/pentaho/platform/settings/PortFileManagerTest.java
  extensions/test-src/org/pentaho/platform/settings/ServerPortTest.java

Unit test coverage change:
============
org.pentaho.platform.osgi.KarafInstance:
 * Instruction Change : **-.85%**
 * Line Change : **-1.10%**

org.pentaho.platform.settings.PortFileManager:
 * Branch New Coverage : 70.00%
 * Complexity New Coverage : 84.62%
 * Instruction New Coverage : 86.44%
 * Line New Coverage : 83.33%
 * Method New Coverage : 100.00%

org.pentaho.platform.settings.ServerPort:
 * Branch Change :  + 25.00%
 * Complexity Change :  + 25.00%
 * Instruction Change :  + 17.74%
 * Line Change :  + 20.00%
 * Method Change :  + 20.00%

null

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/extensions/test-src/org/pentaho/platform/osgi/KarafInstanceTest.java

1. Message: Line has trailing spaces at Line: 69
2. Message: '(' is not followed by whitespace. at Line: 100 Column: 18
3. Message: ')' is not preceded with whitespace. at Line: 100 Column: 26
4. Message: Line has trailing spaces at Line: 103

File /home/buildguy/project/extensions/test-src/org/pentaho/platform/settings/PortFileManagerTest.java

1. Message: 'if' construct must use '{}'s. at Line: 107
2. Message: 'if' construct must use '{}'s. at Line: 109

File /home/buildguy/project/extensions/test-src/org/pentaho/platform/settings/ServerPortTest.java

1. Message: Line has trailing spaces at Line: 36
2. Message: Line has trailing spaces at Line: 74
3. Message: Line has trailing spaces at Line: 79
4. Message: Line has trailing spaces at Line: 85

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/osgi/KarafInstance.java
  extensions/src/org/pentaho/platform/settings/PortFileManager.java
  extensions/src/org/pentaho/platform/settings/ServerPort.java
  extensions/test-src/org/pentaho/platform/osgi/KarafInstanceTest.java
  extensions/test-src/org/pentaho/platform/settings/PortFileManagerTest.java
  extensions/test-src/org/pentaho/platform/settings/ServerPortTest.java

Unit test coverage change:
============
org.pentaho.platform.config.MondrianConfigProperties:
 * Branch Change : **-7.14%**
 * Instruction Change : **-3.16%**

org.pentaho.platform.osgi.KarafInstance:
 * Instruction Change : **-.85%**
 * Line Change : **-1.10%**

org.pentaho.platform.settings.PortFileManager:
 * Branch New Coverage : 70.00%
 * Complexity New Coverage : 84.62%
 * Instruction New Coverage : 86.44%
 * Line New Coverage : 83.33%
 * Method New Coverage : 100.00%

org.pentaho.platform.settings.ServerPort:
 * Branch Change :  + 25.00%
 * Complexity Change :  + 25.00%
 * Instruction Change :  + 17.74%
 * Line Change :  + 20.00%
 * Method Change :  + 20.00%

Integration test coverage change:
============
org.pentaho.platform.plugin.action.chartbeans.ChartAction:
 * Instruction Change :  + .22%

**Pull request merged**
