### PR TITLE
[SP-2549] Backport of BISERVER-11649 - Mondrian role mappers don't pass the role name of a user when his username and group are both 'Admin' (6.1 Suite)

### PR DESCRIPTION
**Pull request by IvanNikolaychuk**
**UserRoleDaoResource**

- Track every update of roles, and if this update is touching a user in current session, updating IPentahoSession.SESSION_ROLES attribute, that represents the roles, avalible for current user.

We are doing it via userRoleDaoService, because data there is always up-to-date
- Added few helper methods and changed visibility of some methods for testing reasongs

**UserRoleDaoResource_RoleUpdatesTest**
- A separate test, written specially for checking, that roles were/were not (depending on whether user is session-user or not) updated.

**UserRoleDaoResourceTest**
- Changed few tests a little,(added several mocks), as method content changed.

**GeneratedContentCleanerTest**
- Added few tests to increase code coverage

@aliakseihaidukou , @akhayrutdinov, review it please. This is a backport of https://github.com/pentaho/pentaho-platform/pull/2788 and https://github.com/pentaho/pentaho-platform/pull/2822

@pamval , @pedrofvteixeira , could you please run WM?

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
i'm on it

**Comment by akhayrutdinov** [comment]
@pamval, @pedrofvteixeira, run WM for this PR please

**Comment by akhayrutdinov** [comment]
Same as #2788 and #2822. If WM finds no problems, I'll merge it

**Comment by pamval** [comment]
running wm

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
  extensions/test-src/org/pentaho/platform/admin/GeneratedContentCleanerTest.java
  extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
  extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource_RolesUpdatedTest.java








Still Broken Tests:
-----------------
org.pentaho.test.platform.web.http.api.RepositoryResourceIT.b3_HappyPath_GET_withMimeType: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: Response media type incorrect: expected:<application/pdf;[]charset=UTF-8> but was:<application/pdf;[ ]charset=UTF-8>
	at org.pentaho.test.platform.web.http.api.JerseyTestUtil.assertResponse(JerseyTestUtil.java:47)
	at org.pentaho.test.platform.web.http.api.RepositoryResourceIT.b3_HappyPath_GET_withMimeType(RepositoryResourceIT.java:364)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)

```

Unit test coverage change:
============
org.pentaho.platform.web.http.api.resources.UserRoleDaoResource:
 * instructionPercentCoverageChange : +25.59%
 * branchPercentCoverageChange : +43.38%
 * linePercentCoverageChange : +19.84%
 * complexityPercentCoverageChange : +19.18%
 * methodPercentCoverageChange : +13.48%
    
org.pentaho.platform.admin.GeneratedContentCleaner:
 * instructionPercentCoverageChange : +13.33%
 * branchPercentCoverageChange : +40.00%
 * linePercentCoverageChange : +10.71%
 * complexityPercentCoverageChange : +27.27%

**Comment by akhayrutdinov** [comment]
@IvanNikolaychuk, can you please add changes from https://github.com/pentaho/pentaho-platform/commit/4037f36ee57515c45985af037b73ecf2ad3be1b3 to repair tests? Thanks

**Comment by IvanNikolaychuk** [comment]
@akhayrutdinov, done.

@pamval, @pedrofvteixeira, could you please run WM one more time?

**Comment by pedrofvteixeira** [comment]
[wingman](http://10.100.11.222:8080/job/wingman-ant/458)

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
  extensions/test-src/org/pentaho/platform/admin/GeneratedContentCleanerTest.java
  extensions/test-src/org/pentaho/platform/config/SystemConfigFolderTest.java
  extensions/test-src/org/pentaho/platform/plugin/services/metadata/PentahoMetadataDomainRepositoryTest.java
  extensions/test-src/org/pentaho/platform/web/http/api/resources/SchedulerResourceUtilTest.java
  extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResourceTest.java
  extensions/test-src/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource_RolesUpdatedTest.java
  extensions/test-src/org/pentaho/test/platform/web/http/api/JerseyTestUtil.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File extensions/test-src/org/pentaho/test/platform/web/http/api/JerseyTestUtil.java
1. Message: Using a static member import should be avoided - junit.framework.Assert.assertEquals. at Line: 27 Column: None
2. Message: Using a static member import should be avoided - junit.framework.Assert.assertNotNull. at Line: 28 Column: None





Newly Fixed Tests:
-----------------
org.pentaho.test.platform.web.http.api.RepositoryResourceIT.b3_HappyPath_GET_withMimeType: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: Response media type incorrect: expected:<application/pdf;[]charset=UTF-8> but was:<application/pdf;[ ]charset=UTF-8>
	at org.pentaho.test.platform.web.http.api.JerseyTestUtil.assertResponse(JerseyTestUtil.java:47)
	at org.pentaho.test.platform.web.http.api.RepositoryResourceIT.b3_HappyPath_GET_withMimeType(RepositoryResourceIT.java:364)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)

```



Unit test coverage change:
============
org.pentaho.platform.web.http.api.resources.UserRoleDaoResource:
 * instructionPercentCoverageChange : +25.59%
 * branchPercentCoverageChange : +43.38%
 * linePercentCoverageChange : +19.84%
 * complexityPercentCoverageChange : +19.18%
 * methodPercentCoverageChange : +13.48%
    
org.pentaho.platform.config.MondrianConfigProperties:
 * instructionPercentCoverageChange : +3.16%
 * branchPercentCoverageChange : +7.14%
    
org.pentaho.platform.admin.GeneratedContentCleaner:
 * instructionPercentCoverageChange : +13.33%
 * branchPercentCoverageChange : +40.00%
 * linePercentCoverageChange : +10.71%
 * complexityPercentCoverageChange : +27.27%
    
org.pentaho.platform.settings.PortAssigner:
 * branchPercentCoverageChange : +2.17%
 * complexityPercentCoverageChange : +2.70%
    
org.pentaho.platform.plugin.services.metadata.PentahoMetadataDomainRepository:
 * instructionPercentCoverageChange :**-0.93%**
 * branchPercentCoverageChange :**-1.25%**
 * linePercentCoverageChange :**-0.82%**
 * complexityPercentCoverageChange :**-0.80%**

**Comment by IvanNikolaychuk** [comment]
@akhayrutdinov, seems like everything is good now

**Comment by akhayrutdinov** [comment]
checking it now

**Comment by akhayrutdinov** [comment]
The test is passing on my desktop, looks like WM gives incorrect results. Merged

**Pull request merged**
