### PR TITLE
[SP-5414] - Backport of BISERVER-12300 - Metadata on files/folders erased during export/import (9.0 Suite)

### PR DESCRIPTION
**Pull request by bcostahitachivantara**
@pentaho-lmartins
@ssamora
@ppatricio
@smmribeiro

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 18m 45s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,extensions,repository
```
---
:ok_hand: All tests passed!
 
Tests run: **1075**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4676/1/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 41m 26s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,extensions,repository
```
---
:ok_hand: All tests passed!
 
Tests run: **2551**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4676/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by ppatricio** [comment]
Merge when a fix version is provided

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 40m 34s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl api,extensions,repository
```
---
:ok_hand: All tests passed!
 
Tests run: **2551**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4676/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
