### PR TITLE
[PPP-3619] Schedules shows wrong "Next run" time/date after schedule was edited.

### PR DESCRIPTION
**Pull request by Advent51**
- fixed

### CODE REVIEW

**Comment by Advent51** [comment]
@pamval @mbatchelor please review.
In case of wingman's problems - all tests passed locally.

**Comment by Advent51** [comment]
@pamval @mbatchelor please review

**Comment by pamval** [comment]
@Advent51 can you take a look at the test failures? and try to figure out why they run locally but not in wingman. I mean, the first error message leads me to believe that some tests only run with a particular configuration (for instance, a specific timezone). thanks!

**Comment by Advent51** [comment]
@pamval PentahoBlockoutManagerIT tests failures were my mistake, but I fixed them in last commit. QuartzSchedulerIT tests passed locally even after my first incomplete fix. And I tested it again before force push. I don't know why, but wingman didn't start it's job to check last commit. Could you please trigger wingman to check it please?

**Comment by pamval** [comment]
waiting for wingman

**Comment by Advent51** [comment]
@pamval I guess this fail wasn't caused by my fix:
> [NOT FOUND  ] pentaho-kettle#kettle-engine;7.1-SNAPSHOT!kettle-engine.jar(source)

**Comment by pamval** [comment]
I hope not :). I submitted another request to wingman

**Comment by Advent51** [comment]
@pamval wingman is still in a bad mood :(

**Comment by Advent51** [comment]
@pamval please review

**Pull request closed without merging**
