### PR TITLE
[CDA-222] CDA Clear Cache API '/plugin/cda/api/clearCache' not workin…

### PR DESCRIPTION
**Pull request by pentaho-lmartins**
…g to show the updated data.

@duarteteixeira @pamval

### CODE REVIEW

**Comment by pentaho-lmartins** [comment]
@lucboudreau, can you please review this PR. The use case is described in the corresponding JIRA.

**Comment by mchen-len-son** [comment]
@pamval can you please have a look?
this is an additional PR to #4053.

**Comment by pentaho-lmartins** [comment]
Hi @mchen-len-son, we're waiting for feedback from @lucboudreau. @pamval already reviewed it and asked for Luc's review as well. As it turned out, this is not a CDA issue but a Mondrian issue.

**Comment by pentaho-lmartins** [comment]
@lucboudreau, changed code with your recommendation. Please review and merge if OK.

**Comment by lucboudreau** [comment]
Can you write some tests in ``OlapServiceImplTest`` for the new method? There are no test classes for ``SystemRefreshResource`` however, but if you figure out how to add one, it wouldn't hurt.

**Comment by pentaho-lmartins** [comment]
@lucboudreau, added test cases to `OlapServiceImplTest` and created `SystemRefreshResourceTest` with tests for the added method. Please review and merge if all is OK.

**Pull request merged**
