### PR TITLE
[BACKLOG-6516] Relocate and rename pentaho.xml's 'verify-user-on-prin…

### PR DESCRIPTION
**Pull request by pedrofvteixeira**
…cipal-creation' property

	- QA identified one scenario where this was not working as expected, namely a scenario where the property exists but it is set to empty
	- added additional unit tests that focus on that particular scenario

### CODE REVIEW

**Comment by pedrofvteixeira** [comment]
@rmansoor , @CodeOnCoffee , @dkincade please review

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f repository/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  repository/src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProvider.java
  repository/test-src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProvider_PrincipalCreation_Test.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File repository/test-src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProvider_PrincipalCreation_Test.java
1. Message: 'if' is not followed by whitespace. at Line: 160 Column: 7
2. Message: Using a static member import should be avoided - org.hamcrest.CoreMatchers.instanceOf. at Line: 37 Column: None
3. Message: Using a static member import should be avoided - org.hamcrest.CoreMatchers.is. at Line: 38 Column: None
4. Message: Using a static member import should be avoided - org.junit.Assert.assertEquals. at Line: 39 Column: None
5. Message: Using a static member import should be avoided - org.junit.Assert.assertNull. at Line: 40 Column: None
6. Message: Using a static member import should be avoided - org.junit.Assert.assertThat. at Line: 41 Column: None
7. Message: Using a static member import should be avoided - org.mockito.Mockito.*. at Line: 42 Column: None





Newly Fixed Tests:
-----------------
org.pentaho.platform.repository2.unified.DefaultUnifiedRepositoryAuthorizationIT.testOwnership: org.pentaho.platform.api.repository2.unified.UnifiedRepositoryException
```
org.pentaho.platform.api.repository2.unified.UnifiedRepositoryException: exception while updating ACL for file with id "81b785b8-e2e3-4dc6-bbd8-952250719778"

Reference number: d247b584-399f-4768-bf0f-1b0de2b196e2
	at org.pentaho.platform.repository2.unified.ExceptionLoggingDecorator.callLogThrow(ExceptionLoggingDecorator.java:512)
	at org.pentaho.platform.repository2.unified.ExceptionLoggingDecorator.updateAcl(ExceptionLoggingDecorator.java:424)
	at org.pentaho.platform.repository2.unified.DefaultUnifiedRepositoryAuthorizationIT.testOwnership(DefaultUnifiedRepositoryAuthorizationIT.java:446)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)
Caused by: org.pentaho.platform.api.repository2.unified.UnifiedRepositoryAccessDeniedException: Access denied while updating permissions on file with id [ 81b785b8-e2e3-4dc6-bbd8-952250719778 ]
	at org.pentaho.platform.repository2.unified.DefaultUnifiedRepository.updateAcl(DefaultUnifiedRepository.java:435)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.security.intercept.method.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:66)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy17.updateAcl(Unknown Source)
	at org.pentaho.platform.repository2.unified.ExceptionLoggingDecorator$39.call(ExceptionLoggingDecorator.java:426)
	at org.pentaho.platform.repository2.unified.ExceptionLoggingDecorator$39.call(ExceptionLoggingDecorator.java:424)
	at org.pentaho.platform.repository2.unified.ExceptionLoggingDecorator.callLogThrow(ExceptionLoggingDecorator.java:489)

```



Unit test coverage change:
============
org.pentaho.platform.repository2.unified.jcr.jackrabbit.security.SpringSecurityPrincipalProvider:
 * instructionPercentCoverageChange : +0.08%
 * branchPercentCoverageChange :**-0.08%**
 * linePercentCoverageChange : +0.22%
 * complexityPercentCoverageChange : +0.21%
    
Integration test coverage change:
============
org.pentaho.platform.repository2.unified.jcr.sejcr.CredentialsStrategySessionFactory:
 * instructionPercentCoverageChange :**-2.57%**
 * branchPercentCoverageChange :**-1.11%**
 * linePercentCoverageChange :**-1.14%**
 * complexityPercentCoverageChange :**-1.18%**

**Comment by pedrofvteixeira** [comment]
@rmansoor, @lucboudreau updated PR according to wingman report, namely: 
- Message: 'if' is not followed by whitespace. at Line: 160 Column: 7

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f repository/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  repository/src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProvider.java
  repository/test-src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProvider_PrincipalCreation_Test.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File repository/test-src/org/pentaho/platform/repository2/unified/jcr/jackrabbit/security/SpringSecurityPrincipalProvider_PrincipalCreation_Test.java
1. Message: Using a static member import should be avoided - org.hamcrest.CoreMatchers.instanceOf. at Line: 37 Column: None
2. Message: Using a static member import should be avoided - org.hamcrest.CoreMatchers.is. at Line: 38 Column: None
3. Message: Using a static member import should be avoided - org.junit.Assert.assertEquals. at Line: 39 Column: None
4. Message: Using a static member import should be avoided - org.junit.Assert.assertNull. at Line: 40 Column: None
5. Message: Using a static member import should be avoided - org.junit.Assert.assertThat. at Line: 41 Column: None
6. Message: Using a static member import should be avoided - org.mockito.Mockito.*. at Line: 42 Column: None





Newly Fixed Tests:
-----------------
org.pentaho.platform.repository2.unified.DefaultUnifiedRepositoryAuthorizationIT.testOwnership: org.pentaho.platform.api.repository2.unified.UnifiedRepositoryException
```
org.pentaho.platform.api.repository2.unified.UnifiedRepositoryException: exception while updating ACL for file with id "28615337-667a-4467-94c0-a7f9b535d54f"

Reference number: 0fe6d79e-266d-4850-93b3-7608961847af
	at org.pentaho.platform.repository2.unified.ExceptionLoggingDecorator.callLogThrow(ExceptionLoggingDecorator.java:512)
	at org.pentaho.platform.repository2.unified.ExceptionLoggingDecorator.updateAcl(ExceptionLoggingDecorator.java:424)
	at org.pentaho.platform.repository2.unified.DefaultUnifiedRepositoryAuthorizationIT.testOwnership(DefaultUnifiedRepositoryAuthorizationIT.java:446)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)
Caused by: org.pentaho.platform.api.repository2.unified.UnifiedRepositoryAccessDeniedException: Access denied while updating permissions on file with id [ 28615337-667a-4467-94c0-a7f9b535d54f ]
	at org.pentaho.platform.repository2.unified.DefaultUnifiedRepository.updateAcl(DefaultUnifiedRepository.java:435)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.security.intercept.method.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:66)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy17.updateAcl(Unknown Source)
	at org.pentaho.platform.repository2.unified.ExceptionLoggingDecorator$39.call(ExceptionLoggingDecorator.java:426)
	at org.pentaho.platform.repository2.unified.ExceptionLoggingDecorator$39.call(ExceptionLoggingDecorator.java:424)
	at org.pentaho.platform.repository2.unified.ExceptionLoggingDecorator.callLogThrow(ExceptionLoggingDecorator.java:489)

```



Unit test coverage change:
============
org.pentaho.platform.repository2.unified.jcr.jackrabbit.security.SpringSecurityPrincipalProvider:
 * instructionPercentCoverageChange : +0.08%
 * branchPercentCoverageChange :**-0.08%**
 * linePercentCoverageChange : +0.22%
 * complexityPercentCoverageChange : +0.21%
    
Integration test coverage change:
============
org.pentaho.platform.repository2.unified.jcr.sejcr.CredentialsStrategySessionFactory:
 * instructionPercentCoverageChange :**-2.57%**
 * branchPercentCoverageChange :**-1.11%**
 * linePercentCoverageChange :**-1.14%**
 * complexityPercentCoverageChange :**-1.18%**

**Pull request merged**
