### PR TITLE
BISERVER-13000 As developer I want to be able to assemble CE pentaho-platform for java 8

### PR DESCRIPTION
**Pull request by prakapenka**
Java 8 adds new methods to abstract classes used in doclet api. For unit
testing we use to have hierarchy to this classes as a stubs. For java 7
they compiled successfully, for java 8 is not since the lack of
implementations of new methods.

For unit testing we can just have mocks. We need to add mockito as ivy
dependency and rewrite testing code. After this project will be able to be
assembled using java 8 jdk.

### CODE REVIEW

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.1 -Djunit.jvmargs=-XX:PermSize=256m -f build-utils/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  build-utils/ivy.xml
  build-utils/test-src/org/pentaho/wadl/PentahoResourceDocletTest.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockClassDoc.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockDeprecatedAnnotationDesc.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockDeprecatedAnnotationTypeDoc.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockMethodDoc.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockPathAnnotationDesc.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockPathAnnotationTypeDoc.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockRootDoc.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File build-utils/test-src/org/pentaho/wadl/PentahoResourceDocletTest.java
1. Message: Unused import - org.mockito.Mock. at Line: 14 Column: 8
2. Message: Unused import - org.mockito.Mockito. at Line: 15 Column: 8
3. Message: '{' is not preceded with whitespace. at Line: 42 Column: 23
4. Message: '(' is not followed by whitespace. at Line: 43 Column: 37
5. Message: ')' is not preceded with whitespace. at Line: 43 Column: 60
6. Message: '(' is not followed by whitespace. at Line: 44 Column: 10
7. Message: '(' is not followed by whitespace. at Line: 44 Column: 58
8. Message: ')' is not preceded with whitespace. at Line: 44 Column: 45
9. Message: ')' is not preceded with whitespace. at Line: 44 Column: 70
10. Message: '(' is not followed by whitespace. at Line: 46 Column: 37
11. Message: ')' is not preceded with whitespace. at Line: 46 Column: 57
12. Message: '(' is not followed by whitespace. at Line: 47 Column: 10
13. Message: '(' is not followed by whitespace. at Line: 47 Column: 64
14. Message: ')' is not preceded with whitespace. at Line: 47 Column: 51
15. Message: ')' is not preceded with whitespace. at Line: 47 Column: 88
16. Message: '(' is not followed by whitespace. at Line: 48 Column: 10
17. Message: '(' is not followed by whitespace. at Line: 48 Column: 58
18. Message: ')' is not preceded with whitespace. at Line: 48 Column: 45
19. Message: ')' is not preceded with whitespace. at Line: 48 Column: 81
20. Message: '(' is not followed by whitespace. at Line: 50 Column: 31
21. Message: ')' is not preceded with whitespace. at Line: 50 Column: 51
22. Message: '(' is not followed by whitespace. at Line: 51 Column: 10
23. Message: '(' is not followed by whitespace. at Line: 51 Column: 58
24. Message: ')' is not preceded with whitespace. at Line: 51 Column: 45
25. Message: ')' is not preceded with whitespace. at Line: 51 Column: 82
26. Message: '(' is not followed by whitespace. at Line: 52 Column: 10
27. Message: '(' is not followed by whitespace. at Line: 52 Column: 52
28. Message: ')' is not preceded with whitespace. at Line: 52 Column: 39
29. Message: ')' is not preceded with whitespace. at Line: 52 Column: 71
30. Message: '(' is not followed by whitespace. at Line: 54 Column: 22
31. Message: ')' is not preceded with whitespace. at Line: 54 Column: 37
32. Message: '(' is not followed by whitespace. at Line: 55 Column: 10
33. Message: '(' is not followed by whitespace. at Line: 55 Column: 39
34. Message: ')' is not preceded with whitespace. at Line: 55 Column: 26
35. Message: ')' is not preceded with whitespace. at Line: 55 Column: 51
36. Message: '(' is not followed by whitespace. at Line: 56 Column: 10
37. Message: '(' is not followed by whitespace. at Line: 56 Column: 46
38. Message: ')' is not preceded with whitespace. at Line: 56 Column: 33
39. Message: ')' is not preceded with whitespace. at Line: 56 Column: 60
40. Message: '(' is not followed by whitespace. at Line: 57 Column: 10
41. Message: ')' is not preceded with whitespace. at Line: 57 Column: 115
42. Message: ')' is not preceded with whitespace. at Line: 57 Column: 33
43. Message: '(' is not followed by whitespace. at Line: 59 Column: 21
44. Message: ')' is not preceded with whitespace. at Line: 59 Column: 35
45. Message: '(' is not followed by whitespace. at Line: 60 Column: 10
46. Message: '(' is not followed by whitespace. at Line: 60 Column: 41
47. Message: ')' is not preceded with whitespace. at Line: 60 Column: 28
48. Message: ')' is not preceded with whitespace. at Line: 60 Column: 69
49. Message: '(' is not followed by whitespace. at Line: 61 Column: 10
50. Message: '(' is not followed by whitespace. at Line: 61 Column: 45
51. Message: ')' is not preceded with whitespace. at Line: 61 Column: 113
52. Message: ')' is not preceded with whitespace. at Line: 61 Column: 32
53. Message: '(' is not followed by whitespace. at Line: 63 Column: 20
54. Message: ')' is not preceded with whitespace. at Line: 63 Column: 33
55. Message: '(' is not followed by whitespace. at Line: 64 Column: 10
56. Message: '(' is not followed by whitespace. at Line: 64 Column: 40
57. Message: ')' is not preceded with whitespace. at Line: 64 Column: 27
58. Message: ')' is not preceded with whitespace. at Line: 64 Column: 66


License header violations:
==========================

1. build-utils/test-src/org/pentaho/wadl/PentahoResourceDocletTest.java








Unit test coverage change:
============
org.pentaho.wadl.PentahoResourceDoclet:
 * instructionPercentCoverageChange :**-0.83%**
 * linePercentCoverageChange :**-1.45%**
 * complexityPercentCoverageChange :**-4.00%**
 * methodPercentCoverageChange :**-14.29%**

**Comment by pamval** [comment]
@prakapenka please review codestyle and license header.

I assume the drop in code coverage is because we're eliminating classes, but would like confirmation on that.

**Comment by prakapenka** [comment]
Fix checkstyle violations.

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.1 -Djunit.jvmargs=-XX:PermSize=256m -f build-utils/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  build-utils/ivy.xml
  build-utils/test-src/org/pentaho/wadl/PentahoResourceDocletTest.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockClassDoc.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockDeprecatedAnnotationDesc.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockDeprecatedAnnotationTypeDoc.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockMethodDoc.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockPathAnnotationDesc.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockPathAnnotationTypeDoc.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockRootDoc.java



License header violations:
==========================

1. build-utils/test-src/org/pentaho/wadl/PentahoResourceDocletTest.java








Unit test coverage change:
============
org.pentaho.wadl.PentahoResourceDoclet:
 * instructionPercentCoverageChange :**-0.83%**
 * linePercentCoverageChange :**-1.45%**
 * complexityPercentCoverageChange :**-4.00%**
 * methodPercentCoverageChange :**-14.29%**

**Comment by pamval** [comment]
License header on PentahoResourceDocletTest is still wrong. please fix

**Comment by prakapenka** [comment]
I'll fix but next time I'll consider to put my own extremely proprietary copyright since I am responsible for licensing pentaho code.
And the second thing I see is that license header for other files in neighbor says "Copyright (c) 2002-2013 Pentaho Corporation..  All rights reserved." Is it means that in 2016 copyright is expired?

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.1 -Djunit.jvmargs=-XX:PermSize=256m -f build-utils/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  build-utils/ivy.xml
  build-utils/test-src/org/pentaho/wadl/PentahoResourceDocletTest.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockClassDoc.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockDeprecatedAnnotationDesc.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockDeprecatedAnnotationTypeDoc.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockMethodDoc.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockPathAnnotationDesc.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockPathAnnotationTypeDoc.java
  build-utils/test-src/org/pentaho/wadl/helpers/MockRootDoc.java










Unit test coverage change:
============
org.pentaho.wadl.PentahoResourceDoclet:
 * instructionPercentCoverageChange :**-0.83%**
 * linePercentCoverageChange :**-1.45%**
 * complexityPercentCoverageChange :**-4.00%**
 * methodPercentCoverageChange :**-14.29%**

**Comment by pamval** [comment]
We usually update the copyright year on the files we change.
So I'll ask you the final change of setting the year to 2016 in PentahoResourceDocletTest.java

**Comment by prakapenka** [comment]
updated.

**Pull request merged**
