### PR TITLE
[BISERVER-13664]-Mail Server settings configuration sends email password

### PR DESCRIPTION
**Pull request by PashkovichAndrei**
in clear text

### CODE REVIEW

**Comment by PashkovichAndrei** [comment]
@mbatchelor, @smaring could you please have a look?
Did I cover all cases of mail's password encryption at this PR?

**Comment by PashkovichAndrei** [comment]
@pamval, org.apache.commons.codec.binary.Base64 couldn't be used because of it's not GWT compatible. 

As for Base64Service, do you mean org.pentaho.platform.util.Base64PasswordService?

**Comment by pamval** [comment]
yeah, that one

**Comment by PashkovichAndrei** [comment]
@pamval org.pentaho.platform.util.Base64PasswordService depends on org.apache.commons.codec.binary.Base64. So that class we couldn't use as well.

I found new solution without adding new class, but I need to check that it works as expected.

**Comment by PashkovichAndrei** [comment]
@pamval could you please do review?

**Pull request merged**
