### PR TITLE
[SP-5908] Backport of PDI-19084 - Backward slash ( \ ) is not resolve…

### PR DESCRIPTION
**Pull request by ssamora**
…d in the transformation path after upgrading from 8.1 to 8.3 (9.1 Suite)

@bcostahitachivantara @smmribeiro 

cherry-pick of 2ba0f687b10949ade926d0645d7f07a3d4e3cfb8 (from PR https://github.com/pentaho/pentaho-platform/pull/4829)

### CODE REVIEW

**Review by smmribeiro — APPROVED** [review]
Consistent with the original PR.

**Comment by buildguy** [comment]
### :warning: Build finished in 32m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl repository
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 3 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.condition.javascript.ConditionalExecutionTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/IActionParameter
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.ArchiveLoaderTest.initializationError</b> (click to expand)</summary><p>

```
Failed to transform class with name org.pentaho.platform.plugin.services.importexport.ImportSession. Reason: org.pentaho.platform.api.repository2.unified.RepositoryFileAcl
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importer.PRPTImportHandlerTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/repository2/unified/IPlatformImportBundle
```

</p></details>

  
Tests run: **1962**, Failures: **3**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4840/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 31m 30s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl repository
```
---
:ok_hand: All tests passed!
 
Tests run: **1979**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4840/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by bcostahitachivantara — APPROVED** [review]
Consistent with base bug

**Pull request merged**
