### PR TITLE
BISERVER-13240 If browsers' primary language is not set to en_US Analyzer schemas are not shown to the users

### PR DESCRIPTION
**Pull request by AliaksandrDrebenchuk**
Catalogs loading fixed

### CODE REVIEW

**Comment by AliaksandrDrebenchuk** [comment]
@mdamour1976
@rmansoor
@e-cuellar
@pentaho-nbaker

**Comment by AliaksandrDrebenchuk** [comment]
@mdamour1976
@rmansoor
@e-cuellar
@pentaho-nbaker
please review

**Comment by AliaksandrDrebenchuk** [comment]
@mdamour1976
@rmansoor
@e-cuellar
@pentaho-nbaker
please review

**Comment by pamval** [comment]
@rmansoor can you take a look at this one please?

**Comment by AliaksandrDrebenchuk** [comment]
@mdamour1976
@rmansoor
@e-cuellar
@pentaho-nbaker
please review

**Comment by AliaksandrDrebenchuk** [comment]
@mdamour1976
@rmansoor
@e-cuellar
@pentaho-nbaker
please review

**Comment by pamval** [comment]
@rmansoor @pentaho-nbaker please review

**Comment by AliaksandrDrebenchuk** [comment]
@rmansoor @pentaho-nbaker please review

**Pull request merged**
