### PR TITLE
[BACKLOG-5417] - Fix for an issue of restoring di-server schedules if…

### PR DESCRIPTION
**Pull request by rfellows**
… the input file has a space in the path.

It turns out that the DI server doesn't allow spaces in filenames so they get converted to spaces under the covers.

### CODE REVIEW

**Comment by rfellows** [comment]
@brendan-lynch please review

**Comment by dkincade** [comment]
Any chance for a unit test on this one?

**Comment by dkincade** [comment]
Or an integration test (at a minumum) so we can detect a regression when there are spaces in the name...

**Comment by rfellows** [comment]
working on refactoring the class to make this piece unit testable... PR will follow sometime

**Comment by rfellows** [comment]
new PR with the tests & fix
https://github.com/pentaho/pentaho-platform/pull/2647

**Pull request merged**
