### PR TITLE
[BACKLOG-33914] - JUnit implementation for the delete and create user…

### PR DESCRIPTION
**Pull request by angel-ramoscardona**
… methods

### CODE REVIEW

**Comment by buildguy** [comment]
### :warning: Build finished in 29m 34s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl repository
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.services.importexport.CommandLineProcessorPasswordTest.testInitRestServiceWithKettlePassword</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.test.platform.plugin.services.security.userrole.ldap.UnionizingLdapAuthoritiesPopulatorTests.org.pentaho.test.platform.plugin.services.security.userrole.ldap.UnionizingLdapAuthoritiesPopulatorTests</b> (click to expand)</summary><p>

```
Error creating bean with name 'org.springframework.security.apacheDirectoryServerContainer': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
```

</p></details>

  
Tests run: **1900**, Failures: **2**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4691/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 29m 54s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl repository
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.services.importexport.CommandLineProcessorPasswordTest.testInitRestServiceWithKettlePassword</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.test.platform.plugin.services.security.userrole.ldap.UnionizingLdapAuthoritiesPopulatorTests.org.pentaho.test.platform.plugin.services.security.userrole.ldap.UnionizingLdapAuthoritiesPopulatorTests</b> (click to expand)</summary><p>

```
Error creating bean with name 'org.springframework.security.apacheDirectoryServerContainer': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
```

</p></details>

  
Tests run: **1900**, Failures: **2**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4691/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 30m 11s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl repository
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.services.importexport.CommandLineProcessorPasswordTest.testInitRestServiceWithKettlePassword</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.test.platform.plugin.services.security.userrole.ldap.UnionizingLdapAuthoritiesPopulatorTests.org.pentaho.test.platform.plugin.services.security.userrole.ldap.UnionizingLdapAuthoritiesPopulatorTests</b> (click to expand)</summary><p>

```
Error creating bean with name 'org.springframework.security.apacheDirectoryServerContainer': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
```

</p></details>

  
Tests run: **1900**, Failures: **2**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4691/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 29m 52s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl repository
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.services.importexport.CommandLineProcessorPasswordTest.testInitRestServiceWithKettlePassword</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.test.platform.plugin.services.security.userrole.ldap.UnionizingLdapAuthoritiesPopulatorTests.org.pentaho.test.platform.plugin.services.security.userrole.ldap.UnionizingLdapAuthoritiesPopulatorTests</b> (click to expand)</summary><p>

```
Error creating bean with name 'org.springframework.security.apacheDirectoryServerContainer': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
```

</p></details>

  
Tests run: **1900**, Failures: **2**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4691/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 30m 39s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl repository
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.services.importexport.CommandLineProcessorPasswordTest.testInitRestServiceWithKettlePassword</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.test.platform.plugin.services.security.userrole.ldap.UnionizingLdapAuthoritiesPopulatorTests.org.pentaho.test.platform.plugin.services.security.userrole.ldap.UnionizingLdapAuthoritiesPopulatorTests</b> (click to expand)</summary><p>

```
Error creating bean with name 'org.springframework.security.apacheDirectoryServerContainer': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
```

</p></details>

  
Tests run: **1900**, Failures: **2**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4691/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 30m 42s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl repository
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.services.importexport.CommandLineProcessorPasswordTest.testInitRestServiceWithKettlePassword</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.test.platform.plugin.services.security.userrole.ldap.UnionizingLdapAuthoritiesPopulatorTests.org.pentaho.test.platform.plugin.services.security.userrole.ldap.UnionizingLdapAuthoritiesPopulatorTests</b> (click to expand)</summary><p>

```
Error creating bean with name 'org.springframework.security.apacheDirectoryServerContainer': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
```

</p></details>

  
Tests run: **1900**, Failures: **2**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4691/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 33m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions,repository
```
---
:ok_hand: All tests passed!
 
Tests run: **1900**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4691/7/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by peterrinehart** [comment]
The copyright dates in the IT classes you updated should be updated to 2020.  Don't see any other problems.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 35m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions,repository
```
---
:ok_hand: All tests passed!
 
Tests run: **1900**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4691/8/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
