### PR TITLE
[BISERVER-12851] - Restore (import/export) fails on windows when refe…

### PR DESCRIPTION
**Pull request by rfellows**
…renced files have spaces in the name

### CODE REVIEW

**Comment by rfellows** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java
  extensions/test-src/org/pentaho/platform/plugin/services/importer/SolutionImportHandlerTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File extensions/test-src/org/pentaho/platform/plugin/services/importer/SolutionImportHandlerTest.java
1. Message: Using a static member import should be avoided - org.apache.commons.io.FilenameUtils.separatorsToUnix. at Line: 33 Column: None
2. Message: Using a static member import should be avoided - org.junit.Assert.assertEquals. at Line: 34 Column: None
3. Message: Using a static member import should be avoided - org.junit.Assert.assertTrue. at Line: 35 Column: None
4. Message: Using a static member import should be avoided - org.mockito.Matchers.any. at Line: 36 Column: None
5. Message: Using a static member import should be avoided - org.mockito.Matchers.anyString. at Line: 37 Column: None
6. Message: Using a static member import should be avoided - org.mockito.Matchers.eq. at Line: 38 Column: None
7. Message: Using a static member import should be avoided - org.mockito.Mockito.*. at Line: 39 Column: None
8. Message: '(' is preceded with whitespace. at Line: 411 Column: 30


License header violations:
==========================

1. extensions/test-src/org/pentaho/platform/plugin/services/importer/SolutionImportHandlerTest.java




Newly Fixed Tests:
-----------------
org.pentaho.test.platform.web.ui.component.FilterDefinitionIT.testNothing: java.lang.NoClassDefFoundError
```
java.lang.NoClassDefFoundError: Could not initialize class org.pentaho.platform.repository.hibernate.HibernateUtil
	at org.pentaho.platform.repository.hibernate.HibernateUtil.$jacocoInit(HibernateUtil.java)
	at org.pentaho.platform.repository.hibernate.HibernateUtil.systemExitPoint(HibernateUtil.java)
	at org.pentaho.platform.engine.core.system.StandaloneApplicationContext.invokeExitPoints(StandaloneApplicationContext.java:181)
	at org.pentaho.platform.engine.core.system.PentahoSystem.systemExitPoint(PentahoSystem.java:1217)
	at org.pentaho.test.platform.engine.core.BaseTest.tearDown(BaseTest.java:174)

```
org.pentaho.test.platform.web.ui.component.FilterDefinitionIT.testFilterCreation: java.lang.ExceptionInInitializerError
```
java.lang.ExceptionInInitializerError
	at org.pentaho.platform.repository.hibernate.HibernateUtil.initialize(HibernateUtil.java:199)
	at org.pentaho.platform.repository.hibernate.HibernateUtil.<clinit>(HibernateUtil.java:90)
	at org.pentaho.platform.repository.runtime.RuntimeRepository.setSession(RuntimeRepository.java:72)
	at org.pentaho.platform.repository.runtime.RuntimeRepository.init(RuntimeRepository.java:77)
	at org.pentaho.platform.engine.core.system.objfac.AbstractSpringPentahoObjectFactory.retreiveObject(AbstractSpringPentahoObjectFactory.java:266)
	at org.pentaho.platform.engine.core.system.objfac.AbstractSpringPentahoObjectFactory.get(AbstractSpringPentahoObjectFactory.java:82)
	at org.pentaho.platform.engine.core.system.objfac.AggregateObjectFactory.get(AggregateObjectFactory.java:273)
	at org.pentaho.platform.engine.core.system.objfac.AggregateObjectFactory.get(AggregateObjectFactory.java:137)
	at org.pentaho.platform.engine.core.system.PentahoSystem.get(PentahoSystem.java:767)
	at org.pentaho.platform.engine.core.system.PentahoSystem.get(PentahoSystem.java:748)
	at org.pentaho.platform.engine.services.solution.SolutionEngine.execute(SolutionEngine.java:219)
	at org.pentaho.platform.engine.services.solution.SolutionEngine.execute(SolutionEngine.java:179)
	at org.pentaho.platform.uifoundation.component.ActionFilterDefinition.getResultSet(ActionFilterDefinition.java:85)
	at org.pentaho.platform.uifoundation.component.FilterDefinition.populate(FilterDefinition.java:243)
	at org.pentaho.test.platform.web.ui.component.FilterDefinitionIT.testFilterCreation(FilterDefinitionIT.java:106)
Caused by: org.hibernate.HibernateException: Could not parse configuration: test-src/web-solution/system/hibernate/hsql.hibernate.cfg.xml
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2246)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:2216)
	at org.pentaho.platform.repository.hibernate.HibernateUtil.initialize(HibernateUtil.java:138)
Caused by: org.dom4j.DocumentException: Unexpected end of file from server Nested exception: Unexpected end of file from server
	at org.dom4j.io.SAXReader.read(SAXReader.java:484)
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2238)

```

Still Broken Tests:
-----------------
org.pentaho.test.platform.web.http.api.RepositoryResourceIT.b3_HappyPath_GET_withMimeType: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: Response media type incorrect: expected:<application/pdf;[]charset=UTF-8> but was:<application/pdf;[ ]charset=UTF-8>
	at org.pentaho.test.platform.web.http.api.JerseyTestUtil.assertResponse(JerseyTestUtil.java:47)
	at org.pentaho.test.platform.web.http.api.RepositoryResourceIT.b3_HappyPath_GET_withMimeType(RepositoryResourceIT.java:364)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)

```

Unit test coverage change:
============
org.pentaho.platform.plugin.services.importer.SolutionImportHandler:
 * instructionPercentCoverageChange : +0.65%
 * branchPercentCoverageChange : +0.20%
 * linePercentCoverageChange : +0.66%
 * complexityPercentCoverageChange :**-0.38%**
    
org.pentaho.platform.config.MondrianConfigProperties:
 * instructionPercentCoverageChange : +3.16%
 * branchPercentCoverageChange : +7.14%
    
org.pentaho.platform.admin.GeneratedContentCleaner:
 * branchPercentCoverageChange :**-10.00%**
 * complexityPercentCoverageChange :**-9.09%**
    
Integration test coverage change:
============
org.pentaho.platform.plugin.services.connections.sql.SQLResultSet:
 * instructionPercentCoverageChange : +0.65%
 * linePercentCoverageChange : +1.53%
 * complexityPercentCoverageChange : +2.33%
 * methodPercentCoverageChange : +5.88%
    
org.pentaho.platform.plugin.services.importer.SolutionImportHandler:
 * instructionPercentCoverageChange :**-0.38%**
 * branchPercentCoverageChange :**-0.43%**
 * linePercentCoverageChange :**-0.49%**
 * complexityPercentCoverageChange :**-0.27%**
    
org.pentaho.platform.plugin.action.sql.SQLBaseComponent:
 * instructionPercentCoverageChange : +1.99%
 * branchPercentCoverageChange : +2.27%
 * linePercentCoverageChange : +2.90%
 * complexityPercentCoverageChange : +1.75%
 * methodPercentCoverageChange : +3.85%
    
org.pentaho.platform.plugin.action.chartbeans.ChartAction:
 * instructionPercentCoverageChange :**-0.22%**

**Comment by rfellows** [comment]
@DFieldFL please review. If you really want me to fix the checkstyle issues in the unit test... i will. other than that, it's good.

**Comment by lucboudreau** [comment]
> If you really want me to fix the checkstyle issues in the unit test... i will.

Please fix them. There is also a 10% drop of coverage in GeneratedContentCleaner as well as a missing license header.

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java
  extensions/test-src/org/pentaho/platform/plugin/services/importer/SolutionImportHandlerTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File extensions/test-src/org/pentaho/platform/plugin/services/importer/SolutionImportHandlerTest.java
1. Message: Using a static member import should be avoided - org.apache.commons.io.FilenameUtils.separatorsToUnix. at Line: 50 Column: None
2. Message: Using a static member import should be avoided - org.junit.Assert.assertEquals. at Line: 51 Column: None
3. Message: Using a static member import should be avoided - org.junit.Assert.assertTrue. at Line: 52 Column: None
4. Message: Using a static member import should be avoided - org.mockito.Matchers.any. at Line: 53 Column: None
5. Message: Using a static member import should be avoided - org.mockito.Matchers.anyString. at Line: 54 Column: None
6. Message: Using a static member import should be avoided - org.mockito.Matchers.eq. at Line: 55 Column: None
7. Message: Using a static member import should be avoided - org.mockito.Mockito.*. at Line: 56 Column: None







Still Broken Tests:
-----------------
org.pentaho.test.platform.web.http.api.RepositoryResourceIT.b3_HappyPath_GET_withMimeType: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: Response media type incorrect: expected:<application/pdf;[]charset=UTF-8> but was:<application/pdf;[ ]charset=UTF-8>
	at org.pentaho.test.platform.web.http.api.JerseyTestUtil.assertResponse(JerseyTestUtil.java:47)
	at org.pentaho.test.platform.web.http.api.RepositoryResourceIT.b3_HappyPath_GET_withMimeType(RepositoryResourceIT.java:364)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)

```

Unit test coverage change:
============
org.pentaho.platform.plugin.services.importer.SolutionImportHandler:
 * instructionPercentCoverageChange : +0.65%
 * branchPercentCoverageChange : +0.20%
 * linePercentCoverageChange : +0.66%
 * complexityPercentCoverageChange :**-0.38%**
    
org.pentaho.platform.config.MondrianConfigProperties:
 * instructionPercentCoverageChange :**-3.16%**
 * branchPercentCoverageChange :**-7.14%**
    
Integration test coverage change:
============
org.pentaho.platform.plugin.services.importer.SolutionImportHandler:
 * instructionPercentCoverageChange :**-0.38%**
 * branchPercentCoverageChange :**-0.43%**
 * linePercentCoverageChange :**-0.49%**
 * complexityPercentCoverageChange :**-0.27%**
    
org.pentaho.platform.plugin.services.pluginmgr.PentahoSystemPluginManager:
 * instructionPercentCoverageChange : +0.04%
 * branchPercentCoverageChange : +0.45%
 * linePercentCoverageChange : +0.21%
 * complexityPercentCoverageChange : +0.65%

**Comment by akhayrutdinov** [comment]
@DFieldFL, can you please proceed this PR today to let it be backported to an upcoming service pack? This changes seem to be quite simple and straightforward

/cc @pamval, @pentaho-nbaker, @rmansoor

**Comment by DFieldFL** [comment]
I will wait for @lucboudreau to comment on the last wingman comment. Otherwise the code looks good.

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f extensions/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  extensions/src/org/pentaho/platform/plugin/services/importer/SolutionImportHandler.java
  extensions/test-src/org/pentaho/platform/plugin/services/importer/SolutionImportHandlerTest.java








Still Broken Tests:
-----------------
org.pentaho.test.platform.web.http.api.RepositoryResourceIT.b3_HappyPath_GET_withMimeType: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: Response media type incorrect: expected:<application/pdf;[]charset=UTF-8> but was:<application/pdf;[ ]charset=UTF-8>
	at org.pentaho.test.platform.web.http.api.JerseyTestUtil.assertResponse(JerseyTestUtil.java:47)
	at org.pentaho.test.platform.web.http.api.RepositoryResourceIT.b3_HappyPath_GET_withMimeType(RepositoryResourceIT.java:364)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)

```

Unit test coverage change:
============
org.pentaho.platform.plugin.services.importer.SolutionImportHandler:
 * instructionPercentCoverageChange : +0.65%
 * branchPercentCoverageChange : +0.20%
 * linePercentCoverageChange : +0.66%
 * complexityPercentCoverageChange :**-0.38%**
    
org.pentaho.platform.admin.GeneratedContentCleaner:
 * branchPercentCoverageChange :**-10.00%**
 * complexityPercentCoverageChange :**-9.09%**
    
Integration test coverage change:
============
org.pentaho.platform.plugin.services.importer.SolutionImportHandler:
 * instructionPercentCoverageChange :**-0.38%**
 * branchPercentCoverageChange :**-0.43%**
 * linePercentCoverageChange :**-0.49%**
 * complexityPercentCoverageChange :**-0.27%**
    
org.pentaho.platform.plugin.services.pluginmgr.PentahoSystemPluginManager:
 * instructionPercentCoverageChange :**-0.04%**
 * branchPercentCoverageChange :**-0.45%**
 * linePercentCoverageChange :**-0.21%**
 * complexityPercentCoverageChange :**-0.65%**

**Pull request merged**
