### PR TITLE
[BACKLOG-36879][BACKLOG-37033][BACKLOG-37034] GWT/XUL Dialogs Default, Trap and Restore Focus

### PR DESCRIPTION
**Pull request by dcleao**
Part of PR set: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1617.

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 1m 27s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 16s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 36s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 13s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Review by NJtwentyone — APPROVED** [review]

**Review by NJtwentyone — CHANGES_REQUESTED** [review]
wingman build is failing, I'm assuming it depends on the other  PR branches to be merged first.

**Comment by buildguy** [comment]
### :x: Build failed in 1m 32s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5226/5/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 14s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5226/6/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by dcleao** [comment]
@NJtwentyone  Don't understand. Merged the GWT dependency. Now, the build is failing due to something which was supposedly fixed by another PR the other day (https://github.com/pentaho/pentaho-platform/pull/5221):
> [2023-02-15T21:27:44.871Z] [ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.9.0:compile (default) on project pentaho-user-console: GWT Module org.pentaho.platform.EmailSupport not found in project sources or resources.

**Comment by dcleao** [comment]
Going to merge this, or the overall build will really fail due to changes in dependencies.

**Comment by dcleao** [comment]
Rewrote history to remove "temporary" commits.

**Pull request merged**
