### PR TITLE
[PDI-20086] Implement a file lock to prevent multiple karaf instances

### PR DESCRIPTION
**Pull request by peterrinehart**
from booting at the same time, which may lead to config file corruption or instances starting without a proper karaf environment.

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 5m 20s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl extensions
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by ddiroma — APPROVED** [review]

**Comment by buildguy** [comment]
### :x: Build failed in 4m 10s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl extensions
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 33m 43s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1572**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5678/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by ddiroma — APPROVED** [review]

**Pull request merged**
