### PR TITLE
[SP-3843][PDI-14442]-PDI Import scripts are executed in parallel by multiple users

### PR DESCRIPTION
**Pull request by stepanovdg**

### CODE REVIEW

**Comment by stepanovdg** [comment]
@mchen-len-son Could you please take a look?

**Comment by mchen-len-son** [comment]
@stepanovdg some files have Hitachi Vantara copyright, some not - let's stay consistent.

**Comment by stepanovdg** [comment]
@mchen-len-son Updated.

**Comment by mchen-len-son** [comment]
There is no decision on copyright headers for 7.1 yet.
Besides that everything looks ok, double-checked locally.
Merging.

**Pull request merged**
