### PR TITLE
[TEST] increase test coverage

### PR DESCRIPTION
**Pull request by DFieldFL**

### CODE REVIEW

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f api/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  api/test-src/org/pentaho/platform/api/repository2/unified/data/SimpleRepositoryFileDataTest.java

Checkstyle violations:
======================
File api/test-src/org/pentaho/platform/api/repository2/unified/data/SimpleRepositoryFileDataTest.java
1. Message: 'catch' is not followed by whitespace. at Line: 79 Column: 12
2. Message: ')' is not preceded with whitespace. at Line: 80 Column: 45
3. Message: 'catch' is not followed by whitespace. at Line: 93 Column: 12
4. Message: ')' is not preceded with whitespace. at Line: 94 Column: 45


License header violations:
==========================
No violations found








Unit test coverage change:
============
org.pentaho.platform.api.repository2.unified.data.simple.SimpleRepositoryFileData:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :91.89%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :93.36%

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f api/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  api/test-src/org/pentaho/platform/api/repository2/unified/data/SimpleRepositoryFileDataTest.java

Checkstyle violations:
======================
No errors found

License header violations:
==========================
No violations found








Unit test coverage change:
============
org.pentaho.platform.api.repository2.unified.data.simple.SimpleRepositoryFileData:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :91.89%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :93.36%

**Comment by DFieldFL** [comment]
@pminutillo @bytekast @kurtwalker please review and merge.

**Comment by lucboudreau** [comment]
According to the wingman comment, this PR did not increase coverage. I think there is a missing annotation on the test class.

**Comment by DFieldFL** [comment]
I did run the wingman twice...maybe it cached the results from the first run? This is a brand new file.

**Comment by DFieldFL** [comment]
Here is my result from my local machine running jacoco 

```
[junit] Running org.pentaho.platform.api.repository2.unified.data.SimpleRepositoryFileDataTest
[junit] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.416 sec
```

**Comment by lucboudreau** [comment]
SimpleRepositoryFileData is not new. It doesn't have a + to its stats either. That's why I think the new tests didn't kick in.

**Comment by lucboudreau** [comment]
ok this could be a wingman issue. Thanks! cc @brosander

**Comment by DFieldFL** [comment]
Could be. I understood the wingman to compare PR stats to Pentaho master stats, which would then show the increase. Maybe that has changed.

**Comment by brosander** [comment]
@lucboudreau if the coverage was either not there or at 0% initially, it treats that as nonexistent and I'd expect it to print the new coverage level without a + (what we see here) guess we need to define expected behavior

/cc @DFieldFL

**Pull request merged**
