### PR TITLE
[BISERVER-14523] New Mondrian Catalog Cache Supporting Incremental ca…

### PR DESCRIPTION
**Pull request by tkafalas**
…ching

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 27m 49s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1543**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4786/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 27m 53s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1543**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4786/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 27m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1543**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4786/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 20s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
Command "git checkout -f 7f6d870e555f5a741c8ec136a39af21fa36d7084" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: 7f6d870e555f5a741c8ec136a39af21fa36d7084
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 31m 52s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1543**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/platform/job/PR-4786/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by tkafalas** [comment]
This PR has 3 code smells.  One deals with removing a deprecated method for which there is no replacement.  Another deals with the use of instanceof in a catch block, however, the catch runs common code for all exceptions caught then tests instanceof to see if it need to rewrap the error before throwing it upsteam.  The last smell is a 16 complexity out of 15.  The method is linear in nature with alot of unnested ifs to see what lines to execute.  In my opinion breaking this up would only add to the complexity since there is no other clear reason to do so.

**Comment by ddiroma** [comment]
Approved

**Pull request merged**
